LBIS.EnchantSources =
{
	[240133] = {
		Name = "Sunfire Silk Spellthread",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[240155] = {
		Name = "Arcanoweave Spellthread",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[240167] = {
		Name = "Arcanoweave Lining",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243950] = {
		Name = "Enchant Helm - Empowered Hex of Leeching",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243952] = {
		Name = "Enchant Boots - Lynx's Dexterity",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243956] = {
		Name = "Enchant Ring - Eyes of the Eagle",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243959] = {
		Name = "Enchant Ring - Zul'jin's Mastery",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243962] = {
		Name = "Enchant Shoulders - Akil'zon's Swiftness",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243970] = {
		Name = "Enchant Weapon - Jan'alai's Precision",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243973] = {
		Name = "Enchant Weapon - Berserker's Rage",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243977] = {
		Name = "Enchant Chest - Mark of the Worldsoul",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243981] = {
		Name = "Enchant Helm - Empowered Blessing of Speed",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243983] = {
		Name = "Enchant Boots - Shaladrassil's Roots",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243986] = {
		Name = "Enchant Ring - Nature's Fury",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[243990] = {
		Name = "Enchant Shoulders - Amirdrassil's Grace",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244002] = {
		Name = "Enchant Chest - Mark of the Magister",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244007] = {
		Name = "Enchant Helm - Empowered Rune of Avoidance",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244008] = {
		Name = "Enchant Boots - Farstrider's Hunt",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244014] = {
		Name = "Enchant Ring - Silvermoon's Alacrity",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244016] = {
		Name = "Enchant Ring - Silvermoon's Tenacity",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244021] = {
		Name = "Enchant Shoulders - Silvermoon's Mending",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244029] = {
		Name = "Enchant Weapon - Acuity of the Ren'dorei",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244031] = {
		Name = "Enchant Weapon - Arcane Mastery",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244640] = {
		Name = "Forest Hunter's Armor Kit",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
	[244642] = {
		Name = "Blood Knight's Armor Kit",
		IsSpell = "False",
		DesignId = "0",
		Source = "Enchanting",
		SourceLocation = "",
		TextureId = "0",
	},
}