----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_AID_OF_THE_ILLIDARI"] = "伊利达雷的援手"
L["BTWQUESTS_ARTIFACT"] = "神器"
L["BTWQUESTS_FATE_OF_THE_TIDESKORN"] = "蔑潮的命运"
L["BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM"] = "邪能图腾的骚动"
L["BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION"] = "鲑鱼溪调查"
L["BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE"] = "莱维娅·劳伦斯的窘境"
L["BTWQUESTS_THE_THIEVING_APPRENTICE"] = "顺手牵羊"
L["BTWQUESTS_THE_TWISTED_TWINS"] = "扭曲的双子"
