----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhTW" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_AID_OF_THE_ILLIDARI"] = "伊利達瑞的援助"
L["BTWQUESTS_ARTIFACT"] = "神器"
L["BTWQUESTS_FATE_OF_THE_TIDESKORN"] = "蔑潮的命運"
L["BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM"] = "魔化圖騰附近的威脅"
L["BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION"] = "布瑞登溪調查"
L["BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE"] = "蕾薇亞‧勞倫斯的愚行"
L["BTWQUESTS_THE_THIEVING_APPRENTICE"] = "偷竊的學徒"
L["BTWQUESTS_THE_TWISTED_TWINS"] = "扭曲的雙胞胎弟弟"
