local LSM = LibStub("LibSharedMedia-3.0") 
-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "BlizzardCast", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCast.tga]]) 
LSM:Register("statusbar", "BlizzardCastBackground", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCastBackground.tga]]) 
LSM:Register("statusbar", "BlizzardCastBgRound", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCastBgRound.tga]]) 
LSM:Register("statusbar", "BlizzardCastLite", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCastLite.tga]]) 
LSM:Register("statusbar", "BlizzardCastRound", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCastRound.tga]]) 
LSM:Register("statusbar", "BlizzardCastUninterruptableRound", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardCastUninterruptableRound.tga]]) 
LSM:Register("statusbar", "BlizzardChannelRound", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardChannelRound.tga]]) 
LSM:Register("statusbar", "BlizzardContainerFrame", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardContainerFrame.tga]]) 
LSM:Register("statusbar", "BlizzardDF_bar", [[Interface\Addons\WYJJDB\Media\statusbar\BlizzardDF_bar.tga]]) 
LSM:Register("statusbar", "SmokAugbar", [[Interface\Addons\WYJJDB\Media\statusbar\SmokAugbar.tga]]) 
LSM:Register("statusbar", "SmokObjectiveTracker", [[Interface\Addons\WYJJDB\Media\statusbar\SmokObjectiveTracker.tga]]) 
LSM:Register("statusbar", "SmokOnePixelBackground", [[Interface\Addons\WYJJDB\Media\statusbar\SmokOnePixelBackground.tga]]) 
LSM:Register("statusbar", "SmokOnePixelbar", [[Interface\Addons\WYJJDB\Media\statusbar\SmokOnePixelbar.tga]]) 
LSM:Register("statusbar", "spec_icons_normal_alpha3", [[Interface\Addons\WYJJDB\Media\statusbar\spec_icons_normal_alpha3.tga]]) 
-- -----
--   SOUND
-- -----
LSM:Register("sound", "|cFFAEEA941|r", [[Interface\Addons\WYJJDB\Media\sound\1.ogg]])
LSM:Register("sound", "|cFFAEEA942|r", [[Interface\Addons\WYJJDB\Media\sound\2.ogg]])
LSM:Register("sound", "|cFFAEEA943|r", [[Interface\Addons\WYJJDB\Media\sound\3.ogg]])
LSM:Register("sound", "|cFFAEEA944|r", [[Interface\Addons\WYJJDB\Media\sound\4.ogg]])
LSM:Register("sound", "|cFFAEEA945|r", [[Interface\Addons\WYJJDB\Media\sound\5.ogg]])
LSM:Register("sound", "|cFFAEEA946|r", [[Interface\Addons\WYJJDB\Media\sound\6.ogg]])
LSM:Register("sound", "|cFFAEEA947|r", [[Interface\Addons\WYJJDB\Media\sound\7.ogg]])
LSM:Register("sound", "|cFFAEEA948|r", [[Interface\Addons\WYJJDB\Media\sound\8.ogg]])
LSM:Register("sound", "|cFFAEEA949|r", [[Interface\Addons\WYJJDB\Media\sound\9.ogg]])
LSM:Register("sound", "|cFFAEEA9410|r", [[Interface\Addons\WYJJDB\Media\sound\10.ogg]])
LSM:Register("sound", "|cFFAEEA94D 第一|r", [[Interface\Addons\WYJJDB\Media\sound\First.ogg]])
LSM:Register("sound", "|cFFAEEA94D 第二|r", [[Interface\Addons\WYJJDB\Media\sound\Second.ogg]])
LSM:Register("sound", "|cFFAEEA94D 第三|r", [[Interface\Addons\WYJJDB\Media\sound\Third.ogg]])
LSM:Register("sound", "|cFFAEEA94D 第四|r", [[Interface\Addons\WYJJDB\Media\sound\Fourth.ogg]])
LSM:Register("sound", "|cFFAEEA94D 第五|r", [[Interface\Addons\WYJJDB\Media\sound\Fifth.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\WYJJDB\Media\sound\01.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\WYJJDB\Media\sound\02.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\WYJJDB\Media\sound\03.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\WYJJDB\Media\sound\04.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\WYJJDB\Media\sound\05.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\WYJJDB\Media\sound\06.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\WYJJDB\Media\sound\07.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\WYJJDB\Media\sound\08.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 准备大怪|r", [[Interface\Addons\WYJJDB\Media\sound\Add.ogg]])
LSM:Register("sound", "|cFFAEEA94X 小怪快打|r", [[Interface\Addons\WYJJDB\Media\sound\Adds.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 注意词缀|r", [[Interface\Addons\WYJJDB\Media\sound\Affix.ogg]])
LSM:Register("sound", "|cFFAEEA94A AoE|r", [[Interface\Addons\WYJJDB\Media\sound\AoE.ogg]])
LSM:Register("sound", "|cFFAEEA94X 协助|r", [[Interface\Addons\WYJJDB\Media\sound\Assist.ogg]])
LSM:Register("sound", "|cFFAEEA94G 规避|r", [[Interface\Addons\WYJJDB\Media\sound\Avoid.ogg]])
LSM:Register("sound", "|cFFAEEA94H 后退|r", [[Interface\Addons\WYJJDB\Media\sound\Back.ogg]])
LSM:Register("sound", "|cFFAEEA94B 备选|r", [[Interface\Addons\WYJJDB\Media\sound\Backup.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 引导位置|r", [[Interface\Addons\WYJJDB\Media\sound\Bait.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 注意射线|r", [[Interface\Addons\WYJJDB\Media\sound\Beam.ogg]])
LSM:Register("sound", "|cFFAEEA94T 坦克承伤|r", [[Interface\Addons\WYJJDB\Media\sound\Bite.ogg]])
LSM:Register("sound", "|cFFAEEA94S 嗜血|r", [[Interface\Addons\WYJJDB\Media\sound\Bloodlust.ogg]])
LSM:Register("sound", "|cFFAEEA94L 蓝色|r", [[Interface\Addons\WYJJDB\Media\sound\Blue.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 炸弹|r", [[Interface\Addons\WYJJDB\Media\sound\Bombs.ogg]])
LSM:Register("sound", "|cFFAEEA94A Boss|r", [[Interface\Addons\WYJJDB\Media\sound\Boss.ogg]])
LSM:Register("sound", "|cFFAEEA94D 打破|r", [[Interface\Addons\WYJJDB\Media\sound\Break.ogg]])
LSM:Register("sound", "|cFFAEEA94A Buff|r", [[Interface\Addons\WYJJDB\Media\sound\Buff.ogg]])
LSM:Register("sound", "|cFFAEEA94K 快交控制|r", [[Interface\Addons\WYJJDB\Media\sound\CC.ogg]])
LSM:Register("sound", "|cFFAEEA94A CD|r", [[Interface\Addons\WYJJDB\Media\sound\CD.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 中间|r", [[Interface\Addons\WYJJDB\Media\sound\Center.ogg]])
LSM:Register("sound", "|cFFAEEA94S 锁链|r", [[Interface\Addons\WYJJDB\Media\sound\Chain.ogg]])
LSM:Register("sound", "|cFFAEEA94C 冲锋|r", [[Interface\Addons\WYJJDB\Media\sound\Charge.ogg]])
LSM:Register("sound", "|cFFAEEA94J 检查|r", [[Interface\Addons\WYJJDB\Media\sound\Check.ogg]])
LSM:Register("sound", "|cFFAEEA94Q 清除|r", [[Interface\Addons\WYJJDB\Media\sound\Clear.ogg]])
LSM:Register("sound", "|cFFAEEA94S 收集|r", [[Interface\Addons\WYJJDB\Media\sound\Collect.ogg]])
LSM:Register("sound", "|cFFAEEA94D 躲地板|r", [[Interface\Addons\WYJJDB\Media\sound\Dance.ogg]])
LSM:Register("sound", "|cFFAEEA94F 防御|r", [[Interface\Addons\WYJJDB\Media\sound\Defensive.ogg]])
LSM:Register("sound", "|cFFAEEA94A Debuff|r", [[Interface\Addons\WYJJDB\Media\sound\Debuff.ogg]])
LSM:Register("sound", "|cFFAEEA94Q 驱散|r", [[Interface\Addons\WYJJDB\Media\sound\Dispell.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 注意躲避|r", [[Interface\Addons\WYJJDB\Media\sound\Dodge.ogg]])
LSM:Register("sound", "|cFFAEEA94B 不要|r", [[Interface\Addons\WYJJDB\Media\sound\Dont.ogg]])
LSM:Register("sound", "|cFFAEEA94T 停止移动|r", [[Interface\Addons\WYJJDB\Media\sound\Dont Move.ogg]])
LSM:Register("sound", "|cFFAEEA94A Dot|r", [[Interface\Addons\WYJJDB\Media\sound\Dot.ogg]])
LSM:Register("sound", "|cFFAEEA94F 放水|r", [[Interface\Addons\WYJJDB\Media\sound\Drop.ogg]])
LSM:Register("sound", "|cFFAEEA94J 进入|r", [[Interface\Addons\WYJJDB\Media\sound\Enter.ogg]])
LSM:Register("sound", "|cFFAEEA94S 哨兵|r", [[Interface\Addons\WYJJDB\Media\sound\Escort.ogg]])
LSM:Register("sound", "|cFFAEEA94T 退出|r", [[Interface\Addons\WYJJDB\Media\sound\Exit.ogg]])
LSM:Register("sound", "|cFFAEEA94W 外部|r", [[Interface\Addons\WYJJDB\Media\sound\External.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 注意脚下|r", [[Interface\Addons\WYJJDB\Media\sound\Feet.ogg]])
LSM:Register("sound", "|cFFAEEA94M 目标锁定|r", [[Interface\Addons\WYJJDB\Media\sound\Fixate.ogg]])
LSM:Register("sound", "|cFFAEEA94J 焦点|r", [[Interface\Addons\WYJJDB\Media\sound\Focus.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 注意头前|r", [[Interface\Addons\WYJJDB\Media\sound\Front.ogg]])
LSM:Register("sound", "|cFFAEEA94K 开门|r", [[Interface\Addons\WYJJDB\Media\sound\Gate.ogg]])
LSM:Register("sound", "|cFFAEEA94S 收集|r", [[Interface\Addons\WYJJDB\Media\sound\Gather.ogg]])
LSM:Register("sound", "|cFFAEEA94L 绿色|r", [[Interface\Addons\WYJJDB\Media\sound\Green.ogg]])
LSM:Register("sound", "|cFFAEEA94Q 前进|r", [[Interface\Addons\WYJJDB\Media\sound\Go.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 抓紧|r", [[Interface\Addons\WYJJDB\Media\sound\Grip.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 治疗CD|r", [[Interface\Addons\WYJJDB\Media\sound\Healcd.ogg]])
LSM:Register("sound", "|cFFAEEA94D 躲避伤害|r", [[Interface\Addons\WYJJDB\Media\sound\Hide.ogg]])
LSM:Register("sound", "|cFFAEEA94N 能量过高|r", [[Interface\Addons\WYJJDB\Media\sound\High Energy.ogg]])
LSM:Register("sound", "|cFFAEEA94C 层数过高|r", [[Interface\Addons\WYJJDB\Media\sound\High Stacks.ogg]])
LSM:Register("sound", "|cFFAEEA94M 免疫|r", [[Interface\Addons\WYJJDB\Media\sound\Immunity.ogg]])
LSM:Register("sound", "|cFFAEEA94J 进进进|r", [[Interface\Addons\WYJJDB\Media\sound\In.ogg]])
LSM:Register("sound", "|cFFAEEA94D 打断施法|r", [[Interface\Addons\WYJJDB\Media\sound\Interrupt.ogg]])
LSM:Register("sound", "|cFFAEEA94J 阶段转换|r", [[Interface\Addons\WYJJDB\Media\sound\Intermission.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 隐身|r", [[Interface\Addons\WYJJDB\Media\sound\Invisibility.ogg]])
LSM:Register("sound", "|cFFAEEA94T 跳|r", [[Interface\Addons\WYJJDB\Media\sound\Jump.ogg]])
LSM:Register("sound", "|cFFAEEA94K 快打断|r", [[Interface\Addons\WYJJDB\Media\sound\Kick.ogg]])
LSM:Register("sound", "|cFFAEEA94F 风筝|r", [[Interface\Addons\WYJJDB\Media\sound\Kite.ogg]])
LSM:Register("sound", "|cFFAEEA94J 击飞|r", [[Interface\Addons\WYJJDB\Media\sound\Knock.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 最后|r", [[Interface\Addons\WYJJDB\Media\sound\Last.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 左边|r", [[Interface\Addons\WYJJDB\Media\sound\Left.ogg]])
LSM:Register("sound", "|cFFAEEA94T 跳跃|r", [[Interface\Addons\WYJJDB\Media\sound\Leap.ogg]])
LSM:Register("sound", "|cFFAEEA94L 连线|r", [[Interface\Addons\WYJJDB\Media\sound\Line.ogg]])
LSM:Register("sound", "|cFFAEEA94L 链接|r", [[Interface\Addons\WYJJDB\Media\sound\Link.ogg]])
LSM:Register("sound", "|cFFAEEA94B 被连接|r", [[Interface\Addons\WYJJDB\Media\sound\Linked.ogg]])
LSM:Register("sound", "|cFFAEEA94K 卡视野|r", [[Interface\Addons\WYJJDB\Media\sound\LoS.ogg]])
LSM:Register("sound", "|cFFAEEA94H 宏|r", [[Interface\Addons\WYJJDB\Media\sound\Macro.ogg]])
LSM:Register("sound", "|cFFAEEA94J 近战|r", [[Interface\Addons\WYJJDB\Media\sound\Melee.ogg]])
LSM:Register("sound", "|cFFAEEA94D 地雷|r", [[Interface\Addons\WYJJDB\Media\sound\Mines.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 移动|r", [[Interface\Addons\WYJJDB\Media\sound\Move.ogg]])
LSM:Register("sound", "|cFFAEEA94X 下一个|r", [[Interface\Addons\WYJJDB\Media\sound\Next.ogg]])
LSM:Register("sound", "|cFFAEEA94J 集中攻击|r", [[Interface\Addons\WYJJDB\Media\sound\Nuke.ogg]])
LSM:Register("sound", "|cFFAEEA94C 橙色|r", [[Interface\Addons\WYJJDB\Media\sound\Orange.ogg]])
LSM:Register("sound", "|cFFAEEA94B 宝珠|r", [[Interface\Addons\WYJJDB\Media\sound\Orb.ogg]])
LSM:Register("sound", "|cFFAEEA94C 出出出|r", [[Interface\Addons\WYJJDB\Media\sound\Out.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 重叠|r", [[Interface\Addons\WYJJDB\Media\sound\Overlap.ogg]])
LSM:Register("sound", "|cFFAEEA94P 砰砰|r", [[Interface\Addons\WYJJDB\Media\sound\Pop.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 药水|r", [[Interface\Addons\WYJJDB\Media\sound\Pots.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 准备拉人|r", [[Interface\Addons\WYJJDB\Media\sound\Pull.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 紫色|r", [[Interface\Addons\WYJJDB\Media\sound\Purple.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 准备推人|r", [[Interface\Addons\WYJJDB\Media\sound\Push.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 远程|r", [[Interface\Addons\WYJJDB\Media\sound\Range.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 准备就绪|r", [[Interface\Addons\WYJJDB\Media\sound\Ready.ogg]])
LSM:Register("sound", "|cFFAEEA94H 红色|r", [[Interface\Addons\WYJJDB\Media\sound\Red.ogg]])
LSM:Register("sound", "|cFFAEEA94F 反射|r", [[Interface\Addons\WYJJDB\Media\sound\Reflect.ogg]])
LSM:Register("sound", "|cFFAEEA94S 刷新|r", [[Interface\Addons\WYJJDB\Media\sound\Refresh.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 右边|r", [[Interface\Addons\WYJJDB\Media\sound\Right.ogg]])
LSM:Register("sound", "|cFFAEEA94Y 圆环|r", [[Interface\Addons\WYJJDB\Media\sound\Ring.ogg]])
LSM:Register("sound", "|cFFAEEA94D 定身|r", [[Interface\Addons\WYJJDB\Media\sound\Root.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 种子|r", [[Interface\Addons\WYJJDB\Media\sound\Seed.ogg]])
LSM:Register("sound", "|cFFAEEA94G 个人CD|r", [[Interface\Addons\WYJJDB\Media\sound\Selfcd.ogg]])
LSM:Register("sound", "|cFFAEEA94H 护盾|r", [[Interface\Addons\WYJJDB\Media\sound\Shield.ogg]])
LSM:Register("sound", "|cFFAEEA94B 帮忙吸收|r", [[Interface\Addons\WYJJDB\Media\sound\Soak.ogg]])
LSM:Register("sound", "|cFFAEEA94M 马上马上|r", [[Interface\Addons\WYJJDB\Media\sound\Soon.ogg]])
LSM:Register("sound", "|cFFAEEA94F 孵化|r", [[Interface\Addons\WYJJDB\Media\sound\Spawn.ogg]])
LSM:Register("sound", "|cFFAEEA94J 进攻驱散|r", [[Interface\Addons\WYJJDB\Media\sound\Spellsteal.ogg]])
LSM:Register("sound", "|cFFAEEA94F 分裂|r", [[Interface\Addons\WYJJDB\Media\sound\Split.ogg]])
LSM:Register("sound", "|cFFAEEA94F 分散|r", [[Interface\Addons\WYJJDB\Media\sound\Spread.ogg]])
LSM:Register("sound", "|cFFAEEA94D 叠层|r", [[Interface\Addons\WYJJDB\Media\sound\Stack.ogg]])
LSM:Register("sound", "|cFFAEEA94B 保持|r", [[Interface\Addons\WYJJDB\Media\sound\Stay.ogg]])
LSM:Register("sound", "|cFFAEEA94T 停止|r", [[Interface\Addons\WYJJDB\Media\sound\Stop.ogg]])
LSM:Register("sound", "|cFFAEEA94T 停止施法|r", [[Interface\Addons\WYJJDB\Media\sound\Stopcast.ogg]])
LSM:Register("sound", "|cFFAEEA94J 交换|r", [[Interface\Addons\WYJJDB\Media\sound\Swap.ogg]])
LSM:Register("sound", "|cFFAEEA94M 目标转换|r", [[Interface\Addons\WYJJDB\Media\sound\Switch.ogg]])
LSM:Register("sound", "|cFFAEEA94M 目标是你|r", [[Interface\Addons\WYJJDB\Media\sound\Targeted.ogg]])
LSM:Register("sound", "|cFFAEEA94C 嘲讽|r", [[Interface\Addons\WYJJDB\Media\sound\Taunt.ogg]])
LSM:Register("sound", "|cFFAEEA94T 图腾|r", [[Interface\Addons\WYJJDB\Media\sound\Totem.ogg]])
LSM:Register("sound", "|cFFAEEA94J 阶段转换|r", [[Interface\Addons\WYJJDB\Media\sound\Transition.ogg]])
LSM:Register("sound", "|cFFAEEA94X 陷阱|r", [[Interface\Addons\WYJJDB\Media\sound\Trap.ogg]])
LSM:Register("sound", "|cFFAEEA94Z 转身|r", [[Interface\Addons\WYJJDB\Media\sound\Turn.ogg]])
LSM:Register("sound", "|cFFAEEA94S 使用|r", [[Interface\Addons\WYJJDB\Media\sound\Use.ogg]])
LSM:Register("sound", "|cFFAEEA94Q 齐射|r", [[Interface\Addons\WYJJDB\Media\sound\Volley.ogg]])
LSM:Register("sound", "|cFFAEEA94B 波浪|r", [[Interface\Addons\WYJJDB\Media\sound\Wave.ogg]])
LSM:Register("sound", "|cFFAEEA94F 风|r", [[Interface\Addons\WYJJDB\Media\sound\Winds.ogg]])
LSM:Register("sound", "|cFFAEEA94H 黄色|r", [[Interface\Addons\WYJJDB\Media\sound\Yellow.ogg]])
LSM:Register("sound", "|cFFAEEA94Q 区域|r", [[Interface\Addons\WYJJDB\Media\sound\Zone.ogg]])
LSM:Register("sound", "|cFFAEEA94G 该补控了|r", [[Interface\Addons\WYJJDB\Media\sound\RefillCC.ogg]])
LSM:Register("sound", "|cFFAEEA94J 焦点打断|r", [[Interface\Addons\WYJJDB\Media\sound\Focus Interrupt.ogg]])
LSM:Register("sound", "|cFFAEEA94S 双点|r", [[Interface\Addons\WYJJDB\Media\sound\DoubleCasts.ogg]])
--CDS
LSM:Register("sound", "|cFFAEEA99Z 罩子|r |T237510:16|t", [[Interface\Addons\WYJJDB\Media\sound\AMZ.ogg]])
LSM:Register("sound", "|cFFAEEA99T 天使|r |T612969:16|t", [[Interface\Addons\WYJJDB\Media\sound\Angel.ogg]])
LSM:Register("sound", "|cFFAEEA99S 升腾|r |T135791:16|t", [[Interface\Addons\WYJJDB\Media\sound\Ascendance.ogg]])
LSM:Register("sound", "|cFFAEEA99Q 秋|r |T3636843:16|t", [[Interface\Addons\WYJJDB\Media\sound\Autumn.ogg]])
LSM:Register("sound", "|cFFAEEA99S 树皮|r |T572025:16|t", [[Interface\Addons\WYJJDB\Media\sound\Bark.ogg]])
LSM:Register("sound", "|cFFAEEA99P 屏障|r |T253400:16|t", [[Interface\Addons\WYJJDB\Media\sound\Barrier.ogg]])
LSM:Register("sound", "|cFFAEEA99C 赤精|r |T877514:16|t", [[Interface\Addons\WYJJDB\Media\sound\Chi-ji.ogg]])
LSM:Register("sound", "|cFFAEEA99J 茧|r |T627485:16|t", [[Interface\Addons\WYJJDB\Media\sound\Cocoon.ogg]])
LSM:Register("sound", "|cFFAEEA99H 黑暗|r |T1305154:16|t", [[Interface\Addons\WYJJDB\Media\sound\Darkness.ogg]])
LSM:Register("sound", "|cFFAEEA99G 光环掌握|r |T135893:16|t", [[Interface\Addons\WYJJDB\Media\sound\Devo.ogg]])
LSM:Register("sound", "|cFFAEEA99A 矮人|r |T136225:16|t", [[Interface\Addons\WYJJDB\Media\sound\Dwarf.ogg]])
LSM:Register("sound", "|cFFAEEA99Z 自由|r |T135968:16|t", [[Interface\Addons\WYJJDB\Media\sound\Freedom.ogg]])
LSM:Register("sound", "|cFFAEEA99Z 治疗之潮|r |T538569:16|t", [[Interface\Addons\WYJJDB\Media\sound\Healing Tide.ogg]])
LSM:Register("sound", "|cFFAEEA99Z 赞美诗|r |T237540:16|t", [[Interface\Addons\WYJJDB\Media\sound\Hymn.ogg]])
LSM:Register("sound", "|cFFAEEA99H 化身|r |T236157:16|t", [[Interface\Addons\WYJJDB\Media\sound\Incarn.ogg]])
LSM:Register("sound", "|cFFAEEA99J 激活|r |T136048:16|t", [[Interface\Addons\WYJJDB\Media\sound\Innervate.ogg]])
LSM:Register("sound", "|cFFAEEA99S 圣疗|r |T135928:16|t", [[Interface\Addons\WYJJDB\Media\sound\Lay.ogg]])
LSM:Register("sound", "|cFFAEEA99Y 影遁|r |T132089:16|t", [[Interface\Addons\WYJJDB\Media\sound\Meld.ogg]])
LSM:Register("sound", "|cFFAEEA99W 误导|r |T132180:16|t", [[Interface\Addons\WYJJDB\Media\sound\Misdirect.ogg]])
LSM:Register("sound", "|cFFAEEA99B 悖论|r |T5199645:16|t", [[Interface\Addons\WYJJDB\Media\sound\Paradox.ogg]])
LSM:Register("sound", "|cFFAEEA99G 灌注|r |T135939:16|t", [[Interface\Addons\WYJJDB\Media\sound\PI.ogg]])
LSM:Register("sound", "|cFFAEEA99B 保护|r |T135964:16|t", [[Interface\Addons\WYJJDB\Media\sound\Protection.ogg]])
LSM:Register("sound", "|cFFAEEA99Y 压制|r |T135936:16|t", [[Interface\Addons\WYJJDB\Media\sound\PS.ogg]])
LSM:Register("sound", "|cFFAEEA99J 集结呐喊|r |T132351:16|t", [[Interface\Addons\WYJJDB\Media\sound\Rally.ogg]])
LSM:Register("sound", "|cFFAEEA99Y 营救|r |T4622460:16|t", [[Interface\Addons\WYJJDB\Media\sound\Rescue.ogg]])
LSM:Register("sound", "|cFFAEEA99H 还魂|r |T1020466:16|t", [[Interface\Addons\WYJJDB\Media\sound\Revival.ogg]])
LSM:Register("sound", "|cFFAEEA99H 回溯|r |T4622474:16|t", [[Interface\Addons\WYJJDB\Media\sound\Rewind.ogg]])
LSM:Register("sound", "|cFFAEEA99N 怒吼|r |T463283:16|t", [[Interface\Addons\WYJJDB\Media\sound\Roar.ogg]])
LSM:Register("sound", "|cFFAEEA99X 牺牲|r |T135966:16|t", [[Interface\Addons\WYJJDB\Media\sound\Sac.ogg]])
LSM:Register("sound", "|cFFAEEA99L 灵魂连接|r |T237586:16|t", [[Interface\Addons\WYJJDB\Media\sound\SLT.ogg]])
LSM:Register("sound", "|cFFAEEA99W 帷幕|r |T635350:16|t", [[Interface\Addons\WYJJDB\Media\sound\Shroud.ogg]])
LSM:Register("sound", "|cFFAEEA99P 破咒|r |T135880:16|t", [[Interface\Addons\WYJJDB\Media\sound\Spellwarding.ogg]])
LSM:Register("sound", "|cFFAEEA99C 春|r |T3636844:16|t", [[Interface\Addons\WYJJDB\Media\sound\Spring.ogg]])
LSM:Register("sound", "|cFFAEEA99L 灵魂石|r |T136210:16|t", [[Interface\Addons\WYJJDB\Media\sound\SS.ogg]])
LSM:Register("sound", "|cFFAEEA99X 夏|r |T3636845:16|t", [[Interface\Addons\WYJJDB\Media\sound\Summer.ogg]])
LSM:Register("sound", "|cFFAEEA99S 时间螺旋|r |T4622479:16|t", [[Interface\Addons\WYJJDB\Media\sound\Time Spiral.ogg]])
LSM:Register("sound", "|cFFAEEA99S 时间膨胀|r |T4622478:16|t", [[Interface\Addons\WYJJDB\Media\sound\TD.ogg]])
LSM:Register("sound", "|cFFAEEA99X 驯如猛虎|r |T651727:16|t", [[Interface\Addons\WYJJDB\Media\sound\Tiger's Lust.ogg]])
LSM:Register("sound", "|cFFAEEA99N 宁静|r |T136107:16|t", [[Interface\Addons\WYJJDB\Media\sound\Tranq.ogg]])
LSM:Register("sound", "|cFFAEEA99J 嫁祸|r |T236283:16|t", [[Interface\Addons\WYJJDB\Media\sound\Tricks.ogg]])
LSM:Register("sound", "|cFFAEEA99K 狂风图腾|r |T538576:16|t", [[Interface\Addons\WYJJDB\Media\sound\Wind Rush.ogg]])
LSM:Register("sound", "|cFFAEEA99D 冬|r |T3636846:16|t", [[Interface\Addons\WYJJDB\Media\sound\Winter.ogg]])

LSM:Register("sound", "|cFFAEEA99Q 群盾|r |T1723997:16|t", [[Interface\Addons\WYJJDB\Media\sound\Mass Barrier.ogg]])
LSM:Register("sound", "|cFFAEEA99Z 战复图腾|r |T136080:16|t", [[Interface\Addons\WYJJDB\Media\sound\APT.ogg]])
LSM:Register("sound", "|cFFAEEA99Y 援护|r |T132365:16|t", [[Interface\Addons\WYJJDB\Media\sound\Intervene.ogg]])
LSM:Register("sound", "|cFFAEEA99D 盾反|r |T132361:16|t", [[Interface\Addons\WYJJDB\Media\sound\Spell Reflect.ogg]])
LSM:Register("sound", "|cFFAEEA99J 加速|r", [[Interface\Addons\WYJJDB\Media\sound\Fast.ogg]])
LSM:Register("sound", "|cFFAEEA99W 微风|r |T4630449:16|t", [[Interface\Addons\WYJJDB\Media\sound\Zephyr.ogg]])
LSM:Register("sound", "|cFFAEEA99H 红驱|r |T4630446:16|t", [[Interface\Addons\WYJJDB\Media\sound\Cauterizing Flame.ogg]])
LSM:Register("sound", "|cFFAEEA99G 龟壳|r |T132199:16|t", [[Interface\Addons\WYJJDB\Media\sound\Turtle.ogg]])
LSM:Register("sound", "|cFFAEEA99J 假死|r |T132293:16|t", [[Interface\Addons\WYJJDB\Media\sound\Feign Death.ogg]])
LSM:Register("sound", "|cFFAEEA99L 绿罩|r |T136120:16|t", [[Interface\Addons\WYJJDB\Media\sound\Anti-Magic Shell.ogg]])
LSM:Register("sound", "|cFFAEEA99W 无敌|r |T524354:16|t", [[Interface\Addons\WYJJDB\Media\sound\Divine Shield.ogg]])
LSM:Register("sound", "|cFFAEEA99X 消散|r |T237563:16|t", [[Interface\Addons\WYJJDB\Media\sound\Dispersion.ogg]])
LSM:Register("sound", "|cFFAEEA99D 斗篷|r |T136177:16|t", [[Interface\Addons\WYJJDB\Media\sound\Cloak.ogg]])
LSM:Register("sound", "|cFFAEEA99Q 强隐|r |T575584:16|t", [[Interface\Addons\WYJJDB\Media\sound\Invisibility.ogg]])
LSM:Register("sound", "|cFFAEEA99C 春哥|r |T252268:16|t", [[Interface\Addons\WYJJDB\Media\sound\SpringBro.ogg]])
LSM:Register("sound", "|cFFAEEA99B 冰箱|r |T135841:16|t", [[Interface\Addons\WYJJDB\Media\sound\Ice Block.ogg]])
LSM:Register("sound", "|cFFAEEA99X 虚空行走|r |T463284:16|t", [[Interface\Addons\WYJJDB\Media\sound\Netherwalk.ogg]])
LSM:Register("sound", "|cFFAEEA99Y 压迫怒吼|r |T4622466:16|t", [[Interface\Addons\WYJJDB\Media\sound\Oppressing Roar.ogg]])
LSM:Register("sound", "|cFFAEEA99Z 战栗图腾|r |T136108:16|t", [[Interface\Addons\WYJJDB\Media\sound\Tremor Totem.ogg]])
LSM:Register("sound", "|cFFAEEA99Q 清毒图腾|r |T136070:16|t", [[Interface\Addons\WYJJDB\Media\sound\PCT.ogg]])

--CCs
LSM:Register("sound", "|cFFAEEA95D 电能图腾|r |T136013:16|t", [[Interface\Addons\WYJJDB\Media\sound\Capacitor Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95X 陷地图腾|r |T136100:16|t", [[Interface\Addons\WYJJDB\Media\sound\Earthgrab Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95D 地缚图腾|r |T136102:16|t", [[Interface\Addons\WYJJDB\Media\sound\Earthbind Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95L 雷霆风暴|r |T237589:16|t", [[Interface\Addons\WYJJDB\Media\sound\Thunderstorm.ogg]])
LSM:Register("sound", "|cFFAEEA95X 心灵尖啸|r |T136184:16|t", [[Interface\Addons\WYJJDB\Media\sound\Psychic Scream.ogg]])
LSM:Register("sound", "|cFFAEEA95Z 震荡波|r |T236312:16|t", [[Interface\Addons\WYJJDB\Media\sound\Shockwave.ogg]])
LSM:Register("sound", "|cFFAEEA95S 扫堂腿|r |T642414:16|t", [[Interface\Addons\WYJJDB\Media\sound\Leg Sweep.ogg]])
LSM:Register("sound", "|cFFAEEA95A 暗影之怒|r |T607865:16|t", [[Interface\Addons\WYJJDB\Media\sound\Shadowfury.ogg]])
LSM:Register("sound", "|cFFAEEA95M 盲目之光|r |T571553:16|t", [[Interface\Addons\WYJJDB\Media\sound\Blinding Light.ogg]])
LSM:Register("sound", "|cFFAEEA95W 乌索尔旋风|r |T571588:16|t", [[Interface\Addons\WYJJDB\Media\sound\Ursol's Vortex.ogg]])
LSM:Register("sound", "|cFFAEEA95R 日光术|r |T252188:16|t", [[Interface\Addons\WYJJDB\Media\sound\Solar Beam.ogg]])
LSM:Register("sound", "|cFFAEEA95H 混乱新星|r |T135795:16|t", [[Interface\Addons\WYJJDB\Media\sound\Chaos Nova.ogg]])
LSM:Register("sound", "|cFFAEEA95B 悲苦咒符|r |T1418287:16|t", [[Interface\Addons\WYJJDB\Media\sound\Sigil of Misery.ogg]])
LSM:Register("sound", "|cFFAEEA95C 沉默咒符|r |T1418288:16|t", [[Interface\Addons\WYJJDB\Media\sound\Sigil of Silence.ogg]])
LSM:Register("sound", "|cFFAEEA95P 破胆怒吼|r |T132154:16|t", [[Interface\Addons\WYJJDB\Media\sound\Intimidating Shout.ogg]])
LSM:Register("sound", "|cFFAEEA95Z 战争践踏|r |T132368:16|t", [[Interface\Addons\WYJJDB\Media\sound\War Stomp.ogg]])
LSM:Register("sound", "|cFFAEEA95P 平心之环|r |T839107:16|t", [[Interface\Addons\WYJJDB\Media\sound\Ring of Peace.ogg]])
LSM:Register("sound", "|cFFAEEA95T 台风|r |T236170:16|t", [[Interface\Addons\WYJJDB\Media\sound\Typhoon.ogg]])
LSM:Register("sound", "|cFFAEEA95F 飞翼打击|r |T4622488:16|t", [[Interface\Addons\WYJJDB\Media\sound\Wing Buffet.ogg]])
LSM:Register("sound", "|cFFAEEA95S 扫尾|r |T4622486:16|t", [[Interface\Addons\WYJJDB\Media\sound\Tail Sweep.ogg]])
LSM:Register("sound", "|cFFAEEA95A 奥术洪流|r |T136222:16|t", [[Interface\Addons\WYJJDB\Media\sound\Arcane Torrent.ogg]])
LSM:Register("sound", "|cFFAEEA95D 夺魂咆哮|r |T132121:16|t", [[Interface\Addons\WYJJDB\Media\sound\Incapacitating Roar.ogg]])
LSM:Register("sound", "|cFFAEEA95C 超级新星|r |T1033912:16|t", [[Interface\Addons\WYJJDB\Media\sound\Supernova.ogg]])
LSM:Register("sound", "|cFFAEEA95C 冲击波|r |T135903:16|t", [[Interface\Addons\WYJJDB\Media\sound\Blast Wave.ogg]])
LSM:Register("sound", "|cFFAEEA95S 死亡之握|r |T237532:16|t", [[Interface\Addons\WYJJDB\Media\sound\Death Grip.ogg]])
LSM:Register("sound", "|cFFAEEA95N 内爆陷阱|r |T1044088:16|t", [[Interface\Addons\WYJJDB\Media\sound\Implosive Trap.ogg]])
LSM:Register("sound", "|cFFAEEA95Z 致盲冰雨|r |T135836:16|t", [[Interface\Addons\WYJJDB\Media\sound\Blinding Sleet.ogg]])
LSM:Register("sound", "|cFFAEEA95S 束缚射击|r |T462650:16|t", [[Interface\Addons\WYJJDB\Media\sound\Binding Shot.ogg]])
LSM:Register("sound", "|cFFAEEA95W 瓦解怒吼|r |T132091:16|t", [[Interface\Addons\WYJJDB\Media\sound\Disrupting Shout.ogg]])
-- -----
--   STATUSBAR
-- -----
