local LSM = LibStub("LibSharedMedia-3.0")
if not LSM then
	return
end

local addonName = "WYJJDB"
local mPath = [[Interface\AddOns\]] .. addonName .. [[\Media\]]

local mediaData = {
	["sound"] = {
		{
			groupName = "Group c1",
			color = "AEEA90",
			list = {
				{ "我就知道你能做到", "EQAchieve.ogg" },
				{ "嘿，你还好吗", "EQDead.ogg" },
				{ "看看获得了什么宝贝", "EQDrop.ogg" },
				{ "希望是个深思熟虑的选择", "EQEscape.ogg" },
				{ "进入战斗", "EQInCombat.ogg" },
				{ "你要加入我们吗", "EQInvite.ogg" },
				{ "离开战斗", "EQLCombat.ogg" },
				{ "订单已添加", "EQListAdd.ogg" },
				{ "移除成功", "EQListRemove.ogg" },
				{ "你有新邮件", "EQMail.ogg" },
				{ "你要打什么位置", "EQPosition.ogg" },
				{ "倒计时开始", "EQPull.ogg" },
				{ "准备就绪", "EQReady.ogg" },
				{ "复活吧，我的勇士", "EQResurrection.ogg" },
				{ "运气真不错", "EQUplevel.ogg" },
				{ "欢迎你的加入", "EQWelcome.ogg" },
				{ "这宝贝是你的了", "EQWin.ogg" },
			},
		},
		{
			groupName = "Group c2",
			color = "AEEA94",
			list = {
				{ "--- 通用/互动 ---", "Empty.ogg" },
				{ "1", "1.ogg" },
				{ "2", "2.ogg" },
				{ "3", "3.ogg" },
				{ "4", "4.ogg" },
				{ "5", "5.ogg" },
				{ "6", "6.ogg" },
				{ "7", "7.ogg" },
				{ "8", "8.ogg" },
				{ "9", "9.ogg" },
				{ "10", "10.ogg" },
				{ "D 第一", "First.ogg" },
				{ "D 第二", "Second.ogg" },
				{ "D 第三", "Third.ogg" },
				{ "D 第四", "Fourth.ogg" },
				{ "D 第五", "Fifth.ogg" },
				{ "X 吸收盾", "Absorb.ogg" },
				{ "Z 准备大怪", "Add.ogg" },
				{ "X 小怪快打", "Adds.ogg" },
				{ "Z 注意词缀", "Affix.ogg" },
				{ "A AoE", "AoE.ogg" },
				{ "Y 远离小怪", "AwayAdds.ogg" },
				{ "Y 远离Boss", "AwayBoss.ogg" },
				{ "Y 远离人群", "AwayCrowed.ogg" },
				{ "X 协助", "Assist.ogg" },
				{ "G 规避", "Avoid.ogg" },
				{ "H 后退", "Back.ogg" },
				{ "B 备选", "Backup.ogg" },
				{ "Y 引导位置", "Bait.ogg" },
				{ "Z 注意射线", "Beam.ogg" },
				{ "T 坦克承伤", "Bite.ogg" },
				{ "S 嗜血", "Bloodlust.ogg" },
				{ "L 蓝色", "Blue.ogg" },
				{ "Z 炸弹", "Bombs.ogg" },
				{ "A Boss", "Boss.ogg" },
				{ "D 打破", "Break.ogg" },
				{ "A Buff", "Buff.ogg" },
				{ "K 快交控制", "CC.ogg" },
				{ "A CD", "CD.ogg" },
				{ "Z 中间", "Center.ogg" },
				{ "S 锁链", "Chain.ogg" },
				{ "C 冲锋", "Charge.ogg" },
				{ "J 检查", "Check.ogg" },
				{ "Q 清除", "Clear.ogg" },
				{ "S 收集", "Collect.ogg" },
				{ "Z 诅咒", "Curse.ogg" },
				{ "D 躲地板", "Dance.ogg" },
				{ "F 防御", "Defensive.ogg" },
				{ "A Debuff", "Debuff.ogg" },
				{ "Q 驱散", "Dispell.ogg" },
				{ "Z 注意躲避", "Dodge.ogg" },
				{ "B 不要", "Dont.ogg" },
				{ "T 停止移动", "Dont Move.ogg" },
				{ "A Dot", "Dot.ogg" },
				{ "F 放水", "Drop.ogg" },
				{ "J 进入", "Enter.ogg" },
				{ "S 哨兵", "Escort.ogg" },
				{ "T 退出", "Exit.ogg" },
				{ "W 外部", "External.ogg" },
				{ "Z 注意脚下", "Feet.ogg" },
				{ "M 目标锁定", "Fixate.ogg" },
				{ "J 焦点", "Focus.ogg" },
				{ "Z 注意头前", "Front.ogg" },
				{ "K 开门", "Gate.ogg" },
				{ "S 收集", "Gather.ogg" },
				{ "L 绿色", "Green.ogg" },
				{ "Q 前进", "Go.ogg" },
				{ "Z 抓紧", "Grip.ogg" },
				{ "Z 治疗CD", "Healcd.ogg" },
				{ "D 躲避伤害", "Hide.ogg" },
				{ "N 能量过高", "High Energy.ogg" },
				{ "C 层数过高", "High Stacks.ogg" },
				{ "M 免疫", "Immunity.ogg" },
				{ "J 进进进", "In.ogg" },
				{ "D 打断施法", "Interrupt.ogg" },
				{ "J 阶段转换", "Intermission.ogg" },
				{ "Y 隐身", "Invisibility.ogg" },
				{ "T 跳", "Jump.ogg" },
				{ "K 快打断", "Kick.ogg" },
				{ "F 风筝", "Kite.ogg" },
				{ "J 击飞", "Knock.ogg" },
				{ "Z 最后", "Last.ogg" },
				{ "Z 左边", "Left.ogg" },
				{ "T 跳跃", "Leap.ogg" },
				{ "L 连线", "Line.ogg" },
				{ "L 链接", "Link.ogg" },
				{ "B 被连接", "Linked.ogg" },
				{ "K 卡视野", "LoS.ogg" },
				{ "H 宏", "Macro.ogg" },
				{ "J 近战", "Melee.ogg" },
				{ "D 地雷", "Mines.ogg" },
				{ "Y 移动", "Move.ogg" },
				{ "X 下一个", "Next.ogg" },
				{ "J 集中攻击", "Nuke.ogg" },
				{ "C 橙色", "Orange.ogg" },
				{ "B 宝珠", "Orb.ogg" },
				{ "C 出出出", "Out.ogg" },
				{ "Z 重叠", "Overlap.ogg" },
				{ "P 砰砰", "Pop.ogg" },
				{ "Y 药水", "Pots.ogg" },
				{ "Z 准备拉人", "Pull.ogg" },
				{ "Z 紫色", "Purple.ogg" },
				{ "Z 准备推人", "Push.ogg" },
				{ "Y 远程", "Range.ogg" },
				{ "Z 准备就绪", "Ready.ogg" },
				{ "H 红色", "Red.ogg" },
				{ "F 反射", "Reflect.ogg" },
				{ "S 刷新", "Refresh.ogg" },
				{ "Y 右边", "Right.ogg" },
				{ "Y 圆环", "Ring.ogg" },
				{ "D 定身", "Root.ogg" },
				{ "K 快跑开", "RunAway.ogg" },
				{ "Z 种子", "Seed.ogg" },
				{ "G 个人CD", "Selfcd.ogg" },
				{ "H 护盾", "Shield.ogg" },
				{ "B 帮忙吸收", "Soak.ogg" },
				{ "M 马上马上", "Soon.ogg" },
				{ "F 孵化", "Spawn.ogg" },
				{ "J 进攻驱散", "Spellsteal.ogg" },
				{ "F 分裂", "Split.ogg" },
				{ "F 分散", "Spread.ogg" },
				{ "D 叠层", "Stack.ogg" },
				{ "B 保持", "Stay.ogg" },
				{ "T 停止", "Stop.ogg" },
				{ "T 停止施法", "Stopcast.ogg" },
				{ "J 交换", "Swap.ogg" },
				{ "M 目标转换", "Switch.ogg" },
				{ "M 目标是你", "Targeted.ogg" },
				{ "C 嘲讽", "Taunt.ogg" },
				{ "T 图腾", "Totem.ogg" },
				{ "J 阶段转换", "Transition.ogg" },
				{ "X 陷阱", "Trap.ogg" },
				{ "Z 转身", "Turn.ogg" },
				{ "S 使用", "Use.ogg" },
				{ "Q 齐射", "Volley.ogg" },
				{ "B 波浪", "Wave.ogg" },
				{ "D 躲风", "Winds.ogg" },
				{ "H 黄色", "Yellow.ogg" },
				{ "Q 区域", "Zone.ogg" },
				{ "G 该补控了", "RefillCC.ogg" },
				{ "J 焦点打断", "Focus Interrupt.ogg" },
				{ "S 双点", "DoubleCasts.ogg" },
				{ "T 停", "Stop.ogg" },
				{ "L 流血", "Bleed.ogg" },
				{ "L 笼子", "Cage.ogg" },
				{ "Y 硬币", "Coin.ogg" },
				{ "J 交叉", "Cross.ogg" },
				{ "J 疾病", "Disease.ogg" },
				{ "A 嘎", "Duck.ogg" },
				{ "F 法夜", "Faye.ogg" },
				{ "M 魔法", "Magic.ogg" },
				{ "Z 主目标", "Main.ogg" },
				{ "W 物理", "Physical.ogg" },
				{ "D 毒药", "Poison.ogg" },
				{ "S 哨兵", "Sentry.ogg" },
				{ "B 边场", "Side.ogg" },
				{ "Y 鱼串", "Stick.ogg" },
				{ "R 扔扔扔", "Throw.ogg" },
				{ "X 迅如猛虎", "Tiger's Lust.ogg" },
				{ "W 乌索尔旋风", "Ursol's Vortex.ogg" },
				{ "B Biu", "biubiubiu.ogg" },
			},
		},
		{
			groupName = "Group c3",
			color = "AEEA95",
			list = {
				{ "--- 群体控制 ---", "Empty.ogg" },
				{ "D 电能图腾 |T136013:16|t", "Capacitor Totem.ogg" },
				{ "X 陷地图腾 |T136100:16|t", "Earthgrab Totem.ogg" },
				{ "D 地缚图腾 |T136102:16|t", "Earthbind Totem.ogg" },
				{ "L 雷霆风暴 |T237589:16|t", "Thunderstorm.ogg" },
				{ "X 心灵尖啸 |T136184:16|t", "Psychic Scream.ogg" },
				{ "Z 震荡波 |T236312:16|t", "Shockwave.ogg" },
				{ "S 扫堂腿 |T642414:16|t", "Leg Sweep.ogg" },
				{ "A 暗影之怒 |T607865:16|t", "Shadowfury.ogg" },
				{ "M 盲目之光 |T571553:16|t", "Blinding Light.ogg" },
				{ "W 乌索尔旋风 |T571588:16|t", "Ursol's Vortex.ogg" },
				{ "R 日光术 |T252188:16|t", "Solar Beam.ogg" },
				{ "H 混乱新星 |T135795:16|t", "Chaos Nova.ogg" },
				{ "B 悲苦咒符 |T1418287:16|t", "Sigil of Misery.ogg" },
				{ "C 沉默咒符 |T1418288:16|t", "Sigil of Silence.ogg" },
				{ "P 破胆怒吼 |T132154:16|t", "Intimidating Shout.ogg" },
				{ "Z 战争践踏 |T132368:16|t", "War Stomp.ogg" },
				{ "P 平心之环 |T839107:16|t", "Ring of Peace.ogg" },
				{ "T 台风 |T236170:16|t", "Typhoon.ogg" },
				{ "F 飞翼打击 |T4622488:16|t", "Wing Buffet.ogg" },
				{ "S 扫尾 |T4622486:16|t", "Tail Sweep.ogg" },
				{ "A 奥术洪流 |T136222:16|t", "Arcane Torrent.ogg" },
				{ "D 夺魂咆哮 |T132121:16|t", "Incapacitating Roar.ogg" },
				{ "C 超级新星 |T1033912:16|t", "Supernova.ogg" },
				{ "C 冲击波 |T135903:16|t", "Blast Wave.ogg" },
				{ "S 死亡之握 |T237532:16|t", "Death Grip.ogg" },
				{ "N 内爆陷阱 |T1044088:16|t", "Implosive Trap.ogg" },
				{ "Z 致盲冰雨 |T135836:16|t", "Blinding Sleet.ogg" },
				{ "S 束缚射击 |T462650:16|t", "Binding Shot.ogg" },
				{ "W 瓦解怒吼 |T132091:16|t", "Disrupting Shout.ogg" },
			},
		},
		{
			groupName = "Group c4",
			color = "AEEA96",
			list = {
				{ "--- 个人技能/外部光环 ---", "Empty.ogg" },
				{ "Z 罩子 |T237510:16|t", "AMZ.ogg" },
				{ "T 天使 |T612969:16|t", "Angel.ogg" },
				{ "S 升腾 |T135791:16|t", "Ascendance.ogg" },
				{ "Q 秋 |T3636843:16|t", "Autumn.ogg" },
				{ "S 树皮 |T572025:16|t", "Bark.ogg" },
				{ "P 屏障 |T253400:16|t", "Barrier.ogg" },
				{ "C 赤精 |T877514:16|t", "Chi-ji.ogg" },
				{ "J 茧 |T627485:16|t", "Cocoon.ogg" },
				{ "H 黑暗 |T1305154:16|t", "Darkness.ogg" },
				{ "G 光环掌握 |T135893:16|t", "Devo.ogg" },
				{ "A 矮人 |T136225:16|t", "Dwarf.ogg" },
				{ "Z 自由 |T135968:16|t", "Freedom.ogg" },
				{ "Z 治疗之潮 |T538569:16|t", "Healing Tide.ogg" },
				{ "Z 赞美诗 |T237540:16|t", "Hymn.ogg" },
				{ "H 化身 |T236157:16|t", "Incarn.ogg" },
				{ "J 激活 |T136048:16|t", "Innervate.ogg" },
				{ "S 圣疗 |T135928:16|t", "Lay.ogg" },
				{ "Y 影遁 |T132089:16|t", "Meld.ogg" },
				{ "W 误导 |T132180:16|t", "Misdirect.ogg" },
				{ "B 悖论 |T5199645:16|t", "Paradox.ogg" },
				{ "G 灌注 |T135939:16|t", "PI.ogg" },
				{ "B 保护 |T135964:16|t", "Protection.ogg" },
				{ "Y 压制 |T135936:16|t", "PS.ogg" },
				{ "J 集结呐喊 |T132351:16|t", "Rally.ogg" },
				{ "Y 营救 |T4622460:16|t", "Rescue.ogg" },
				{ "H 还魂 |T1020466:16|t", "Revival.ogg" },
				{ "H 回溯 |T4622474:16|t", "Rewind.ogg" },
				{ "N 怒吼 |T463283:16|t", "Roar.ogg" },
				{ "X 牺牲 |T135966:16|t", "Sac.ogg" },
				{ "L 灵魂连接 |T237586:16|t", "SLT.ogg" },
				{ "W 帷幕 |T635350:16|t", "Shroud.ogg" },
				{ "P 破咒 |T135880:16|t", "Spellwarding.ogg" },
				{ "C 春 |T3636844:16|t", "Spring.ogg" },
				{ "L 灵魂石 |T136210:16|t", "SS.ogg" },
				{ "X 夏 |T3636845:16|t", "Summer.ogg" },
				{ "S 时间螺旋 |T4622479:16|t", "Time Spiral.ogg" },
				{ "S 时间膨胀 |T4622478:16|t", "TD.ogg" },
				{ "X 驯如猛虎 |T651727:16|t", "Tiger's Lust.ogg" },
				{ "N 宁静 |T136107:16|t", "Tranq.ogg" },
				{ "J 嫁祸 |T236283:16|t", "Tricks.ogg" },
				{ "K 狂风图腾 |T538576:16|t", "Wind Rush.ogg" },
				{ "D 冬 |T3636846:16|t", "Winter.ogg" },
				{ "Q 群盾 |T1723997:16|t", "Mass Barrier.ogg" },
				{ "Z 战复图腾 |T136080:16|t", "APT.ogg" },
				{ "Y 援护 |T132365:16|t", "Intervene.ogg" },
				{ "D 盾反 |T132361:16|t", "Spell Reflect.ogg" },
				{ "J 加速", "Fast.ogg" },
				{ "W 微风 |T4630449:16|t", "Zephyr.ogg" },
				{ "H 红驱 |T4630446:16|t", "Cauterizing Flame.ogg" },
				{ "G 龟壳 |T132199:16|t", "Turtle.ogg" },
				{ "J 假死 |T132293:16|t", "Feign Death.ogg" },
				{ "L 绿罩 |T136120:16|t", "Anti-Magic Shell.ogg" },
				{ "W 无敌 |T524354:16|t", "Divine Shield.ogg" },
				{ "X 消散 |T237563:16|t", "Dispersion.ogg" },
				{ "D 斗篷 |T136177:16|t", "Cloak.ogg" },
				{ "Q 强隐 |T575584:16|t", "Invisibility.ogg" },
				{ "C 春哥 |T252268:16|t", "SpringBro.ogg" },
				{ "B 冰箱 |T135841:16|t", "Ice Block.ogg" },
				{ "X 虚空行走 |T463284:16|t", "Netherwalk.ogg" },
				{ "Y 压迫怒吼 |T4622466:16|t", "Oppressing Roar.ogg" },
				{ "Z 战栗图腾 |T136108:16|t", "Tremor Totem.ogg" },
				{ "Q 清毒图腾 |T136070:16|t", "PCT.ogg" },
				{ "Q 切割", "SliceAndDice.ogg" },
				{ "G 割裂", "Rupture.ogg" },
				{ "B 变身", "Metamorphosis.ogg" },
				{ "S 圣印", "Seal.ogg" },
				{ "X 小猪", "Pig.ogg" },
				{ "J 解毒", "CureToxin.ogg" },
				{ "G 骨盾", "BoneShield.ogg" },
				{ "B 补盾", "ShieldRefresh.ogg" },
				{ "D 道标", "BeaconOfLight.ogg" },
				{ "T 特效触发", "Proc.ogg" },
				{ "D 钉刺", "Sting.ogg" },
				{ "S 饰品触发", "TrinketProc.ogg" },
				{ "D 凋零", "DeathAndDecay.ogg" },
				{ "T 吞病", "DevouringPlague.ogg" },
				{ "D 大狗熊", "BigBear.ogg" },
				{ "D 大龙", "BigDragon.ogg" },
				{ "A 奥术之魂", "ArcaneSoul.ogg" },
				{ "B 崩摧10层", "Crumbling10Stacks.ogg" },
				{ "Z 扎昆", "Zakuun.ogg" },
				{ "D 打单体", "SingleTar.ogg" },
				{ "D 打风暴", "StormTar.ogg" },
				{ "D 毒镰", "PoisonScythe.ogg" },
				{ "M 玛胖", "Mannoroth.ogg" },
				{ "K 考验10层", "Trial10Stacks.ogg" },
				{ "X 血兽降临", "BloodBeastIncoming.ogg" },
				{ "B 补地毯", "CarpetRefresh.ogg" },
				{ "G 过热高温", "ExtremeHot.ogg" },
				{ "J 静滞激活", "StasisActive.ogg" },
				{ "Y 预兆全开", "OmenAllOpen.ogg" },
				{ "Y 预兆减CD", "OmenCDR.ogg" },
				{ "Y 预兆加盾", "OmenShield.ogg" },
				{ "Y 预兆增疗", "OmenHeal.ogg" },
				{ "L 黎明两层", "Dawn2Stacks.ogg" },
				{ "Z 主母", "Mother.ogg" },
				{ "X 亵渎", "Profane.ogg" },
				{ "J 假死触发", "FeignDeathProc.ogg" },
				{ "X 小技能", "SmallCD.ogg" },
				{ "D 大技能", "BigCD.ogg" },
			},
		},
		{
			groupName = "Group c5",
			color = "AEEA97",
			list = {
				{ "--- 技能就緒 ---", "Empty.ogg" },
				{ "W 伟大", "r-Greatness.ogg" },
				{ "B 冰封就绪", "r-IBF.ogg" },
				{ "B 冰脉就绪", "r-IcyVeins.ogg" },
				{ "C 冲动就绪", "r-AdrenalineRush.ogg" },
				{ "R 刃舞就绪", "r-BladeDance.ogg" },
				{ "J 剑舞就绪", "r-BladeFlurry.ogg" },
				{ "Y 压制就绪", "r-Overpower.ogg" },
				{ "B 变身就绪", "r-Meta.ogg" },
				{ "S 嗜血就绪", "r-Bloodlust.ogg" },
				{ "T 土爹就绪", "r-EarthElemental.ogg" },
				{ "S 圣佑就绪", "r-DivineProtection.ogg" },
				{ "S 圣歌就绪", "r-Hymn.ogg" },
				{ "S 圣疗就绪", "r-LayOnHands.ogg" },
				{ "D 大军就绪", "r-Army.ogg" },
				{ "D 大风车就绪", "r-Bladestorm.ogg" },
				{ "T 天鬼就绪", "r-Gargoyle.ogg" },
				{ "T 天鬼飞走了", "GargoyleGone.ogg" },
				{ "A 奥强就绪", "r-ArcanePower.ogg" },
				{ "J 嫁祸就绪", "r-Tricks.ogg" },
				{ "N 宁静就绪", "r-Tranquility.ogg" },
				{ "Y 影舞就绪", "r-ShadowDance.ogg" },
				{ "J 急射就绪", "r-RapidFire.ogg" },
				{ "Z 掌握就绪", "r-Mastery.ogg" },
				{ "W 无敌就绪", "r-Bubble.ogg" },
				{ "A 暗影魔就绪", "r-Shadowfiend.ogg" },
				{ "S 杀戮就绪", "r-KillingSpree.ogg" },
				{ "S 死愿就绪", "r-DeathWish.ogg" },
				{ "F 法潮就绪", "r-ManaTide.ogg" },
				{ "J 激活就绪", "r-Innervate.ogg" },
				{ "G 灌注就绪", "r-PI.ogg" },
				{ "H 火爹就绪", "r-FireElemental.ogg" },
				{ "R 燃烧就绪", "r-Combustion.ogg" },
				{ "L 狼魂就绪", "r-FeralSpirit.ogg" },
				{ "S 神启就绪", "r-DivineIllumination.ogg" },
				{ "F 符文武器就绪", "r-ERW.ogg" },
				{ "H 红人就绪", "r-BestialWrath.ogg" },
				{ "C 翅膀就绪", "r-AvengingWrath.ogg" },
				{ "Z 赞美诗就绪", "r-DivineHymn.ogg" },
				{ "T 铜墙铁壁就绪", "r-UnbreakableArmor.ogg" },
				{ "L 鲁莽就绪", "r-Recklessness.ogg" },
				{ "W 万灵就绪", "r-Convoke.ogg" },
				{ "E 二号机就绪", "r-GrimoireFelguard.ogg" },
				{ "B 冰柱就绪", "r-PillarOfFrost.ogg" },
				{ "H 化身就绪", "r-Incarnation.ogg" },
				{ "S 升华就绪", "r-Ascendancy.ogg" },
				{ "S 升腾就绪", "r-Ascendance.ogg" },
				{ "X 协同就绪", "r-CoordinatedFire.ogg" },
				{ "Y 印记就绪", "r-Mark.ogg" },
				{ "J 君王就绪", "r-Kingsbane.ogg" },
				{ "D 地狱火就绪", "r-Infernal.ogg" },
				{ "Z 壮胆酒就绪", "r-FortifyingBrew.ogg" },
				{ "T 天启就绪", "r-Apocalypse.ogg" },
				{ "T 天神就绪", "r-Avatar.ogg" },
				{ "B 崩摧就绪", "r-Crumbling.ogg" },
				{ "H 幻能就绪", "r-ShiftingPower.ogg" },
				{ "Y 怨毒就绪", "r-Misery.ogg" },
				{ "M 明月就绪", "r-FullMoon.ogg" },
				{ "A 暗刃就绪", "r-ShadowBlades.ogg" },
				{ "B 暴君就绪", "r-Tyrant.ogg" },
				{ "Z 朱鹤就绪", "r-ChiJi.ogg" },
				{ "H 横扫就绪", "r-SweepingStrikes.ogg" },
				{ "S 死印就绪", "r-Deathmark.ogg" },
				{ "H 毁灭之风就绪", "r-DoomWinds.ogg" },
				{ "X 消失就绪", "r-Vanish.ogg" },
				{ "Y 涌动就绪", "r-Surge.ogg" },
				{ "S 深呼吸就绪", "r-DeepBreath.ogg" },
				{ "M 灭战就绪", "r-Warbreaker.ogg" },
				{ "H 灰烬就绪", "r-AshenHallow.ogg" },
				{ "L 灵魂腐化就绪", "r-SoulRot.ogg" },
				{ "B 爆发就绪", "r-Outbreak.ogg" },
				{ "K 狂暴就绪", "r-Berserk.ogg" },
				{ "K 狂龙就绪", "r-Dragonrage.ogg" },
				{ "X 玄牛就绪", "r-Niuzao.ogg" },
				{ "B 白虎就绪", "r-Xuen.ogg" },
				{ "B 百发就绪", "r-Trueshot.ogg" },
				{ "S 神器就绪", "r-Artifact.ogg" },
				{ "T 突变就绪", "r-Transformation.ogg" },
				{ "T 突袭就绪", "r-Assault.ogg" },
				{ "J 精兵就绪", "r-Vanguard.ogg" },
				{ "Z 转转锤就绪", "r-SpinningHammer.ogg" },
				{ "Z 追击就绪", "r-TheHunt.ogg" },
				{ "L 链接就绪", "r-Link.ogg" },
				{ "Q 青龙就绪", "r-YuLon.ogg" },
				{ "J 静滞就绪", "r-Stasis.ogg" },
				{ "H 黑眼就绪", "r-Darkglare.ogg" },
				{ "L 龙吼就绪", "r-DragonRoar.ogg" },
				{ "L 龙喷就绪", "r-BreathOfSindragosa.ogg" },
				{ "Z 准备大锤", "BigHammerReady.ogg" },
				{ "Z 准备皎月", "EclipseReady.ogg" },
				{ "M 免费圣令", "FreeWordofGlory.ogg" },
				{ "K 快打焚身", "BurnNow.ogg" },
				{ "K 快打顺劈", "CleaveNow.ogg" },
				{ "K 快翻书", "UseBook.ogg" },
				{ "K 快补奉献", "ConsecrationRefresh.ogg" },
				{ "B 补疾病", "DiseaseRefresh.ogg" },
				{ "B 补绽放", "BloomRefresh.ogg" },
				{ "B 补铁鬃", "IronfurRefresh.ogg" },
				{ "B 补黑檀", "EbonRefresh.ogg" },
				{ "B 补Dot", "DotRefresh.ogg" },
				{ "B 补Buff", "BuffRefresh.ogg" },
				{ "X 小技能就绪", "r-SmallCD.ogg" },
				{ "D 打断就绪", "r-Interrupt.ogg" },
				{ "Q 驱散就绪", "r-Dispell.ogg" },
				{ "D 大技能就绪", "r-BigCD.ogg" },
			},
		},
		{
			groupName = "Group nil",
			color = "FFFFFF",
			list = {
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", "01.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", "02.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", "03.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", "04.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", "05.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", "06.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", "07.ogg" },
				{ "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", "08.ogg" },
			},
		},
	},
	["statusbar"] = {
		{
			groupName = "Statusbars",
			list = {
				{ "BlizzardCast", "BlizzardCast.tga" },
				{ "BlizzardCastBackground", "BlizzardCastBackground.tga" },
				{ "BlizzardCastBgRound", "BlizzardCastBgRound.tga" },
				{ "BlizzardCastLite", "BlizzardCastLite.tga" },
				{ "BlizzardCastRound", "BlizzardCastRound.tga" },
				{ "BlizzardCastUninterruptableRound", "BlizzardCastUninterruptableRound.tga" },
				{ "BlizzardChannelRound", "BlizzardChannelRound.tga" },
				{ "BlizzardContainerFrame", "BlizzardContainerFrame.tga" },
				{ "BlizzardDF_bar", "BlizzardDF_bar.tga" },
				{ "SmokAugbar", "SmokAugbar.tga" },
				{ "SmokObjectiveTracker", "SmokObjectiveTracker.tga" },
				{ "SmokOnePixelBackground", "SmokOnePixelBackground.tga" },
				{ "SmokOnePixelbar", "SmokOnePixelbar.tga" },
				{ "WYJJGradient-Line", "WYJJGradient-Line.tga" },
				{ "WYJJGradient-Circle", "WYJJGradient-Circle.tga" },
				{ "RoundMurphy", "RoundMurphy.tga" },
			},
		},
	},
	["border"] = {
		{
			groupName = "Borders",
			list = {
				{ "RoundBorder", "RoundBorder.tga" },
				{ "TargetBorder", "TargetBorder.tga" },
			},
		},
	},
}
for mType, groups in pairs(mediaData) do
	for _, group in ipairs(groups) do
		local groupColor = group.color

		for _, item in ipairs(group.list) do
			local name, file = item[1], item[2]
			local displayName = name

			if mType == "sound" and groupColor then
				displayName = "|cFF" .. groupColor .. name .. "|r"
			end

			LSM:Register(mType, displayName, mPath .. mType .. [[\]] .. file)
		end
	end
end
