local LSM = LibStub("LibSharedMedia-3.0") 
-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -----
--   SOUND
-- -----
LSM:Register("sound", "|cFFAEEA941|r", [[Interface\Addons\WYJJDB\sound\1.ogg]])
LSM:Register("sound", "|cFFAEEA942|r", [[Interface\Addons\WYJJDB\sound\2.ogg]])
LSM:Register("sound", "|cFFAEEA943|r", [[Interface\Addons\WYJJDB\sound\3.ogg]])
LSM:Register("sound", "|cFFAEEA944|r", [[Interface\Addons\WYJJDB\sound\4.ogg]])
LSM:Register("sound", "|cFFAEEA945|r", [[Interface\Addons\WYJJDB\sound\5.ogg]])
LSM:Register("sound", "|cFFAEEA946|r", [[Interface\Addons\WYJJDB\sound\6.ogg]])
LSM:Register("sound", "|cFFAEEA947|r", [[Interface\Addons\WYJJDB\sound\7.ogg]])
LSM:Register("sound", "|cFFAEEA948|r", [[Interface\Addons\WYJJDB\sound\8.ogg]])
LSM:Register("sound", "|cFFAEEA949|r", [[Interface\Addons\WYJJDB\sound\9.ogg]])
LSM:Register("sound", "|cFFAEEA9410|r", [[Interface\Addons\WYJJDB\sound\10.ogg]])
LSM:Register("sound", "|cFFAEEA94第一|r", [[Interface\Addons\WYJJDB\sound\First.ogg]])
LSM:Register("sound", "|cFFAEEA94第二|r", [[Interface\Addons\WYJJDB\sound\Second.ogg]])
LSM:Register("sound", "|cFFAEEA94第三|r", [[Interface\Addons\WYJJDB\sound\Third.ogg]])
LSM:Register("sound", "|cFFAEEA94第四|r", [[Interface\Addons\WYJJDB\sound\Fourth.ogg]])
LSM:Register("sound", "|cFFAEEA94第五|r", [[Interface\Addons\WYJJDB\sound\Fifth.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\WYJJDB\sound\01.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\WYJJDB\sound\02.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\WYJJDB\sound\03.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\WYJJDB\sound\04.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\WYJJDB\sound\05.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\WYJJDB\sound\06.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\WYJJDB\sound\07.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\WYJJDB\sound\08.ogg]])
LSM:Register("sound", "|cFFAEEA94准备大怪|r", [[Interface\Addons\WYJJDB\sound\Add.ogg]])
LSM:Register("sound", "|cFFAEEA94小怪快打|r", [[Interface\Addons\WYJJDB\sound\Adds.ogg]])
LSM:Register("sound", "|cFFAEEA94注意词缀|r", [[Interface\Addons\WYJJDB\sound\Affix.ogg]])
LSM:Register("sound", "|cFFAEEA94AoE|r", [[Interface\Addons\WYJJDB\sound\AoE.ogg]])
LSM:Register("sound", "|cFFAEEA94协助|r", [[Interface\Addons\WYJJDB\sound\Assist.ogg]])
LSM:Register("sound", "|cFFAEEA94规避|r", [[Interface\Addons\WYJJDB\sound\Avoid.ogg]])
LSM:Register("sound", "|cFFAEEA94后退|r", [[Interface\Addons\WYJJDB\sound\Back.ogg]])
LSM:Register("sound", "|cFFAEEA94备选|r", [[Interface\Addons\WYJJDB\sound\Backup.ogg]])
LSM:Register("sound", "|cFFAEEA94引导位置|r", [[Interface\Addons\WYJJDB\sound\Bait.ogg]])
LSM:Register("sound", "|cFFAEEA94注意射线|r", [[Interface\Addons\WYJJDB\sound\Beam.ogg]])
LSM:Register("sound", "|cFFAEEA94坦克承伤|r", [[Interface\Addons\WYJJDB\sound\Bite.ogg]])
LSM:Register("sound", "|cFFAEEA94嗜血|r", [[Interface\Addons\WYJJDB\sound\Bloodlust.ogg]])
LSM:Register("sound", "|cFFAEEA94蓝色|r", [[Interface\Addons\WYJJDB\sound\Blue.ogg]])
LSM:Register("sound", "|cFFAEEA94炸弹|r", [[Interface\Addons\WYJJDB\sound\Bombs.ogg]])
LSM:Register("sound", "|cFFAEEA94Boss|r", [[Interface\Addons\WYJJDB\sound\Boss.ogg]])
LSM:Register("sound", "|cFFAEEA94打破|r", [[Interface\Addons\WYJJDB\sound\Break.ogg]])
LSM:Register("sound", "|cFFAEEA94Buff|r", [[Interface\Addons\WYJJDB\sound\Buff.ogg]])
LSM:Register("sound", "|cFFAEEA94快交控制|r", [[Interface\Addons\WYJJDB\sound\CC.ogg]])
LSM:Register("sound", "|cFFAEEA94CD|r", [[Interface\Addons\WYJJDB\sound\CD.ogg]])
LSM:Register("sound", "|cFFAEEA94中间|r", [[Interface\Addons\WYJJDB\sound\Center.ogg]])
LSM:Register("sound", "|cFFAEEA94锁链|r", [[Interface\Addons\WYJJDB\sound\Chain.ogg]])
LSM:Register("sound", "|cFFAEEA94冲锋|r", [[Interface\Addons\WYJJDB\sound\Charge.ogg]])
LSM:Register("sound", "|cFFAEEA94检查|r", [[Interface\Addons\WYJJDB\sound\Check.ogg]])
LSM:Register("sound", "|cFFAEEA94清除|r", [[Interface\Addons\WYJJDB\sound\Clear.ogg]])
LSM:Register("sound", "|cFFAEEA94收集|r", [[Interface\Addons\WYJJDB\sound\Collect.ogg]])
LSM:Register("sound", "|cFFAEEA94躲地板|r", [[Interface\Addons\WYJJDB\sound\Dance.ogg]])
LSM:Register("sound", "|cFFAEEA94防御|r", [[Interface\Addons\WYJJDB\sound\Defensive.ogg]])
LSM:Register("sound", "|cFFAEEA94Debuff|r", [[Interface\Addons\WYJJDB\sound\Debuff.ogg]])
LSM:Register("sound", "|cFFAEEA94驱散|r", [[Interface\Addons\WYJJDB\sound\Dispell.ogg]])
LSM:Register("sound", "|cFFAEEA94注意躲避|r", [[Interface\Addons\WYJJDB\sound\Dodge.ogg]])
LSM:Register("sound", "|cFFAEEA94不要|r", [[Interface\Addons\WYJJDB\sound\Dont.ogg]])
LSM:Register("sound", "|cFFAEEA94停止移动|r", [[Interface\Addons\WYJJDB\sound\Dont Move.ogg]])
LSM:Register("sound", "|cFFAEEA94Dot|r", [[Interface\Addons\WYJJDB\sound\Dot.ogg]])
LSM:Register("sound", "|cFFAEEA94放水|r", [[Interface\Addons\WYJJDB\sound\Drop.ogg]])
LSM:Register("sound", "|cFFAEEA94进入|r", [[Interface\Addons\WYJJDB\sound\Enter.ogg]])
LSM:Register("sound", "|cFFAEEA94哨兵|r", [[Interface\Addons\WYJJDB\sound\Escort.ogg]])
LSM:Register("sound", "|cFFAEEA94退出|r", [[Interface\Addons\WYJJDB\sound\Exit.ogg]])
LSM:Register("sound", "|cFFAEEA94外部|r", [[Interface\Addons\WYJJDB\sound\External.ogg]])
LSM:Register("sound", "|cFFAEEA94注意脚下|r", [[Interface\Addons\WYJJDB\sound\Feet.ogg]])
LSM:Register("sound", "|cFFAEEA94目标锁定|r", [[Interface\Addons\WYJJDB\sound\Fixate.ogg]])
LSM:Register("sound", "|cFFAEEA94焦点|r", [[Interface\Addons\WYJJDB\sound\Focus.ogg]])
LSM:Register("sound", "|cFFAEEA94注意头前|r", [[Interface\Addons\WYJJDB\sound\Front.ogg]])
LSM:Register("sound", "|cFFAEEA94开门|r", [[Interface\Addons\WYJJDB\sound\Gate.ogg]])
LSM:Register("sound", "|cFFAEEA94收集|r", [[Interface\Addons\WYJJDB\sound\Gather.ogg]])
LSM:Register("sound", "|cFFAEEA94绿色|r", [[Interface\Addons\WYJJDB\sound\Green.ogg]])
LSM:Register("sound", "|cFFAEEA94前进|r", [[Interface\Addons\WYJJDB\sound\Go.ogg]])
LSM:Register("sound", "|cFFAEEA94抓紧|r", [[Interface\Addons\WYJJDB\sound\Grip.ogg]])
LSM:Register("sound", "|cFFAEEA94治疗CD|r", [[Interface\Addons\WYJJDB\sound\Healcd.ogg]])
LSM:Register("sound", "|cFFAEEA94躲避伤害|r", [[Interface\Addons\WYJJDB\sound\Hide.ogg]])
LSM:Register("sound", "|cFFAEEA94能量过高|r", [[Interface\Addons\WYJJDB\sound\High Energy.ogg]])
LSM:Register("sound", "|cFFAEEA94层数过高|r", [[Interface\Addons\WYJJDB\sound\High Stacks.ogg]])
LSM:Register("sound", "|cFFAEEA94免疫|r", [[Interface\Addons\WYJJDB\sound\Immunity.ogg]])
LSM:Register("sound", "|cFFAEEA94进进进|r", [[Interface\Addons\WYJJDB\sound\In.ogg]])
LSM:Register("sound", "|cFFAEEA94打断施法|r", [[Interface\Addons\WYJJDB\sound\Interrupt.ogg]])
LSM:Register("sound", "|cFFAEEA94阶段转换|r", [[Interface\Addons\WYJJDB\sound\Intermission.ogg]])
LSM:Register("sound", "|cFFAEEA94隐身|r", [[Interface\Addons\WYJJDB\sound\Invisibility.ogg]])
LSM:Register("sound", "|cFFAEEA94跳|r", [[Interface\Addons\WYJJDB\sound\Jump.ogg]])
LSM:Register("sound", "|cFFAEEA94快打断|r", [[Interface\Addons\WYJJDB\sound\Kick.ogg]])
LSM:Register("sound", "|cFFAEEA94风筝|r", [[Interface\Addons\WYJJDB\sound\Kite.ogg]])
LSM:Register("sound", "|cFFAEEA94击飞|r", [[Interface\Addons\WYJJDB\sound\Knock.ogg]])
LSM:Register("sound", "|cFFAEEA94最后|r", [[Interface\Addons\WYJJDB\sound\Last.ogg]])
LSM:Register("sound", "|cFFAEEA94左边|r", [[Interface\Addons\WYJJDB\sound\Left.ogg]])
LSM:Register("sound", "|cFFAEEA94跳跃|r", [[Interface\Addons\WYJJDB\sound\Leap.ogg]])
LSM:Register("sound", "|cFFAEEA94连线|r", [[Interface\Addons\WYJJDB\sound\Line.ogg]])
LSM:Register("sound", "|cFFAEEA94链接|r", [[Interface\Addons\WYJJDB\sound\Link.ogg]])
LSM:Register("sound", "|cFFAEEA94被连接|r", [[Interface\Addons\WYJJDB\sound\Linked.ogg]])
LSM:Register("sound", "|cFFAEEA94卡视野|r", [[Interface\Addons\WYJJDB\sound\LoS.ogg]])
LSM:Register("sound", "|cFFAEEA94宏|r", [[Interface\Addons\WYJJDB\sound\Macro.ogg]])
LSM:Register("sound", "|cFFAEEA94近战|r", [[Interface\Addons\WYJJDB\sound\Melee.ogg]])
LSM:Register("sound", "|cFFAEEA94地雷|r", [[Interface\Addons\WYJJDB\sound\Mines.ogg]])
LSM:Register("sound", "|cFFAEEA94移动|r", [[Interface\Addons\WYJJDB\sound\Move.ogg]])
LSM:Register("sound", "|cFFAEEA94下一个|r", [[Interface\Addons\WYJJDB\sound\Next.ogg]])
LSM:Register("sound", "|cFFAEEA94集中攻击|r", [[Interface\Addons\WYJJDB\sound\Nuke.ogg]])
LSM:Register("sound", "|cFFAEEA94橙色|r", [[Interface\Addons\WYJJDB\sound\Orange.ogg]])
LSM:Register("sound", "|cFFAEEA94宝珠|r", [[Interface\Addons\WYJJDB\sound\Orb.ogg]])
LSM:Register("sound", "|cFFAEEA94出出出|r", [[Interface\Addons\WYJJDB\sound\Out.ogg]])
LSM:Register("sound", "|cFFAEEA94重叠|r", [[Interface\Addons\WYJJDB\sound\Overlap.ogg]])
LSM:Register("sound", "|cFFAEEA94砰砰|r", [[Interface\Addons\WYJJDB\sound\Pop.ogg]])
LSM:Register("sound", "|cFFAEEA94药水|r", [[Interface\Addons\WYJJDB\sound\Pots.ogg]])
LSM:Register("sound", "|cFFAEEA94准备拉人|r", [[Interface\Addons\WYJJDB\sound\Pull.ogg]])
LSM:Register("sound", "|cFFAEEA94紫色|r", [[Interface\Addons\WYJJDB\sound\Purple.ogg]])
LSM:Register("sound", "|cFFAEEA94准备推人|r", [[Interface\Addons\WYJJDB\sound\Push.ogg]])
LSM:Register("sound", "|cFFAEEA94远程|r", [[Interface\Addons\WYJJDB\sound\Range.ogg]])
LSM:Register("sound", "|cFFAEEA94准备就绪|r", [[Interface\Addons\WYJJDB\sound\Ready.ogg]])
LSM:Register("sound", "|cFFAEEA94红色|r", [[Interface\Addons\WYJJDB\sound\Red.ogg]])
LSM:Register("sound", "|cFFAEEA94反射|r", [[Interface\Addons\WYJJDB\sound\Reflect.ogg]])
LSM:Register("sound", "|cFFAEEA94刷新|r", [[Interface\Addons\WYJJDB\sound\Refresh.ogg]])
LSM:Register("sound", "|cFFAEEA94右边|r", [[Interface\Addons\WYJJDB\sound\Right.ogg]])
LSM:Register("sound", "|cFFAEEA94圆环|r", [[Interface\Addons\WYJJDB\sound\Ring.ogg]])
LSM:Register("sound", "|cFFAEEA94定身|r", [[Interface\Addons\WYJJDB\sound\Root.ogg]])
LSM:Register("sound", "|cFFAEEA94种子|r", [[Interface\Addons\WYJJDB\sound\Seed.ogg]])
LSM:Register("sound", "|cFFAEEA94个人CD|r", [[Interface\Addons\WYJJDB\sound\Selfcd.ogg]])
LSM:Register("sound", "|cFFAEEA94护盾|r", [[Interface\Addons\WYJJDB\sound\Shield.ogg]])
LSM:Register("sound", "|cFFAEEA94帮忙吸收|r", [[Interface\Addons\WYJJDB\sound\Soak.ogg]])
LSM:Register("sound", "|cFFAEEA94马上马上|r", [[Interface\Addons\WYJJDB\sound\Soon.ogg]])
LSM:Register("sound", "|cFFAEEA94孵化|r", [[Interface\Addons\WYJJDB\sound\Spawn.ogg]])
LSM:Register("sound", "|cFFAEEA94进攻驱散|r", [[Interface\Addons\WYJJDB\sound\Spellsteal.ogg]])
LSM:Register("sound", "|cFFAEEA94分裂|r", [[Interface\Addons\WYJJDB\sound\Split.ogg]])
LSM:Register("sound", "|cFFAEEA94分散|r", [[Interface\Addons\WYJJDB\sound\Spread.ogg]])
LSM:Register("sound", "|cFFAEEA94叠层|r", [[Interface\Addons\WYJJDB\sound\Stack.ogg]])
LSM:Register("sound", "|cFFAEEA94保持|r", [[Interface\Addons\WYJJDB\sound\Stay.ogg]])
LSM:Register("sound", "|cFFAEEA94停止|r", [[Interface\Addons\WYJJDB\sound\Stop.ogg]])
LSM:Register("sound", "|cFFAEEA94停止施法|r", [[Interface\Addons\WYJJDB\sound\Stopcast.ogg]])
LSM:Register("sound", "|cFFAEEA94交换|r", [[Interface\Addons\WYJJDB\sound\Swap.ogg]])
LSM:Register("sound", "|cFFAEEA94目标转换|r", [[Interface\Addons\WYJJDB\sound\Switch.ogg]])
LSM:Register("sound", "|cFFAEEA94目标是你|r", [[Interface\Addons\WYJJDB\sound\Targeted.ogg]])
LSM:Register("sound", "|cFFAEEA94嘲讽|r", [[Interface\Addons\WYJJDB\sound\Taunt.ogg]])
LSM:Register("sound", "|cFFAEEA94图腾|r", [[Interface\Addons\WYJJDB\sound\Totem.ogg]])
LSM:Register("sound", "|cFFAEEA94阶段转换|r", [[Interface\Addons\WYJJDB\sound\Transition.ogg]])
LSM:Register("sound", "|cFFAEEA94陷阱|r", [[Interface\Addons\WYJJDB\sound\Trap.ogg]])
LSM:Register("sound", "|cFFAEEA94转身|r", [[Interface\Addons\WYJJDB\sound\Turn.ogg]])
LSM:Register("sound", "|cFFAEEA94使用|r", [[Interface\Addons\WYJJDB\sound\Use.ogg]])
LSM:Register("sound", "|cFFAEEA94齐射|r", [[Interface\Addons\WYJJDB\sound\Volley.ogg]])
LSM:Register("sound", "|cFFAEEA94波浪|r", [[Interface\Addons\WYJJDB\sound\Wave.ogg]])
LSM:Register("sound", "|cFFAEEA94风|r", [[Interface\Addons\WYJJDB\sound\Winds.ogg]])
LSM:Register("sound", "|cFFAEEA94黄色|r", [[Interface\Addons\WYJJDB\sound\Yellow.ogg]])
LSM:Register("sound", "|cFFAEEA94区域|r", [[Interface\Addons\WYJJDB\sound\Zone.ogg]])
LSM:Register("sound", "|cFFAEEA94该补控了|r", [[Interface\Addons\WYJJDB\sound\RefillCC.ogg]])
LSM:Register("sound", "|cFFAEEA94焦点打断|r", [[Interface\Addons\WYJJDB\sound\Focus Interrupt.ogg]])
LSM:Register("sound", "|cFFAEEA94双点|r", [[Interface\Addons\WYJJDB\sound\DoubleCasts.ogg]])
--CDS
LSM:Register("sound", "|cFFAEEA99罩子|r |T237510:16|t", [[Interface\Addons\WYJJDB\sound\AMZ.ogg]])
LSM:Register("sound", "|cFFAEEA99天使|r |T612969:16|t", [[Interface\Addons\WYJJDB\sound\Angel.ogg]])
LSM:Register("sound", "|cFFAEEA99升腾|r |T135791:16|t", [[Interface\Addons\WYJJDB\sound\Ascendance.ogg]])
LSM:Register("sound", "|cFFAEEA99秋|r |T3636843:16|t", [[Interface\Addons\WYJJDB\sound\Autumn.ogg]])
LSM:Register("sound", "|cFFAEEA99树皮|r |T572025:16|t", [[Interface\Addons\WYJJDB\sound\Bark.ogg]])
LSM:Register("sound", "|cFFAEEA99屏障|r |T253400:16|t", [[Interface\Addons\WYJJDB\sound\Barrier.ogg]])
LSM:Register("sound", "|cFFAEEA99赤精|r |T877514:16|t", [[Interface\Addons\WYJJDB\sound\Chi-ji.ogg]])
LSM:Register("sound", "|cFFAEEA99茧|r |T627485:16|t", [[Interface\Addons\WYJJDB\sound\Cocoon.ogg]])
LSM:Register("sound", "|cFFAEEA99黑暗|r |T1305154:16|t", [[Interface\Addons\WYJJDB\sound\Darkness.ogg]])
LSM:Register("sound", "|cFFAEEA99光环掌握|r |T135893:16|t", [[Interface\Addons\WYJJDB\sound\Devo.ogg]])
LSM:Register("sound", "|cFFAEEA99矮人|r |T136225:16|t", [[Interface\Addons\WYJJDB\sound\Dwarf.ogg]])
LSM:Register("sound", "|cFFAEEA99自由|r |T135968:16|t", [[Interface\Addons\WYJJDB\sound\Freedom.ogg]])
LSM:Register("sound", "|cFFAEEA99治疗之潮|r |T538569:16|t", [[Interface\Addons\WYJJDB\sound\Healing Tide.ogg]])
LSM:Register("sound", "|cFFAEEA99赞美诗|r |T237540:16|t", [[Interface\Addons\WYJJDB\sound\Hymn.ogg]])
LSM:Register("sound", "|cFFAEEA99化身|r |T236157:16|t", [[Interface\Addons\WYJJDB\sound\Incarn.ogg]])
LSM:Register("sound", "|cFFAEEA99激活|r |T136048:16|t", [[Interface\Addons\WYJJDB\sound\Innervate.ogg]])
LSM:Register("sound", "|cFFAEEA99圣疗|r |T135928:16|t", [[Interface\Addons\WYJJDB\sound\Lay.ogg]])
LSM:Register("sound", "|cFFAEEA99影遁|r |T132089:16|t", [[Interface\Addons\WYJJDB\sound\Meld.ogg]])
LSM:Register("sound", "|cFFAEEA99误导|r |T132180:16|t", [[Interface\Addons\WYJJDB\sound\Misdirect.ogg]])
LSM:Register("sound", "|cFFAEEA99悖论|r |T5199645:16|t", [[Interface\Addons\WYJJDB\sound\Paradox.ogg]])
LSM:Register("sound", "|cFFAEEA99灌注|r |T135939:16|t", [[Interface\Addons\WYJJDB\sound\PI.ogg]])
LSM:Register("sound", "|cFFAEEA99保护|r |T135964:16|t", [[Interface\Addons\WYJJDB\sound\Protection.ogg]])
LSM:Register("sound", "|cFFAEEA99压制|r |T135936:16|t", [[Interface\Addons\WYJJDB\sound\PS.ogg]])
LSM:Register("sound", "|cFFAEEA99集结呐喊|r |T132351:16|t", [[Interface\Addons\WYJJDB\sound\Rally.ogg]])
LSM:Register("sound", "|cFFAEEA99营救|r |T4622460:16|t", [[Interface\Addons\WYJJDB\sound\Rescue.ogg]])
LSM:Register("sound", "|cFFAEEA99还魂|r |T1020466:16|t", [[Interface\Addons\WYJJDB\sound\Revival.ogg]])
LSM:Register("sound", "|cFFAEEA99回溯|r |T4622474:16|t", [[Interface\Addons\WYJJDB\sound\Rewind.ogg]])
LSM:Register("sound", "|cFFAEEA99怒吼|r |T463283:16|t", [[Interface\Addons\WYJJDB\sound\Roar.ogg]])
LSM:Register("sound", "|cFFAEEA99牺牲|r |T135966:16|t", [[Interface\Addons\WYJJDB\sound\Sac.ogg]])
LSM:Register("sound", "|cFFAEEA99灵魂连接|r |T237586:16|t", [[Interface\Addons\WYJJDB\sound\SLT.ogg]])
LSM:Register("sound", "|cFFAEEA99帷幕|r |T635350:16|t", [[Interface\Addons\WYJJDB\sound\Shroud.ogg]])
LSM:Register("sound", "|cFFAEEA99破咒|r |T135880:16|t", [[Interface\Addons\WYJJDB\sound\Spellwarding.ogg]])
LSM:Register("sound", "|cFFAEEA99春|r |T3636844:16|t", [[Interface\Addons\WYJJDB\sound\Spring.ogg]])
LSM:Register("sound", "|cFFAEEA99灵魂石|r |T136210:16|t", [[Interface\Addons\WYJJDB\sound\SS.ogg]])
LSM:Register("sound", "|cFFAEEA99夏|r |T3636845:16|t", [[Interface\Addons\WYJJDB\sound\Summer.ogg]])
LSM:Register("sound", "|cFFAEEA99时间螺旋|r |T4622479:16|t", [[Interface\Addons\WYJJDB\sound\Time Spiral.ogg]])
LSM:Register("sound", "|cFFAEEA99时间膨胀|r |T4622478:16|t", [[Interface\Addons\WYJJDB\sound\TD.ogg]])
LSM:Register("sound", "|cFFAEEA99驯如猛虎|r |T651727:16|t", [[Interface\Addons\WYJJDB\sound\Tiger's Lust.ogg]])
LSM:Register("sound", "|cFFAEEA99宁静|r |T136107:16|t", [[Interface\Addons\WYJJDB\sound\Tranq.ogg]])
LSM:Register("sound", "|cFFAEEA99嫁祸|r |T236283:16|t", [[Interface\Addons\WYJJDB\sound\Tricks.ogg]])
LSM:Register("sound", "|cFFAEEA99狂风图腾|r |T538576:16|t", [[Interface\Addons\WYJJDB\sound\Wind Rush.ogg]])
LSM:Register("sound", "|cFFAEEA99冬|r |T3636846:16|t", [[Interface\Addons\WYJJDB\sound\Winter.ogg]])
--Custom
LSM:Register("sound", "|cFFAEEA99群盾|r |T1723997:16|t", [[Interface\Addons\WYJJDB\sound\Mass Barrier.ogg]])
LSM:Register("sound", "|cFFAEEA99战复图腾|r |T136080:16|t", [[Interface\Addons\WYJJDB\sound\APT.ogg]])
LSM:Register("sound", "|cFFAEEA99援护|r |T132365:16|t", [[Interface\Addons\WYJJDB\sound\Intervene.ogg]])
LSM:Register("sound", "|cFFAEEA99盾反|r |T132361:16|t", [[Interface\Addons\WYJJDB\sound\Spell Reflect.ogg]])
LSM:Register("sound", "|cFFAEEA99加速|r", [[Interface\Addons\WYJJDB\sound\Fast.ogg]])
LSM:Register("sound", "|cFFAEEA99微风|r |T4630449:16|t", [[Interface\Addons\WYJJDB\sound\Zephyr.ogg]])
LSM:Register("sound", "|cFFAEEA99红驱|r |T4630446:16|t", [[Interface\Addons\WYJJDB\sound\Cauterizing Flame.ogg]])
LSM:Register("sound", "|cFFAEEA99龟壳|r |T132199:16|t", [[Interface\Addons\WYJJDB\sound\Turtle.ogg]])
LSM:Register("sound", "|cFFAEEA99假死|r |T132293:16|t", [[Interface\Addons\WYJJDB\sound\Feign Death.ogg]])
LSM:Register("sound", "|cFFAEEA99绿罩|r |T136120:16|t", [[Interface\Addons\WYJJDB\sound\Anti-Magic Shell.ogg]])
LSM:Register("sound", "|cFFAEEA99无敌|r |T524354:16|t", [[Interface\Addons\WYJJDB\sound\Divine Shield.ogg]])
LSM:Register("sound", "|cFFAEEA99消散|r |T237563:16|t", [[Interface\Addons\WYJJDB\sound\Dispersion.ogg]])
LSM:Register("sound", "|cFFAEEA99斗篷|r |T136177:16|t", [[Interface\Addons\WYJJDB\sound\Cloak.ogg]])
LSM:Register("sound", "|cFFAEEA99强隐|r |T575584:16|t", [[Interface\Addons\WYJJDB\sound\Invisibility.ogg]])
LSM:Register("sound", "|cFFAEEA99春哥|r |T252268:16|t", [[Interface\Addons\WYJJDB\sound\SpringBro.ogg]])
LSM:Register("sound", "|cFFAEEA99冰箱|r |T135841:16|t", [[Interface\Addons\WYJJDB\sound\Ice Block.ogg]])
LSM:Register("sound", "|cFFAEEA99虚空行走|r |T463284:16|t", [[Interface\Addons\WYJJDB\sound\Netherwalk.ogg]])
LSM:Register("sound", "|cFFAEEA99压迫怒吼|r |T4622466:16|t", [[Interface\Addons\WYJJDB\sound\Oppressing Roar.ogg]])
LSM:Register("sound", "|cFFAEEA99战栗图腾|r |T136108:16|t", [[Interface\Addons\WYJJDB\sound\Tremor Totem.ogg]])
LSM:Register("sound", "|cFFAEEA99清毒图腾|r |T136070:16|t", [[Interface\Addons\WYJJDB\sound\PCT.ogg]])

--CCs
LSM:Register("sound", "|cFFAEEA95电能图腾|r |T136013:16|t", [[Interface\Addons\WYJJDB\sound\Capacitor Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95陷地图腾|r |T136100:16|t", [[Interface\Addons\WYJJDB\sound\Earthgrab Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95地缚图腾|r |T136102:16|t", [[Interface\Addons\WYJJDB\sound\Earthbind Totem.ogg]])
LSM:Register("sound", "|cFFAEEA95雷霆风暴|r |T237589:16|t", [[Interface\Addons\WYJJDB\sound\Thunderstorm.ogg]])
LSM:Register("sound", "|cFFAEEA95心灵尖啸|r |T136184:16|t", [[Interface\Addons\WYJJDB\sound\Psychic Scream.ogg]])
LSM:Register("sound", "|cFFAEEA95震荡波|r |T236312:16|t", [[Interface\Addons\WYJJDB\sound\Shockwave.ogg]])
LSM:Register("sound", "|cFFAEEA95扫堂腿|r |T642414:16|t", [[Interface\Addons\WYJJDB\sound\Leg Sweep.ogg]])
LSM:Register("sound", "|cFFAEEA95暗影之怒|r |T607865:16|t", [[Interface\Addons\WYJJDB\sound\Shadowfury.ogg]])
LSM:Register("sound", "|cFFAEEA95盲目之光|r |T571553:16|t", [[Interface\Addons\WYJJDB\sound\Blinding Light.ogg]])
LSM:Register("sound", "|cFFAEEA95乌索尔旋风|r |T571588:16|t", [[Interface\Addons\WYJJDB\sound\Ursol's Vortex.ogg]])
LSM:Register("sound", "|cFFAEEA95日光术|r |T252188:16|t", [[Interface\Addons\WYJJDB\sound\Solar Beam.ogg]])
LSM:Register("sound", "|cFFAEEA95混乱新星|r |T135795:16|t", [[Interface\Addons\WYJJDB\sound\Chaos Nova.ogg]])
LSM:Register("sound", "|cFFAEEA95悲苦咒符|r |T1418287:16|t", [[Interface\Addons\WYJJDB\sound\Sigil of Misery.ogg]])
LSM:Register("sound", "|cFFAEEA95沉默咒符|r |T1418288:16|t", [[Interface\Addons\WYJJDB\sound\Sigil of Silence.ogg]])
LSM:Register("sound", "|cFFAEEA95破胆怒吼|r |T132154:16|t", [[Interface\Addons\WYJJDB\sound\Intimidating Shout.ogg]])
LSM:Register("sound", "|cFFAEEA95战争践踏|r |T132368:16|t", [[Interface\Addons\WYJJDB\sound\War Stomp.ogg]])
LSM:Register("sound", "|cFFAEEA95平心之环|r |T839107:16|t", [[Interface\Addons\WYJJDB\sound\Ring of Peace.ogg]])
LSM:Register("sound", "|cFFAEEA95台风|r |T236170:16|t", [[Interface\Addons\WYJJDB\sound\Typhoon.ogg]])
LSM:Register("sound", "|cFFAEEA95飞翼打击|r |T4622488:16|t", [[Interface\Addons\WYJJDB\sound\Wing Buffet.ogg]])
LSM:Register("sound", "|cFFAEEA95扫尾|r |T4622486:16|t", [[Interface\Addons\WYJJDB\sound\Tail Sweep.ogg]])
LSM:Register("sound", "|cFFAEEA95奥术洪流|r |T136222:16|t", [[Interface\Addons\WYJJDB\sound\Arcane Torrent.ogg]])
LSM:Register("sound", "|cFFAEEA95夺魂咆哮|r |T132121:16|t", [[Interface\Addons\WYJJDB\sound\Incapacitating Roar.ogg]])
LSM:Register("sound", "|cFFAEEA95超级新星|r |T1033912:16|t", [[Interface\Addons\WYJJDB\sound\Supernova.ogg]])
LSM:Register("sound", "|cFFAEEA95冲击波|r |T135903:16|t", [[Interface\Addons\WYJJDB\sound\Blast Wave.ogg]])
LSM:Register("sound", "|cFFAEEA95死亡之握|r |T237532:16|t", [[Interface\Addons\WYJJDB\sound\Death Grip.ogg]])
LSM:Register("sound", "|cFFAEEA95内爆陷阱|r |T1044088:16|t", [[Interface\Addons\WYJJDB\sound\Implosive Trap.ogg]])
LSM:Register("sound", "|cFFAEEA95致盲冰雨|r |T135836:16|t", [[Interface\Addons\WYJJDB\sound\Blinding Sleet.ogg]])
LSM:Register("sound", "|cFFAEEA95束缚射击|r |T462650:16|t", [[Interface\Addons\WYJJDB\sound\Binding Shot.ogg]])
LSM:Register("sound", "|cFFAEEA95瓦解怒吼|r |T132091:16|t", [[Interface\Addons\WYJJDB\sound\Disrupting Shout.ogg]])
-- -----
--   STATUSBAR
-- -----
