local addonName, addonTable = ...;
local _, _, _, tocversion = GetBuildInfo()
local L=addonTable.locale
--if GetLocale() == "zhCN" then
--error
L["ERROR_ERROR1"] = "尝试调用保护功能";
L["ERROR_ERROR2"] = "宏尝试调用保护功能";
L["ERROR_DEBUGTOOLTIP"] = "发生错误时在小地图按钮显示一个红X\n并且不会收纳BugSack插件的小地图图标";
--Shared
L["LIB_QUERY"] = "查询";
L["LIB_TIPS"] = "提示";
L["LIB_PLUS"] = "额外";
L["LIB_SIZE"] = "尺寸";
L["LIB_POINT"] = "位置";
L["LIB_LAYOUT"] = "布局";
L["LIB_WIDTH"]= "宽度";
L["LIB_HEIGHT"]= "高度";
L["LIB_MACROERR"] = "你的宏数量已达最大值120，请删除一些再尝试";
L["LIB_NOTENABLED"]= "未启用";
L["LIB_NOTINST"]= "未安装";
L["LIB_STOPMAINT"]= "已停止维护";
L["LIB_ADDCOLL"]= "已添加";
L["LIB_DELCOLL"]= "已删除";
L["LIB_COLLERR1"]= "已存在";
L["LIB_CLEAR"] = "清空"
L["LIB_AUTO"] = "自动%s"
L["LIB_GNBUT"] = "%s按钮"
L["LIB_RECORD"] = "%s记录"
--OptionsUI
L["OPTUI_SET"] = "设置";
L["OPTUI_RLUITIPS"] = "***配置已更改,请重载UI以应用新配置***";
L["OPTUI_ERRORTIPS"] = "***插件加载失败，请重新尝试***";
L["OPTUI_RESETDEFAULT"] = "%s\n|cffFF0000"..RESET_TO_DEFAULT.."|r"
L["OPTUI_RESETDEFAULTRL"] = "%s\n|cffFF0000"..RESET_TO_DEFAULT.."|r("..RELOADUI..")?"
L["OPTUI_OPENGN"] = "\n|cff00FF00%s|r("..RELOADUI..")?"
--About
L["ADDON_LOAD"] = "载入成功, /pig或小地图按钮设置";
L["ABOUT_TABNAME"] = "关于";
L["ABOUT_TABNAME2"] = "扩展";
L["ABOUT_MAIL"]="反馈邮箱: "
L["ABOUT_TUTORIAL"]="使用教程: "
L["ABOUT_DISC"]="玩家交流: "
L["ABOUT_FUNC"]="主要功能: "
L["ABOUT_GETURL"]="获取方式: "
L["ABOUT_UPDATETIPS"] = "插件已过期,更新方式查看关于菜单";
--Debug
L["DEBUG_TABNAME"] = "调试";
L["DEBUG_BUTNAME"] = "内存CPU监控";
L["DEBUG_CPUUSAGE"] = "CPU性能分析";
L["DEBUG_CPUUSAGETIPS"] = "开启CPU使用率监控\n请只在需要时候开启，此功能需要消耗一些系统性能\n"..L["RELOADUI"];
L["DEBUG_CPUUSAGEWARNING"] = "你开启了CPU性能分析，请在测试后关闭此选项"
L["DEBUG_COLLECT"] = "回收";
L["DEBUG_COLLECTTIPS"] = "|cff00FFff此功能会导致插件所有执行都停止，直到收回过程完成。\n插件过多情况下可能超过几秒，这会令游戏暂时冻结(卡住)。\n除开插件开发调试，大多数情况不需要手动调用，LUA自动内存管理机制会定期运作|r"
L["DEBUG_ADDNUM"] = "个插件";
L["DEBUG_ADD"] = "插件";
L["DEBUG_MEMORY"] = "内存";
L["DEBUG_ERRORLOG"] = "错误日志";
L["DEBUG_OPENERRORLOGCMD"] = "打开日志指令：";
L["DEBUG_SCRIPTTOOLTIP"] = "打开游戏自带的LUA错误提示功能，非调试插件情况下请不要开启";
L["DEBUG_TAINTLOG"] = "污染日志";
L["DEBUG_TAINT0"] = "不记录任何内容";
L["DEBUG_TAINT1"] = "记录被阻止的操作";
L["DEBUG_TAINT2"] = "记录被阻止的操作/全局变量";
L["DEBUG_TAINT11"] = "记录被阻止的操作/全局变量/条目(PTR/Beta)";
L["DEBUG_GETGUID"] = "获取目标GUID";
L["DEBUG_SHOWGRID"] = HUD_EDIT_MODE_SHOW_GRID or "显示网格"
L["DEBUG_CONFIG"] = "调试配置";
L["DEBUG_CONFIGTIPS"] = "此配置默认关闭所有功能，供调试插件使用";
--Config
L["CONFIG_TABNAME"] = "配置";
L["CONFIG_DIYTIPS"] = "把你的"..addonName.."配置加入到插件"..CHAT_DEFAULT.."配置列表，你可以在任何地方载入你的配置";
L["CONFIG_LOADTIPS"] = "载入|cff00ff00<%s>|r"..INFO.."?\n当前配置数据将被|cffff0000重置|r,需重载界面";
L["CONFIG_ERRTIPS"] = "1、如遇到问题，请在此载入插件"..CHAT_DEFAULT.."配置。\n2、如问题仍未解决请通过关于内的反馈方式提交问题。";
L["CONFIG_LOAD"] = "载入";
L["CONFIG_DAOCHU"] = "导出";
L["CONFIG_DAORU"] = "导入";
L["CONFIG_IMPORT"] = "请在下方输入要导入的字符串，并点击导入按钮";
L["CONFIG_DERIVE"] = "请复制下方字符串，粘贴到需要导入位置";
L["CONFIG_DERIVERL"] = "导入并重载";
L["CONFIG_DERIVEERROR"] = "导入失败，无法识别的字符串";
--常用
L["COMMON_SLUGOFF"] = "关闭Slug字体特效";
L["COMMON_SLUGOFFTISP"]="关闭10.0之后增加的Slug字体特效。一种新的字体渲染引擎，主要为了改善浮动信息以及姓名板名字效果。但是此功能会导致额外加载时间，某些情况还会导致第一次进战斗卡顿一下"
L["COMMON_ADDONPROFILER"] = "隐藏插件列表CPU占用分析"
L["COMMON_ADDONPROFILERTISP"] = "该选项只是隐藏了插件列表的CPU占用分析功能"
L["COMMON_ADVANCEDCOMBATTISP"] = "更改过于频繁"
L["COMMON_COMBATSTART"] = "自动开始记录战斗日志";
L["COMMON_HIDEREDERROR"] = "隐藏红色错误提示";
L["COMMON_HIDEYELLOWINFO"] = "隐藏黄色警告提示";
L["COMMON_HIDEPIGLOAD"] = "隐藏插件载入提示";
L["COMMON_AFK"] = "离开屏保";
L["COMMON_AFKTISP"] = "暂离时自动进入屏保功能";
L["COMMON_AFKTISPTXT"] = "临时离开，勿动!!!";
L["INTERACT_TISP"] = "\r按住Shift停止自动接任务";
L["INTERACT_DIALOGUE"] = "自动对话";
L["INTERACT_DIALOGUETISP"] = "当NPC只有一个对话选项时自动激活选项\n对话选项>1请在下拉菜单设置默认对话选项"..L["INTERACT_TISP"];
L["INTERACT_DIALOGUEMULTI"] = "多选项选择"
L["INTERACT_QUEST"] = "自动接任务";
L["INTERACT_QUESTTISP"] = "和NPC对话时自动接任务"..L["INTERACT_TISP"];
L["INTERACT_QUESTEND"] = "自动交任务";
L["INTERACT_QUESTENDTISP"] = "和NPC对话时自动交任务"..L["INTERACT_TISP"];
L["INTERACT_STAND"] = "自动站立";
L["INTERACT_STANDTISP"] = "与NPC或物体交互时自动站立";
L["INTERACT_INVITE"] = "自动接受组队邀请";
L["INTERACT_REQUEST"] = "自动接受复活";
L["INTERACT_AUTOREPAIR"] = "自动修理";
L["INTERACT_AUTOREPAIRTISP"] = "与修理商人对话时自动修理身上和背包物品";
L["INTERACT_AUTOREPAIRGUILD"] = "优先使用公会资金";
L["INTERACT_RIGHTMENU"] = "增强交互右键菜单";
L["INTERACT_RIGHTMENUERR"] = "注意此功能复制的姓名不可作为/tar目标";
L["INTERACT_RIGHTMENUDOWN"] = "下移增强菜单";
--商业
L["TRADE_TABNAME"] = "贸易";
--
L["TRADEAH_TABNAME"] = "拍卖助手"
L["TRADEAH_TISP"] = "增强拍卖行界面"
L["TRADEAH_SCANCD"] = "扫描间隔%d"
L["TRADEAH_SCANITEM"] = "正在扫描物品..."
L["TRADEAH_SCANITEMG"] = "正在获取价格..."
L["TRADEAH_OPENBAG"] = "拍卖时打开背包"
L["TRADEAH_MOUSETISPG"] = "鼠标提示拍卖缓存价钱"
L["TRADEAH_MOUSERIGHT"] = "鼠标右键快速拍卖"
L["TRADEAH_SKILLNOOFF"] = "拍卖行打开时禁止专业面板关闭"
L["TRADEAH_CACHEG"] = "缓存价格"
L["TRADEAH_CACHEGTISP"] = "1、缓存价格以后才能显示涨跌百分比\n2、100%表示当前价格和最后次缓存价格一样\n3、80%表示当前价格是最后次缓存价格80%(即便宜了20%)\n4、120%表示当前价格是最后次缓存价格120%(即贵了20%)"
L["TRADEAH_CACHEGEND"] = "价格缓存完毕"
L["TRADEAH_TICLOGMODE"] = "防卡模式"
L["TRADEAH_TICLOGMODETISP"] = "如果拍卖行买卖CD很长，请开启此模式"
L["TRADEAH_TICLOGMODETISP1"] = "当前处于%s,手动复制粘贴搜索"
L["TRADEAH_TICLOGMODETISP2"] = "|cffFFFF00自动查价失败\n当前处于防卡模式\n按住Shift左键点击右侧物品→|r\n|cffFF0000(注意不是点击背包物品)|r"
L["TRADEAH_BUY"] = "买"
L["TRADEAH_FASTBUY"] = "快速购买"
L["TRADEAH_FASTBUYTISP"] = "开启后每行会增加一个购买按钮，点击后会直接购买\n已做保护，非一口单价从低到高排序将不会显示此按钮，\n|cffFF0000注意此操作存在风险，开启此功能视为你了解此风险|r"
L["TRADEAH_PRICETREND"] = "价格走势"
L["TRADEAH_FOCUSBAG"] = "关注/背包物品"
L["TRADEAH_FOCUS"] = "关注"
L["TRADEAH_FOCUSTISP"] = "\124cff00ff001、在浏览列表右键点击物品名可加入关注。\n2、关注列表物品左键点击搜索，右键点击删除。\124r"
L["TRADEAH_SHOPLIST"] = "清单"
L["TRADEAH_SHOPLIST1"] = "购物清单"
L["TRADEAH_UNDERCUT"] = "压价"
L["TRADEAH_UNDERCUTTISP"] = "选中后拍卖物品时将根据现售最低价自动压价"
L["TRADEAH_BIDG"] = "压竞标价"
L["TRADEAH_BIDGTISP"] = "压一口价同时压竞标价"
L["TRADEAH_SAVEPRICE"] = "记住拍卖价格"
L["TRADEAH_SAVEPRICETISP"] = "本次卖出相同物品使用前一次设置拍卖价格,而不是压已有的最低价。\n(只在本次打开拍卖界面期间生效)"
L["TRADEAH_SAVEPRICETISP1"] = "使用上次拍卖价格，本次不搜索"
L["TRADEAH_SAVETIME"] = "记住拍卖时间"
L["TRADEAH_STACKSIZE"] = "默认起拍堆叠"
L["TRADEAH_UNDERCUTERR1"] = "浏览页请翻到第一页"
L["TRADEAH_UNDERCUTERR2"] = "没有参考价"
L["TRADEAH_BAGTISP1"] ="右键点击查询)"
L["TRADEAH_BAGTISP2"] ="按住Shift左键点击"
--
L["TRADEMAIL_TABNAME"] = "邮箱助手"
L["TRADEMAIL_TABNAMETISP"] = "增强你的邮箱界面，方便你查看邮箱物品/发送邮件"
L["TRADEMAIL_PICKCD"] = "批量取件间隔%.2f/s"
L["TRADEMAIL_CLEAR"] = "此操作将|cffff0000清理所有不包含附件(已读)|r的邮件。\n确定清理吗?"
L["TRADEMAIL_TISP1"] = "|cff00FF00剩:|r"
L["TRADEMAIL_TISP2"] = "发件时保持背包开启"
L["TRADEMAIL_TISP2"] = "连寄"
L["TRADEMAIL_TISP21"] = "发件箱未关闭情况下会自动填入上一次收件人"
L["TRADEMAIL_TISP3"] = "自动标题"
L["TRADEMAIL_TISP31"] = "邮寄金币时自动填入标题"
L["TRADEMAIL_TISP4"] = "快速邮寄"
L["TRADEMAIL_TISP41"] = "左键批量选择/右键单选\n选择时按住ALT则快速邮寄"
L["TRADEMAIL_TISP5"] = "清空已选"
L["TRADEMAIL_ERROR1"] = "|cffFF0000退回邮件，到期将被删除|r"
L["TRADEMAIL_CONTACTS1"] = "本人"
L["TRADEMAIL_CONTACTS1TISP"] = "本人的其他角色\n"
L["TRADEMAIL_CONTACTS2TISP"] = "你的游戏好友"
L["TRADEMAIL_CONTACTS3"] = "最近"
L["TRADEMAIL_CONTACTS3TISP"] = "最近联系人\n"..KEY_BUTTON1..":选择发件人\n"..KEY_BUTTON2..":删除"
--
L["TRADESELLBUY_TABNAME"] = "售卖助手"
L["TRADESELLBUY_TISP"] = "一键丢弃/自动卖出/自动购买/快捷开启使用/快捷分解/快捷选矿/快捷存取银行物品"
L["TRADESELLBUY_TISP1"] = "在聊天栏显示%s记录"
L["TRADESELLBUY_TISP2"] = KEY_BUTTON1..": %s清单物品\n"..KEY_BUTTON2..": 设置%s清单"
L["TRADESELLBUY_TISP3"] = "在商人界面增加一个%s按钮\n"..L["TRADESELLBUY_TISP2"]
L["TRADESELLBUY_TISP4"] = "%s目录为空"
L["TRADESELLBUY_TISP5"] = KEY_BUTTON1.."-|cff00FFFF%s指定物品|r\n"..KEY_BUTTON2.."-|cff00FFFF打开%s|r"
L["TRADESELLBUY_TISP6"] = "没有需%s物品"
L["TRADESELLBUY_TISP7"] = "你尚未学会%s技能"
L["TRADESELLBUY_TISP8"] = "|cff00FFFF该设置为角色独享|r"
L["TRADESELLBUY_ERROR1"] = "物品已在排除列表"
L["TRADESELLBUY_ERROR2"] = "物品已在%s列表"
L["TRADESELLBUY_ERROR3"] = "排除列表只支持灰色物品"
L["TRADESELLBUY_ERROR4"] = "非消耗品"
L["TRADESELLBUY_ERROR5"] = "高品质物品，无法一键丢弃"
L["TRADESELLBUY_ERROR6"] = "物品无法开启/使用"
L["TRADESELLBUY_ERROR7"] = "无法选矿"
L["TRADESELLBUY_TITLE1"] = "\124cff00FF00↓%s列表↓\124r"
L["TRADESELLBUY_EXCLUDE"] = "排除"
L["TRADESELLBUY_EXCLUDE1"] = "排除物品"
L["TRADESELLBUY_EXCLUDE2"] = "下方列表|c%s灰色|r物品将不会被自动卖出"
L["TRADESELLBUY_ADDALL"] = "全部添加"
L["TRADESELLBUY_SELL1"] = "售"
L["TRADESELLBUY_SELL2"] = "出售"
L["TRADESELLBUY_SELL3"] = "|cFF7FFFAA本次%s件获得:|r "
L["TRADESELLBUY_SELL4"] = "打开商人界面自动%s灰色物品和下方列表内的物品"
L["TRADESELLBUY_BUY1"] = "购"
L["TRADESELLBUY_BUY2"] = "购买"
L["TRADESELLBUY_BUY3"] = "打开商人界面自动%s下方列表物品"
L["TRADESELLBUY_BUY4"] = "职业共享"
L["TRADESELLBUY_BUY4-1"] = "购买列表设置为职业共享|cff00FFFF(默认为分角色保存)|r"
L["TRADESELLBUY_BUY5"] = "|cFF00ff00补货%s:|r %s |cFF00ff00数量:|r%s|cFF00ff00花费:|r%s"
L["TRADESELLBUY_BUY5-1"] = "(限量)"
L["TRADESELLBUY_DROP1"] = "丢"
L["TRADESELLBUY_DROP2"] = "丢弃"
L["TRADESELLBUY_DROP3"] = "复制%s指令"
L["TRADESELLBUY_DROP4"] = "因暴雪API改动，无法自动%s/一次%s多个物品。\n可以复制此指令到已有的宏尾部。这样在使用宏时将执行一次动作"
L["TRADESELLBUY_OPEN1"] = "开"
L["TRADESELLBUY_OPEN2"] = "开启"
L["TRADESELLBUY_FEN1"] = "分"
L["TRADESELLBUY_FEN2"] = "分解"
L["TRADESELLBUY_XUAN1"] = "选"
L["TRADESELLBUY_XUAN2"] = "选矿"
L["TRADESELLBUY_SAVE1"] = "存"
L["TRADESELLBUY_SAVE2"] = "存储"
L["TRADESELLBUY_SAVE3"] = "最大存放金额"
L["TRADESELLBUY_SAVE4"] = KEY_BUTTON1..": \124cff00FF00存储%s\124r\n"..KEY_BUTTON2..": \124cff00FF00取出%s\124r"
L["TRADESELLBUY_SAVE6"] = L["TRADESELLBUY_SAVE4"].."\nShift+"..KEY_BUTTON1.."-\124cff00FFFF设置存储%s物品\124r\n".."SHIFT+"..KEY_BUTTON2.."-\124cff00FFFF设置取出%s物品\124r"
L["TRADESELLBUY_TAKE1"] = "取"
L["TRADESELLBUY_TAKE2"] = "取出"
L["TRADESELLBUY_TAKE3"] = "最大提取金额"
L["TRADESELLBUY_TAKE4"] = L["TRADESELLBUY_SAVE4"].."\nShift+"..KEY_BUTTON1.."-\124cff00FFFF设置存储%s数量\124r\n".."SHIFT+"..KEY_BUTTON2.."-\124cff00FFFF设置取出%s数量\124r"
--
L["TRADECHARDATA_TABNAME"] = "角色数据"

--Chat
L["CHAT_TABNAME"] = "聊天";
L["CHAT_FILTERS"] = "过滤";
L["CHAT_FILTERSTAB"] = "过\n滤";
L["CHAT_WHISPER"] = "密语";
L["CHAT_KEYWORD"] = "关键字";
L["CHAT_KEYWORD_TI_1"] = "  用，分隔";
L["CHAT_KEYWORD_TI"] = "输入"..L["CHAT_KEYWORD"]..L["CHAT_KEYWORD_TI_1"];
L["CHAT_BLACK_NAME"] = "黑名单";
L["CHAT_BLACK_SET0"] = {"高频发言","短时间高频发言后续发言会被过滤"}
L["CHAT_BLACK_SET1"] = {"重复发言","过滤%d分钟之内的重复发言(不过滤自身发言)"}
L["CHAT_BLACK_EITB"] = L["CHAT_KEYWORD"]..L["CHAT_KEYWORD_TI_1"].."\nAA：屏蔽包含AA的信息\nAA#BB：屏蔽同时包含AA和BB的信息"
L["CHAT_KEYWORD_NAME"] = "关注";
L["CHAT_KEYWORD_NAME1"] = "提取";
L["CHAT_KEYWORD_NAMETAB"] = "提\n取";
L["CHAT_KEYWORD_NAME2"] = L["CHAT_KEYWORD"]..L["CHAT_KEYWORD_TI_1"].."\nAA：提取包含AA的内容\nAA#BB：提取同时包含AA和BB的内容\nAA&CC：提取包含AA但不包含CC的内容"
L["CHAT_KEYWORD_SET1"] = "提示音";
L["CHAT_KEYWORD_SET2"] = "输出到聊天窗口";
L["CHAT_DAOSHU"] = "开怪倒数";
L["CHAT_JILUTIME"]={"一周","一月","半年","一年"}
L["CHAT_JILUTISHI"]="点击上方频道标签浏览聊天记录";
L["CHAT_JILUTDEL"]="确定要清空%s聊天记录吗？";
L["CHAT_WHISPERTIXING"]="新"..L["CHAT_WHISPER"].."图标提醒"
L["CHAT_WHISPERTIXINGTOP"]="收到"..L["CHAT_WHISPER"].."时图标会闪动"
L["CHAT_WHISPERAUDIO"]="新"..L["CHAT_WHISPER"].."提示音"
L["CHAT_WHISPERAUDIOTOP"]="收到"..L["CHAT_WHISPER"].."时会播放指定提示音"
L["CHAT_TABNAME1"] = GENERAL;
L["CHAT_QUKBUT"] = "快捷切换频道按钮";
L["CHAT_QUKBUTTIPS"]="在聊天栏增加一排频道快捷切换按钮，可快速切换频道"
L["CHAT_QUKBUTNAME"] = {"说","喊","队","会","团","通","战","综","交","组","世"};
L["CHAT_JXNAME"] = {"长","领","导"};
if tocversion>30000 then L["CHAT_QUKBUTNAME"][7]="副" end
L["CHAT_BENDIFUWU"] = "服务";
L["CHAT_BENDIFANGWU"] = "本地防务";
L["CHAT_WORLDFANGWU"] = "世界防务";
L["CHAT_QUKBUT_UP"] = "附着于聊天栏上方";
L["CHAT_QUKBUT_DOWN"] = "附着于聊天栏下方";
L["CHAT_QUKBUT_STYLE"]= "样式";
L["CHAT_MINMAXB"]= "显示放大缩小字体按钮";
L["CHAT_MINMAXBTIPS"]= "在聊天栏右上方添加放大缩小字体按钮";
L["CHAT_ALTEX"]= "免ALT键移动光标/查看输入记录";
L["CHAT_ALTEXTIPS"]= "无需按住ALT键即可移动光标，上下翻看输入记录，左右移动光标";
L["CHAT_JIANYIN"]= "关闭聊天栏文字渐隐"
L["CHAT_JIANYINTIPS"]= "移除聊天栏文字渐隐效果";
L["CHAT_LINKSHOW"]= "鼠标指向链接直接预览物品属性";
L["CHAT_ZHIXIANGSHOWTIPS"]= "鼠标指向聊天栏物品链接直接显示属性框，正常需要点击链接";
L["CHAT_CLASSCOLOR"]= "聊天栏显示职业颜色";
L["CHAT_JINGJIAN"]= "精简频道名";
L["CHAT_JINGJIANTIPS"]= L["CHAT_JINGJIAN"].."例：["..LOOK_FOR_GROUP.."]→[组]";
L["CHAT_JOINPIG"]= "自动加入"..LOOK_FOR_GROUP.."/PIG频道"
L["CHAT_JOINPIGTIPS"]= "进入游戏后自动加入"..LOOK_FOR_GROUP.."/PIG频道";
L["CHAT_FONTSIZE"]= "自动设置聊天框字体:"
L["CHAT_FONTSIZETIPS"]= "开启后将在每次登录时恢复聊天框字体大小为设置值，如果想自定义单独聊天框窗字体大小请关闭此选项。"
L["CHAT_DAORUQITASET"]= "导入其他角色聊天设置";
L["CHAT_DAYINZIDINGYI"]= "打印自定义频道所有者";
L["CHAT_TABNAME2"] = "TAB切换频道";
L["CHAT_TABNAME2TIPS"] = L["CHAT_TABNAME2"].."|cff00ff00(激活输入框时会在下方选中的频道之间切换)|r";
L["CHAT_BN_WHISPER"] = "战网"..L["CHAT_WHISPER"]
L["CHAT_TABCKBTIPS"] ="勾选以后TAB键将可以切换到【%s】频道"
L["CHAT_TABNAME3"] = "频道粘连";
L["CHAT_TABNAME3TIPS"] ="粘连回车|cff00ff00(取消粘连回车的频道，发言后回车不会返回此频道)|r";
L["CHAT_ZLCKBTIPS"] ="勾选粘连【%s】频道到回车，取消勾选解除粘连";
L["CHAT_RECHATBUT"]= "重置聊天"..L["OPTUI_SET"];
L["CHAT_TABNAME5"] = "频道顺序";
L["CHAT_TABNAME5_XULIE"] = "序列";
L["CHAT_MARGIN"]= "修改系统聊天窗口的边距限制"
L["CHAT_MARGINTIPS"]= "修改系统聊天窗口的边距限制，使之突破移动边距限制";
L["CHAT_ZHUNAME"]= "主聊天窗口";
L["CHAT_ZHUCHATF"]= L["OPTUI_SET"]..L["CHAT_ZHUNAME"]..L["LIB_POINT"]..L["LIB_SIZE"].."\124cff00ff00(边距受系统限制，可在上方解除系统限制)\124r";
L["CHAT_LOOTNAME"]= "右边独立聊天窗口";
L["CHAT_LOOTCHATF"]= L["OPTUI_SET"]..L["CHAT_LOOTNAME"]..L["LIB_POINT"]..L["LIB_SIZE"];
L["CHAT_LOOTFADD"]= "创建"..L["CHAT_LOOTNAME"];
L["CHAT_LOOTFYES"]= "已创建"..L["CHAT_LOOTNAME"];
L["CHAT_LOOTABNAME"]="拾取/其他";
L["CHAT_LOOTFTIPS"]="\124cffffff00在屏幕右下角创建一个独立聊天窗口(显示额外信息)\124r\n\124cff00ff00下方选项在创建独立拾取窗口后方可启用\n不需要独立拾取窗口时请手动移除\124r";
L["CHAT_LOOTFNRSET"]="重设分配聊天窗口显示内容";
L["CHAT_LOOTFNRSETTIPS"]="启用独立拾取窗口后，建议打开此选项。\n重新设置窗口显示内容，综合频道将取消经验荣誉以及拾取信息的显示，拾取窗口添加拾取/经验/荣誉等的显示！\n修改战斗记录为记录以便缩短标签页长度。";
L["CHAT_LOOTFADDERR1"]="创建失败！当前屏幕分辨率过小";
L["CHAT_LOOTFADDERR2"]="创建失败！系统允许做大聊天窗口数：10，当前："..FCF_GetNumActiveChatFrames();
--动作条
L["ACTION_TABNAME"] = ACTIONBARS_LABEL;
L["ACTION_TABNAME1"] = GENERAL;
L["ACTION_TABNAME2"] = "功能动作条";
L["ACTION_ADDQUICKBUT"] = "添加到功能动作条";
L["ACTION_ADDQUICKBUTTIS"] = "<%s>添加到功能动作条,以便快速使用。\n|cffFF0000注意：此功能需先在<"..L["ACTION_TABNAME"]..">菜单打开<"..L["ACTION_TABNAME2"]..">|r";
L["ACTION_TABNAME3"] = L["LIB_PLUS"]..ACTIONBARS_LABEL;
--背包
L["BAGBANK_TABNAME"] = "背包/银行";
--界面优化
L["FRAMEP_TABNAME"] = "暴雪界面增强";
L["FRAMEP_TABNAME2"] = "界面扩展";
--鼠标提示
L["TOOLTIP_TABNAME"] = MOUSE_LABEL..L["LIB_TIPS"];
L["TOOLTIP_TABNAME1"] = L["LIB_PLUS"]..INFO;
L["TOOLTIP_TABNAME1"] = L["LIB_PLUS"]..INFO;
--头像框架
L["UNIT_TABNAME"] = "头像框架";
L["UNIT_TABNAME1"] = "自身头像";
L["UNIT_TABNAME2"] = "队友头像";
L["UNIT_TABNAME3"] = "目标头像";
--战斗辅助
L["COMBAT_TABNAME"] = "战斗辅助";
L["COMBAT_TABNAME1"] = "标记按钮";
L["COMBAT_TABNAME2"] = "战斗时间";
L["COMBAT_TABNAME3"] = "个人资源条";
L["COMBAT_TABNAME4"] = "新手保姆";
--地图
L["MAP_TABNAME"] = "地图";
L["MAP_TABNAME1"] = "小地图";
L["MAP_NIMIBUT"] = "显示本插件小地图按钮";
L["MAP_NIMIBUTTIPS"] = "显示插件的小地图按钮";
L["MAP_NIMIBUT_BS"] = "允许被收纳";
L["MAP_NIMIBUT_BSTIPS"] = "开启后小地图按钮将可以被其他插件收纳。|cffFF0000(注意和下方收纳小地图按钮功能只能选一)|r";
L["MAP_NIMIBUT_SN"] = "收纳其他插件小地图按钮";
L["MAP_NIMIBUT_SNTIPS"] = "开启后将收纳其他插件的小地图按钮到单独界面，"..KEY_BUTTON1.."点击本插件小地图按钮可查看已收纳按钮！|cffFF0000(注意和上方允许被收纳只能选一)|r";
L["MAP_NIMIBUT_HANGNUM"]="每行按钮数:"
L["MAP_NIMIBUT_NOSN"]="点击按钮切换收纳与否"
L["MAP_NIMIBUT_TIPS1"]=KEY_BUTTON1.."-|cff00FFFF展开小地图按钮|r\r"..KEY_BUTTON2.."-|cff00FFFF设置|r\rShift+"..KEY_BUTTON1.."-|cff00FFFF重载界面|r\rCtrl+"..KEY_BUTTON1.."-|cff00FFFF打开错误日志|r"
L["MAP_NIMIBUT_TIPS2"]=KEY_BUTTON1.."-|cff00FFFF设置|r\rShift+"..KEY_BUTTON1.."-|cff00FFFF重载界面|r\rCtrl+"..KEY_BUTTON1.."-|cff00FFFF打开错误日志|r"
L["MAP_NIMIBUT_TIPS3"]="|cff00FF00此界面收纳其他插件小地图按钮\r|r|cff00FFFF如需关闭: "..KEY_BUTTON2.."设置-地图|r"
L["MAP_TABNAME2"] = "世界地图";
L["MAP_WORDXY"] = "显示玩家坐标";
L["MAP_WORDXYTIPS"] = "显示玩家在地图坐标";
L["MAP_WORDWIND"] = "窗口化世界地图";
L["MAP_WORDWINDTIPS"] = "窗口化世界地图";
L["MAP_WORDLV"] = "显示等级范围";
L["MAP_WORDLVTIPS"] = "显示地图的等级范围";
L["MAP_WORDSKILL"] = tocversion<40000 and "显示钓鱼技能要求" or "显示宠物等级范围";
L["MAP_WORDSKILLTIPS"] = tocversion<40000 and "显示地图的钓鱼技能最低要求" or "显示地图的宠物等级范围";
L["MAP_WORDMIWU"] = "去除战争迷雾";
L["MAP_WORDMIWUTIPS"] = "去除地图战争迷雾";
--Cvar
L["CVAR_TABNAME"] = "游戏设置(CVar)";
L["CVAR_TABNAME0"] = "易用性";
L["CVAR_TABNAME1"] = GENERAL;
L["CVAR_TABNAME2"] = "姓名版";
L["CVAR_TABNAME3"] = "自身高亮";
L["CVAR_TABNAME4"] = "高级";
----
L["EXT_TOJOIN"] = ",进组暗号%s"
--Invite
L["TARDIS_TABNAME"] = "汇合石";
L["TARDIS_CHEDUI"] = "车队";
L["TARDIS_CHEDUI_1"] = "找车队";
L["TARDIS_CHEDUI_2"] = "找乘客";
L["TARDIS_FARM"] = "坐车";
L["TARDIS_PLANE"] = "位面";
L["TARDIS_YELL"] = "喊话";
L["TARDIS_RECEIVEDATA"] = "正在接收数据...";
L["TARDIS_LFG_JOIN"] = "加入PIG频道";
L["TARDIS_LFG_LEAVE"] = "已加入PIG频道"