local AddOnFolderName = ...
local L = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName, "esMX")
if not L then return end

L["%1$s (%2$d) is already on the user-defined NPC list."] = "%1$s (%2$d) ya está en la lista de PNJs definidos por el usuario."
L["%1$s (%2$d) is not on the user-defined NPC list."] = "%1$s (%2$d) no está en la lista de NPC definidos por el usuario."
L["Added %1$s (%2$d) to the user-defined NPC list."] = "Se agregó %1$s (%2$d) a la lista de PNJs definidos por el usuario."
L["Alerts"] = "Alertas"
L["BOTTOM"] = "Inferior"
L["BOTTOMLEFT"] = "Inferior izquierdo"
L["BOTTOMRIGHT"] = "Inferior derecho"
L["CENTER"] = "Centro"
L["Completed Achievement Criteria"] = "Criterios de logro completados"
L["Completed Quest Objectives"] = "Objetivos de misión completados"
L["Dead NPCs"] = "PNJs muertos"
L["Detection"] = "Detección"
L["Drag to set the spawn point for targeting buttons."] = "Arrastre para fijar el punto de aparición del botón de objetivo."
L["Duration"] = "Duración"
L["Hide Anchor"] = "Ocultar anclaje"
L["Hide During Combat"] = "Ocultar durante combate"
L["Horizontal offset from the anchor point."] = "Desplazamiento horizontal desde el punto de anclaje."
L["Ignore Mute"] = "Ignorar silencio"
L["Interval"] = "Intervalo"
L["LEFT"] = "Izquierda"
L["NPCs"] = "PNJs"
L["Play alert sounds when sound is muted."] = "Reproduce sonidos de alerta cuando el sonido esta silenciado."
--[[Translation missing --]]
--[[ L["Predefined NPCs cannot be added to the user-defined NPC list."] = "Predefined NPCs cannot be added to the user-defined NPC list."--]] 
L["Removed %1$s (%2$d) from the user-defined NPC list."] = "Se eliminó %1$s (%2$d) de la lista de PNJs definidos por el usuario."
L["Reset Position"] = "Restablecer posición"
L["RIGHT"] = "Derecha"
L["Screen Flash"] = "Destello de pantalla"
L["Screen Location"] = "Pantalla de localización"
L["Show Anchor"] = "Mostrar anclaje"
L["Spawn Point"] = "Punto de aparicion"
L["The number of minutes a targeting button will exist before fading out."] = "El número de minutos que el botón de objetivo estará antes de desvanecerse."
L["The number of minutes before an NPC will be detected again."] = "El número de minutos antes de que un PNJ sea detectado de nuevo."
L["TOP"] = "Superior"
L["TOPLEFT"] = "Superior izquierdo"
L["TOPRIGHT"] = "Superior derecho"
L["Type the name of a Continent, Dungeon, or Zone, or the partial name of an NPC. Accepts Lua patterns."] = "Escribe el nombre de un continente, mazmorra o zona, o el nombre parcial de un PNJ. Acepta patrones de Lua."
L["Valid values are a numeric NPC ID, the word \"mouseover\" while you have your mouse cursor over an NPC, or the word \"target\" while you have an NPC set as your target."] = "Los valores válidos son un ID de PNJ numérico, la palabra \"pasar el mouse\" mientras tiene el cursor del mouse sobre un PNJ, o la palabra \"objetivo\" mientras tiene un PNJ establecido como su objetivo."
L["Vertical offset from the anchor point."] = "Desplazamiento vertical desde el punto de anclaje."
L["X Offset"] = "Desplazamiento X"
L["Y Offset"] = "Desplazamiento Y"

