local HandyNotes_Draenor = LibStub("AceAddon-3.0"):GetAddon("HandyNotes_Draenor")

if ((C_QuestLog.IsQuestFlaggedCompleted(36386) == false) or (C_QuestLog.IsQuestFlaggedCompleted(36390) == false) or (C_QuestLog.IsQuestFlaggedCompleted(36389) == false) or (C_QuestLog.IsQuestFlaggedCompleted(36392) == false) or (C_QuestLog.IsQuestFlaggedCompleted(36388) == false) or (C_QuestLog.IsQuestFlaggedCompleted(36381) == false)) then
    HandyNotes_Draenor.nodes["SpiresOfArak"][43901500] = { "SpiresOfArak", "36395", "Elixir of Shadow Sight 1", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
    HandyNotes_Draenor.nodes["SpiresOfArak"][43802470] = { "SpiresOfArak", "36397", "Elixir of Shadow Sight 2", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
    HandyNotes_Draenor.nodes["SpiresOfArak"][69204330] = { "SpiresOfArak", "36398", "Elixir of Shadow Sight 3", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
    HandyNotes_Draenor.nodes["SpiresOfArak"][48906250] = { "SpiresOfArak", "36399", "Elixir of Shadow Sight 4", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
    HandyNotes_Draenor.nodes["SpiresOfArak"][55602200] = { "SpiresOfArak", "36400", "Elixir of Shadow Sight 5", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
    HandyNotes_Draenor.nodes["SpiresOfArak"][53108450] = { "SpiresOfArak", "36401", "Elixir of Shadow Sight 6", "Elixir of Shadow Sight", "Elixir can be used at Shrine of Terrok for 1 of 6 i585 Weapons (see Gift of Anzu) Object will be removed as soon as you loot all Gifts of Anzu", "Icon_Treasure_Default", "Treasure", "115463" }
end