----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "zhCN" then
    return
end

local L = BtWQuests.L
L["ALLIED_RACE_MECHAGNOME"] = "Allied Race：机械侏儒"
L["ALLIED_RACE_VULPERA"] = "Allied Race：狐人"
L["BTWQUESTS_BEGIN_THE_BATTLE_FOR_BRENNADAM"] = "开启布伦纳丹之战"
L["BTWQUESTS_COSMETIC_WAIST_OF_TIME"] = "装饰品：钟示贤德腰带"
L["BTWQUESTS_GIFT_OF_NZOTH"] = "恩佐斯的礼物"
L["BTWQUESTS_GIFT_OF_NZOTH_BREADCRUMB"] = "世界任务 击退娜迦的入侵!"
L["BTWQUESTS_HATI_REBORN"] = "哈提的重生"
L["BTWQUESTS_HERITAGE_OF_GILNEAS"] = "吉尔尼斯的传承"
L["BTWQUESTS_HERITAGE_OF_GNOMEREGAN"] = "诺莫瑞根的传承"
L["BTWQUESTS_HERITAGE_OF_KEZAN"] = "科赞的传承"
L["BTWQUESTS_HERITAGE_OF_THE_BRONZEBEARD"] = "铜须的传承"
L["BTWQUESTS_HERITAGE_OF_THE_SHUHALO"] = "舒哈鲁的传承"
L["BTWQUESTS_HERITAGE_OF_THE_SINDOREI"] = "辛多雷的传承"
L["BTWQUESTS_MAGHAR_ORC"] = "玛格汉兽人"
L["BTWQUESTS_MAJO_AND_JOMA"] = "玛乔和乔玛"
L["BTWQUESTS_NIGHT_WARRIOR_NIGHT_ELF_CUSTOMIZATION"] = "“月夜战神”暗夜精灵自定义选项"
L["BTWQUESTS_PROGRESS_THE_WAR_CAMPAIGN"] = "阵营战役进度"
L["BTWQUESTS_THE_WAR_CAMPAIGN"] = "阵营战役"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1"] = "阵营战役: 达萨罗之战"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1_5"] = "阵营战役:风暴熔炉"
L["BTWQUESTS_WARFRONT_THE_BATTLE_FOR_DARKSHORE"] = "战争前线：黑海岸之战"
L["DUNGEON_KINGS_REST"] = "地下城：诸王之眠"
L["DUNGEON_SIEGE_OF_BORALUS"] = "地下城：围攻伯拉勒斯"
L["MECHAGNOME"] = "机械侏儒"
L["VULPERA"] = "狐人"
L["WAIST_OF_TIME"] = "钟示贤德腰带"
