BTWQUESTS_CHAIN_BATTLE_FOR_AZEROTH_PROLOGUE = 80000
BTWQUESTS_CHAIN_BATTLE_FOR_AZEROTH_PROLOGUE_ALLIANCE = 80001
BTWQUESTS_CHAIN_BATTLE_FOR_AZEROTH_PROLOGUE_HORDE = 80002

BtWQuestsDatabase:AddExpansion(BTWQUESTS_EXPANSION_BATTLE_FOR_AZEROTH, {
    background = {
        atlas = "UI-EJ-BattleforAzeroth"
    }
})