----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "deDE" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_ACTIVE"] = "Aktiv"
L["BTWQUESTS_ALLIED_RACES"] = "Verbündete Völker"
L["BTWQUESTS_AVAILABLE"] = "Verfügbar"
L["BTWQUESTS_COMPLETED"] = "Abgeschlossen"
L["BTWQUESTS_COSMETIC"] = "Kosmetisch"
L["BTWQUESTS_FACTION"] = "Fraktion"
L["BTWQUESTS_IGNORED"] = "Ignoriert"
L["BTWQUESTS_LEVEL"] = "Stufe %d"
L["BTWQUESTS_MOUNT"] = "Aufsitzen"
L["BTWQUESTS_PET"] = "Begleiter"
L["BTWQUESTS_PROFESSIONS"] = "Berufe"
L["BTWQUESTS_PROFESSION_ALCHEMY"] = "Alchemie"
L["BTWQUESTS_PROFESSION_BLACKSMITHING"] = "Schmiedekunst"
L["BTWQUESTS_PROFESSION_ENCHANTING"] = "Verzauberkunst"
L["BTWQUESTS_PROFESSION_ENGINEERING"] = "Ingenieurskunst"
L["BTWQUESTS_PROFESSION_FIRST_AID"] = "Erste Hilfe"
L["BTWQUESTS_PROFESSION_FISHING"] = "Angeln"
L["BTWQUESTS_PROFESSION_HERBALISM"] = "Kräuterkunde"
L["BTWQUESTS_PROFESSION_INSCRIPTION"] = "Inschriftenkunde"
L["BTWQUESTS_PROFESSION_JEWELCRAFTING"] = "Juwelierskunst"
L["BTWQUESTS_PROFESSION_LEATHERWORKING"] = "Lederverarbeitung"
L["BTWQUESTS_PROFESSION_MINING"] = "Bergbau"
L["BTWQUESTS_PROFESSION_SKINNING"] = "Kürschnerei"
L["BTWQUESTS_PROFESSION_TAILORING"] = "Schneiderei"
L["BTWQUESTS_TOY"] = "Spielzeug"
L["BTWQUESTS_WORLD_QUESTS"] = "Weltquests"
L["OTHER"] = "Anderes"
L["UNKNOWN"] = "Unbekannt"
