----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "frFR" then
    return
end

local L = BtWQuests.L
L["BTWQUESTS_ACTIVE"] = "Actif"
L["BTWQUESTS_ALLIED_RACES"] = "Races alliées"
L["BTWQUESTS_AVAILABLE"] = "Disponible"
L["BTWQUESTS_COMPLETED"] = "Achevé"
L["BTWQUESTS_COSMETIC"] = "Ornemental"
L["BTWQUESTS_COUNTDOWN_HMS"] = "% heures, %d minutes et %s secondes"
L["BTWQUESTS_COUNTDOWN_MS"] = "%d minutes et %s secondes"
L["BTWQUESTS_COUNTDOWN_S"] = "%d secondes"
L["BTWQUESTS_EPILOGUE"] = "Épilogue"
L["BTWQUESTS_EXPANSION_NAME0"] = "World of Warcraft"
L["BTWQUESTS_GO_TO"] = "Aller à %s"
L["BTWQUESTS_IGNORED"] = "Ignoré"
L["BTWQUESTS_KILL"] = "Tuer %s"
L["BTWQUESTS_LEVEL"] = "Niveau %d"
L["BTWQUESTS_MOUNT"] = "Monter"
L["BTWQUESTS_PET"] = "Familier"
L["BTWQUESTS_PREFIX"] = "%s : %s"
L["BTWQUESTS_PROFESSIONS"] = "Métiers"
L["BTWQUESTS_PROFESSION_ALCHEMY"] = "Alchimie"
L["BTWQUESTS_PROFESSION_BLACKSMITHING"] = "Forge"
L["BTWQUESTS_PROFESSION_ENCHANTING"] = "Enchantement"
L["BTWQUESTS_PROFESSION_ENGINEERING"] = "Ingénierie"
L["BTWQUESTS_PROFESSION_FIRST_AID"] = "Secourisme"
L["BTWQUESTS_PROFESSION_FISHING"] = "Pêche"
L["BTWQUESTS_PROFESSION_HERBALISM"] = "Herboristerie"
L["BTWQUESTS_PROFESSION_INSCRIPTION"] = "Calligraphie"
L["BTWQUESTS_PROFESSION_JEWELCRAFTING"] = "Joaillerie"
L["BTWQUESTS_PROFESSION_LEATHERWORKING"] = "Travail du cuir"
L["BTWQUESTS_PROFESSION_MINING"] = "Minage"
L["BTWQUESTS_PROFESSION_SKINNING"] = "Dépeçage"
L["BTWQUESTS_PROFESSION_TAILORING"] = "Couture"
L["BTWQUESTS_PROGRESS"] = "Progression %d sur %d"
L["BTWQUESTS_PROGRESS_SIDE"] = "Progression %d sur %d (%d sur %d)"
L["BTWQUESTS_QUEST_CHAIN_COMPLETED"] = "Vous avez terminé cette suite de quêtes"
L["BTWQUESTS_QUEST_JOURNAL"] = "Journal de Quête"
L["BTWQUESTS_REQUIREMENTS"] = "Prérequis %d/%d"
L["BTWQUESTS_REQUIREMENT_PROGRESS"] = "Progression prérequis"
L["BTWQUESTS_SKILL_LEVEL"] = "%s dans %s"
L["BTWQUESTS_TOOLTIP_PREREQUISITES"] = "Prérequis:"
L["BTWQUESTS_TOY"] = "Jouet"
L["BTWQUESTS_VIEW_ALL"] = "Tout Afficher"
L["BTWQUESTS_WORLD_QUESTS"] = "Expéditions"
L["OTHER"] = "Autre"
L["UNKNOWN"] = "Inconnu"
