local _,L = ...

if GetLocale()=="frFR" then

-- Main.lua
	L["Rematch"] = nil
	L["Toggle Window"] = "Basculer la fenêtre"
	L["Auto Load"] = "Chargement auto"
	L["Team Notes"] = "Notes d'équipe"
	L["Pets Tab"] = "Onglet de mascottes"
	L["Teams Tab"] = "Onglet d'équipes"
	L["Queue Tab"] = "Onglet de file"
	L["Toggle Rematch"] = "Basculer Rematch"
	L["Load this team?"] = "Charger cette équipe ?"
	L["They do not appear to be online."] = "Semble ne pas être en ligne."
	L["has also been added to your leveling queue!"] = "peut aussi être ajoutée à votre file de leveling !"
	L["The team named '%s' can't be found."] = "L'équipe '%s' ne peut être trouvée."
	L["Rematch Debug Info"] = "Infos de débogage Rematch"

-- Utils.lua
	L["Leveling Pet"] = "Mascotte de leveling"

-- Widgets\PetListButtons.lua
	L["Empty Battle Pet Slot"] = "Emplacement de combat vide"
	L["This pet can't level."] = "Cette mascotte ne peut monter de niveau."
	L["Only pets that can battle and are under 25 can go in the leveling queue."] = "Seules les mascottes pouvant combattre et d'un niveau inférieur à 25 peuvent être placées dans la file."

-- Widgets\Toolbar.lua
	L["Total Pets"] = "Totales"
	L["Unique Pets"] = "Uniques"
	L["Save As..."] = "Sauver sous..."
	L["Save the currently loaded pets to a new team."] = "Enregistre les mascottes actuellement chargées dans une nouvelle équipe."
	L["Save the currently loaded pets to the loaded team."] = "Enregistre les mascottes actuellement chargées dans l'équipe chargée."
	L["Dismiss Pet"] = "Renvoyer la mascotte"
	L["Summon Pet"] = "Invoquer la mascotte"
	L["Summons a random pet from your favorites."] = "Invoque une mascotte aléatoire depuis vos favoris."
	L["Random Favorite"] = "Favorite aléatoire"
	L["Random From All"] = "Aléatoire entre toutes"
	L["All pets are at full health."] = "Toutes les mascottes possèdent tous leurs points de vie."
	L["This treat's buff is already active."] = "Cette amélioration est déjà active."
	L["%s\n\nPets At Max Level: %s%d\124r\nPets Not Collected: %s%d\124r\n\n%s Click to display more about your collection."] = "%s\n\nMascottes au niveau max : %s%d\124r\nMascottes non collectées : %s%d\124r\n\n%s Cliquez pour en savoir plus sur votre collection."

-- Widgets\MinimapButton.lua
	L["Load Favorite Team"] = "Charger l'équipe favorite"
	L["Favorite Teams"] = "Équipes favorites"

-- Widgets\PanelTabs.lua

-- Process\PetLoading.lua
	L["You can't load a team during combat."] = "Vous ne pouvez pas charger une équipe pendant un combat."
	L["You can't load a team during a pet battle."] = "Vous ne pouvez pas charger une équipe pendant un combat de mascotte."
	L["You can't load a team in a matched pet battle."] = "Vous ne pouvez pas charger une équipe dans un combat de mascotte adapté."
	L["Loading..."] = "Chargement..."
	L["Pets are missing from this team!"] = "Mascottes absentes de cette équipe !"
	L["Substitutes were found. Please review the loaded team and click Save if you'd like to keep the chosen pets."] = "Des remplaçantes ont été trouvées. Merci de vérifier l'équipe chargée et de cliquer sur Enregistrer si vous souhaitez garder les mascottes choisies."
	L["Don't Warn About Missing Pets"] = "Ne pas m'alerter des mascottes manquantes"

-- Process\Roster.lua

-- Process\Filters.lua
	L["Favorites"] = "Favorites"
	L["Types"] = "Types"
	L["Strong Vs"] = "Fortes contre"
	L["Tough Vs"] = "Difficulté contre"
	L["Breed"] = "Race"
	L["Similar"] = "Similaire"
	L["Script"] = "Script"
	L["Level"] = "Niveau"
	L["Leveling"] = "En cours de leveling"
	L["Tradable"] = "Négociable"
	L["Battle"] = "Combat"
	L["Quantity"] = "Quantité"
	L["Team"] = "Équipe"
	L["Hidden"] = "Masquées"
	L["Zone"] = "Zone"
	L["Notes"] = "Notes"
	L["Search"] = "Rechercher"
	L["Sort"] = "Trier"
	L["Stats Search"] = "Statistiques de recherche"

-- Process\PetList.lua

-- Process\QueueProcess.lua
	L["Now leveling:"] = "En cours de leveling :"
	L["Rematch's leveling queue is empty"] = "La file de leveling Rematch est vide"
	L["All done leveling pets!"] = "Mascottes de leveling terminées !"

-- Process\Sanctuary.lua

-- Menus\Menu.lua
	L["Help"] = "Aide"

-- Menus\TeamMenus.lua
	L["Edit Win Record"] = "Modifier le nombre de victoire"
	L["Change Name Or Target"] = "Changer le nom ou la cible"
	L["Edit Team"] = "Modifier l'équipe"
	L["Set Notes"] = "Écrire une note"
	L["Leveling Preferences"] = "Préférences de leveling"
	L["Move To"] = "Déplacer vers"
	L["Move To Top"] = "Placer en haut"
	L["Move Up"] = "Monter"
	L["Move Down"] = "Descendre"
	L["Move To End"] = "Placer à la fin"
	L["Share"] = "Partager"
	L["Delete this team?"] = "Supprimer cette équipe ?"
	L["Unload Team"] = "Décharger l'équipe"
	L["Put Leveling Pet Here"] = "Définir comme emplacement de leveling"
	L["Add a leveling pet to this team?"] = "Ajouter une mascotte à cette équipe ?"
	L["About Teams"] = "À propos des équipes"
	L["Teams named in %sWhite\124r have a target stored within them.\nTeams named in Gold do not.\n\n%sTo change pets or abilities in a team:\124r\n1) Load the team.\n2) Make any changes.\n3) Click Save at the bottom of the window."] = "Les équipes écrites en %sBlanc\124r possèdent une cible stockée avec elles.\nLes équipes écrites en Jaune n'en ont pas.\n\n%sPour changer les mascottes ou les compétences d'une équipe : \124r\n1) Chargez l'équipe.\n2) Apportez vos modifications.\n3) Cliquez sur Enregistrer en bas de la fenêtre."
	L["Export As Plain Text"] = "Exporter en texte brut"
	L["Export this team in plain text that you can copy elsewhere, such as forums or emails.\n\nThe plain text format is best for sharing a team with others that may not use Rematch.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "Exporter cette équipe en texte brut que vous pouvez copier ailleurs, comme sur des forums ou des emails.\n\nLe format texte brut est meilleur pour partager une équipe avec d'autres personnes n'utilisant pas Rematch.\n\nLes autres utilisateurs de Rematch peuvent récupérer cette équipe dans leur Rematch via Importer une équipe."
	L["Export As String"] = "Exporter en tant que chaîne"
	L["Export this team as a string you can copy elsewhere, such as forums or emails.\n\nThe string format is best for copying multiple teams to be imported together, or for sharing teams with someone in another language.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "Exporter cette équipe sous forme de chaîne que vous pouvez copier ailleurs, comme sur des forums ou des emails.\n\nLe format chaîne est meilleur pour copier plusieurs équipes qui pourront être importer ensemble, ou pour partager des équipes avec quelqu'un utilisant une autre langue.\n\nLes autres utilisateurs de Rematch peuvent récupérer cette équipe dans leur Rematch via Importer une équipe."
	L["Import Team"] = "Importer une équipe"
	L["Import a single team or many teams that was exported from Rematch."] = "Importer une ou plusieurs équipes qui ont été exportées depuis Rematch."
	L["Send Team"] = "Partager l'équipe"
	L["Sharing is disabled in options."] = "Le partage est désactivé dans les options."
	L["Send this team to another online user of Rematch."] = "Envoyer cette équipe à un autre utilisateur de Rematch connecté."
	L["Prompt To Load"] = "Proposer de charger l'équipe"
	L["When your new target has a saved team not already loaded, and the target panel isn't on screen, display a popup asking if you want to load the team.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "Lorsque votre nouvelle cible possède une équipe enregistrée mais pas encore chargée, et que le panneau de cible n'est pas à l'écran, afficher une popup demandant si vous souhaitez charger l'équipe.\n\nAgit uniquement lors de la première interaction avec une cible. Vous pouvez toujours charger l'équipe associée à une cible depuis le panneau de cible."
	L["With Rematch Window"] = "Avec la fenêtre Rematch"
	L["Prompt to load with the Rematch window instead of a separate popup dialog."] = "Demander à charger l'équipe avec la fenêtre Rematch plutôt qu'une fenêtre de dialogue séparée."
	L["Always Prompt"] = "Toujours demander"
	L["Prompt every time you interact with a target with a saved team not already loaded, instead of only the first time."] = "Demander à chaque fois que vous interagissez avec une cible qui possède une équipe enregistrée mais pas encore chargée, au lieu de demander seulement la première fois."
	L["When you mouseover a new target that has a saved team not already loaded, immediately load it.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "Lorsque vous passez la souris sur une nouvelle cible qui possède une équipe enregistrée pas encore chargée, charger automatiquement celle-ci.\n\nAgit uniquement lors de la première interaction avec une cible. Vous pouvez toujours charger l'équipe associée à une cible depuis le panneau de cible."
	L["Show After Loading"] = "Afficher après le chargement"
	L["After a team auto loads, show the Rematch window."] = "Après qu'une équipe soit automatiquement chargée, afficher la fenêtre Rematch."
	L["Show On Injured"] = "Afficher sur les blessés"
	L["When a team auto loads, show the Rematch window if any pets are injured."] = "Lorsqu'une équipe charge automatiquement, afficher la fenêtre Rematch si les mascottes ne sont pas au maximum de leurs points de vie."
	L["On Target Only"] = "Sur ciblage uniquement"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right-click!"] = "Charger automatiquement lors du ciblage uniquement, et non sur le passage de la souris.\n\n\124cffff4040ATTENTION !\124r Ceci n'est pas recommandé ! Il sera peut-être trop tard pour charger les mascottes si vous ciblez avec un clic-droit !"
	L["Export Listed Teams"] = "Exporter les équipes listées"
	L["Export all teams listed below to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "Exporter toutes les équipes listées ci-dessous vers une chaîne que vous pouvez copier ailleurs, comme sur des forums ou des emails.\n\nLes autres utilisateurs de Rematch peuvent alors récupérer ces équipes dans leur Rematch via Importer des équipes.\n\nVous pouvez exporter une seule équipe en utilisant le clic-droit sur celle-ci et en choisissant son menu Partager."
	L["Backup All Teams"] = "Sauvegarder toutes les équipes"
	L["This will export all teams across all tabs into text that you can paste elsehwere, such as an email to yourself or a text file someplace safe. You can later restore these teams with the Import Teams option."] = "Cela exportera toutes les équipes de tous les onglets en texte que vous pourrez coller ailleurs, comme un email à vous-même ou un fichier texte dans un endroit sûr. Vous pourrez restaurer ces équipes plus tard avec l'option Importer des équipes."
	L["Import Teams"] = "Importer des équipes"
	L["Import From Pet Battle Teams"] = "Importer depuis les équipes de combat"
	L["Copy your existing teams from Pet Battle Teams to Rematch."] = "Copiez vos équipes existantes depuis vos équipes de combat de mascotte vers Rematch."

-- Menus\PetMenus.lua
	L["Unnamed Pets"] = "Mascottes sans nom"
	L["-- Collected pets that still have their original name.\n\nreturn owned and not customName"] = "-- Mascottes collectées qui possèdent toujours leur nom original.\n\nRetourne leur propre nom et non le nom personnalisé"
	L["Partially Leveled"] = "Partiellement montée"
	L["-- Pets that have earned some xp in battle.\n\nreturn xp and xp>0"] = "-- Mascottes qui ont gagné quelques xp en combat.\n\nRetourne l'xp et l'xp > 0"
	L["Unique Abilities"] = "Compétences uniques"
	L["-- Pets with abilities not shared by other pets.\n\nif not count then\n  -- create count of each ability per species\n  count = {}\n  for speciesID in AllSpeciesIDs() do\n    for abilityID in AllAbilities(speciesID) do\n      if not count[abilityID] then\n        count[abilityID] = 0\n      end\n      count[abilityID] = count[abilityID] + 1\n    end\n  end\nend\n\nfor _,abilityID in ipairs(abilityList) do\n  if count[abilityID]==1 then\n    return true\n  end\nend"] = "-- Mascottes possédant des compétences non partagées par d'autres mascottes.\n\nif not count then\n -- crée un compteur par spécialité\n  count = {}\n  for speciesID in AllSpeciesIDs() do\n    for abilityID in AllAbilities(speciesID) do\n      if not count[abilityID] then\n        count[abilityID] = 0\n      end\n      count[abilityID] = count[abilityID] + 1\n    end\n  end\nend\n\nfor _,abilityID in ipairs(abilityList) do\n  if count[abilityID]==1 then\n    return true\n  end\nend"
	L["Pets Without Rares"] = "Mascottes ne possédant pas de rares"
	L["-- Collected battle pets that have no rare version.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif canBattle and owned and not rares[speciesID] then\n  return true\nend"] = "-- Mascottes collectées qui n'ont pas de version rare.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif canBattle and owned and not rares[speciesID] then\n  return true\nend"
	L["Hybrid Counters"] = "Compteurs hybrides"
	L["-- Pets with three or more attack types different than their pet type.\n\nlocal count = 0\nfor _,abilityID in ipairs(abilityList) do\n  local abilityType,noHints = select(7, C_PetBattles.GetAbilityInfoByID(abilityID) )\n  if not noHints and abilityType~=petType then\n    count = count + 1\n  end\nend\n\nreturn count>=3\n"] = "-- Mascottes possédant 3 attaques ou plus que leur type de mascotte.\n\nlocal count = 0\nfor _,abilityID in ipairs(abilityList) do\n  local abilityType,noHints = select(7, C_PetBattles.GetAbilityInfoByID(abilityID) )\n  if not noHints and abilityType~=petType then\n    count = count + 1\n  end\nend\n\nreturn count>=3\n"
	L["Stop Leveling This Slot"] = "Arrêter de monter de niveau cet emplacement"
	L["Find Similar"] = "Trouver les identiques"
	L["Enter a new name"] = "Entrez un nouveau nom"
	L["List %d Teams"] = "Voir les %d équipes"
	L["Hide Pet"] = "Masquer la mascotte"
	L["Unhide Pet"] = "Voir la mascotte"
	L["Slotted pets cannot be released."] = "Les mascottes dans un emplacement ne peuvent être relâchées."
	L["Release this pet?"] = "Relâcher cette mascotte ?"
	L["Once released, this pet is gone forever!"] = "Une fois relâchée, cette mascotte est partie pour toujours !"
	L["Slotted pets cannot be caged."] = "Les mascottes dans un emplacement ne peuvent être mises en cage."
	L["Injured pets cannot be caged."] = "Les mascottes blessées ne peuvent être mises en cage."
	L["Cage this pet?"] = "Mettre en cage cette mascotte ?"
	L["Start Leveling"] = "Débuter le leveling"
	L["Add To Leveling Queue"] = "Ajouter à la file de leveling"
	L["Stop Leveling"] = "Arrêter le leveling"
	L["Only Favorites"] = "Favorites uniquement"
	L["Favorite Filters"] = "Filtres favoris"
	L["Pet Filter"] = "Filtre de mascotte"
	L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches.\n\nSearch results will be sorted by relevance unless the option %sDon't Sort By Relevance\124r is checked in the Options tab."] = "En plus des filtres de ce menu, vous pouvez affiner la liste de mascottes avec la barre de recherche. Quelques exemples de recherche\n\nMascottes : %sTigré noir\124r\nZones : %sSilithus\124r\nCompétences : %sTempête de sable\124r\nTexte de compétences : %sRace\124r\nNiveaux : %slevel=21-23\124r\nStatistiques: %sspeed>300\124r\n\nLes recherches entre \"quotes\" limitent les résultats à une correspondance complète.\n\nLes recherches seront triées par correspondance sauf si l'option %sNe pas trier par correspondance\124r est cochée dans l'onglet d'options."
	L["Reset All"] = "Réinitialiser tout"
	L["Checkbox Groups"] = "Cases à cocher"
	L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = "Dans les menus de filtre, on suppose que si aucune case n'est cochée dans les groupes de cases c'est que vous voulez voir tous les choix.\n\nVous pouvez aussi :\n\n%s[Maj]+Clic\124r pour tout cocher exceptée la case cliquée.\n\n%s[Alt]+Clic\124r pour tout décocher exceptée la case cliquée."
	L["Low Level (1-7)"] = "Bas niveau (1-7)"
	L["Mid Level (8-14)"] = "Niveau moyen (8-14)"
	L["High Level (15-24)"] = "Haut niveau (15-24)"
	L["Max Level (25)"] = "Niveau max (25)"
	L["Without Any 25s"] = "Sans niveau 25"
	L["Moveset Not At 25"] = "Moveset Not At 25"
	L["You can filter to a specific level or range of levels in the search box. For example, search for:\n\n\%slevel=1\124r\nor\n\%slevel=21-23\124r"] = "Vous pouvez filtrer à un niveau spécifique ou une fourchette de niveaux dans la zone de recherche. Par exemple, recherchez :\n\n\%slevel=1\124r\nor\n\%slevel=21-23\124r"
	L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" categorizes pets with no breed data. Keep your breed addon up to date to see if they have new data."] = "Toutes les données de race sont issues de votre addon %s%s\124r installé.\n\nLa race \"Nouvelle\" catégorise les mascottes qui ne possèdent pas encore de données de races. Maintenez votre addon de race à jour pour voir s'il y a de nouvelles données."
	L["Not Leveling"] = "Pas en cours de leveling"
	L["Not Tradable"] = "Pas négociable"
	L["Can Battle"] = "Peut se battre"
	L["Can't Battle"] = "Ne peut se battre"
	L["One Copy"] = "Un exemplaire"
	L["Two+ Copies"] = "Deux exemplaires ou plus"
	L["Three+ Copies"] = "Trois exemplaires ou plus"
	L["In A Team"] = "Dans une équipe"
	L["Not In A Team"] = "Pas dans une équipe"
	L["Current Zone"] = "Zone actuelle"
	L["Hidden Pets"] = "Mascottes cachées"
	L["Has Notes"] = "Possède des notes"
	L["Reverse Sort"] = "Inverser le tri"
	L["Favorites First"] = "Favorites en premier"
	L["Sort By"] = "Trier par"
	L["You can filter to a specific range of stats too. For example, search for:\n\n\%shealth>500\124r\nor\n\%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = "Vous pouvez aussi filtrer sur une fourchette de statistiques. Par exemple, recherchez :\n\n\%shealth>500\124r\nor\n\%sspeed=200-300\124r\n\nL'ordre de tri n'est normalement pas réinitialisé lorsque les filtres le sont. L'option %sRéinitialiser le tri avec les filtres\124r dans l'onglet d'options réinitialisera le tri lorsque vous réinitialiserez les filtres."
	L["Find Pets With This Ability"] = "Trouver les mascottes avec cette compétence"
	L["Hide this pet?"] = "Masquer cette mascotte ?"
	L["Don't Ask When Hiding Pets"] = "Ne pas demander confirmation lors du masquage de mascottes"
	L["Are you sure you want to hide all versions of %s%s\124r?\n\nHidden pets will not show up in the pet list or searches. You can view or unhide these pets in the 'Other' filter."] = "Êtes-vous sûr de vouloir masquer toutes les versions de %s%s\124r ?\n\nLes mascottes cachées n'apparaîtront plus dans la liste de mascottes ou lors des recherches. Vous pouvez les voir ou les ré-afficher dans le filtre 'Autre'."
	L["Save Filter"] = "Enregistrer le filtre"
	L["A filter must be active before it can be saved."] = "Un filtre doit être actif avant qu'il puisse être enregistré."
	L["Save this as a favorite filter?"] = "Enregistrer ce filtre comme filtre favoris ?"
	L["Filters: %s%s\124r\n\nChoose a name to use in the Favorite Filters menu:"] = "Filtres : %s%s\124r\n\nChoisissez un nom à utiliser dans le menu des filtres favoris :"
	L["Note: Search text and Sort order are not included in the filter."] = "À noter : Le texte de recherche et l'ordre de tri ne sont pas inclus dans le filtre."
	L["Delete Filter"] = "Supprimer le filtre"
	L["Are you sure you want to delete the filter named %s%s\124r?"] = "Êtes-vous sûr de vouloir supprimer le filtre %s%s\124r ?"
	L["New Script"] = "Nouveau script"
	L["Create a new pet filter."] = "Créer un nouveau filtre de mascotte."
	L["Delete Script"] = "Supprimer le script"
	L["Are you sure you want to delete the script named %s%s\124r?"] = "Êtes-vous sûr de vouloir supprimer le script %s%s\124r ?"

-- Menus\Npcs.lua
	L["Eastern Kingdom"] = "Royaumes de l'Est"
	L["Kalimdor"] = "Kalimdor"
	L["Outland"] = "Outreterre"
	L["Northrend"] = "Norfendre"
	L["Cataclysm"] = "Cataclysme"
	L["Pandaria"] = "Pandarie"
	L["Beasts of Fable"] = "Mythes et légendes"
	L["Celestial Tournament"] = "Tournois Célestes"
	L["Draenor"] = "Draenor"
	L["Garrison"] = "Fief"
	L["Menagerie"] = "Ménagerie"
	L["Tanaan Jungle"] = "Jungle de Tanaan"
	L["Val'sharah"] = "Val'sharah"
	L["Suramar"] = "Suramar"
	L["Stormheim"] = "Tornheim"
	L["Highmountain"] = "Haut-Roc"
	L["Dalaran"] = "Dalaran"
	L["Azsuna"] = "Azsuna"
	L["No Target"] = "Pas de cible"
	L["Noteworthy Targets"] = "Cibles notables"
	L["These are noteworthy targets such as tamers and legendary pets.\n\nChoose one to view the pets you would battle.\n\nTargets with a \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t already have a team saved."] = "Il y a des cibles notables comme les dompteurs et mascottes légendaires.\n\nChoisissez-en une pour voir les mascottes que vous souhaiteriez combattre.\n\nLes cibles avec un \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t possèdent déjà une équipe enregistrée."

-- Dialogs\Dialog.lua
	L["Tab:"] = "Onglet :"

-- Cards\PetCard.lua
	L["Damage\nTaken"] = "Dégâts\nsubis"
	L["from"] = "avec"
	L["abilities"] = "compétences"
	L["Unpin Pet Card"] = "Détacher la fiche de mascotte"
	L["While pinned, the pet card will display where you last moved it.\n\nClick this to unpin the pet card and snap it back to the pets."] = "Tant qu'épinglée, la fiche de mascotte sera affichée au dernier endroit où vous l'aviez placé.\n\nCliquez ici pour détacher la fiche de mascotte et la re-positionner avec les mascottes"
	L["Pet Card"] = "Fiche de mascotte"
	L["Hold [Alt] to view more about this pet."] = "Maintenez [Alt] pour en savoir plus sur cette mascotte."
	L["XP: %d/%d (%d%%)"] = nil
	L["Possible Breeds"] = "Races possibles"
	L["Slotted"] = "Placée"
	L["This pet is loaded in one of the three battle pet slots."] = "Cette mascotte est chargée dans l'un des trois emplacements de combat de mascotte."
	L["Favorite"] = "Favorite"
	L["This pet is marked as a Favorite from its right-click menu."] = "Cette mascotte est marquée comme favorite depuis son menu contextuel."
	L["This pet is in Rematch's leveling queue."] = "Cette mascotte est dans la file d'attente de leveling Rematch."
	L["Determines how stats are distributed.  All breed data is pulled from your installed %s%s\124r addon."] = "Détermine comment les statistiques sont distribués.  Toute donnée de race est issue de votre addon %s%s\124r."
	L["Species ID"] = "ID d'espèce"
	L["All versions of this pet share this unique \"species\" number."] = "Toutes les versions de cette mascotte partagent ce numéro unique \"d'espèce\"."
	L["%d Teams"] = "%d équipes"
	L["Teams"] = "Équipes"
	L["%s Click to search for all teams that include this pet."] = "%s Cliquez pour rechercher toutes les équipes incluant cette mascotte."
	L["%s Click to search for all versions of this pet."] = "%s Cliquez pour rechercher toutes les versions de cette mascotte."
	L["When this team loads, your current leveling pet will go in this spot."] = "Lorsque cette équipe charge, votre mascotte actuelle de leveling va dans cet emplacement."
	L["This is an opponent pet."] = "Mascotte d'un adversaire."
	L["All breed data pulled from %s%s\124r."] = "Toutes les données de race sont issues de %s%s\124r."
	L["Stats At Level 25 \124cff0070ddRare"] = "Statistiques au niveau 25 \124cff0070ddRare"
	L["No known breeds :("] = "Race inconnue :("

-- Cards\AbilityCard.lua
	L["Vs"] = nil

-- Cards\Notes.lua
	L["Pet Notes"] = "Notes"
	L["Delete Notes"] = "Supprimer les notes"
	L["Are you sure you want to delete the notes for %s\124r?"] = "Êtes-vous sûr de vouloir supprimer les notes pour %s\124r ?"

-- Cards\WinRecord.lua
	L["Win Record"] = "Enregistrement de victoire"
	L["Hold [Alt] to view totals for all teams."] = "Maintenez [Alt] pour voir les totaux de toutes les équipes."
	L["Wins:"] = "Victoires :"
	L["Losses:"] = "Défaites :"
	L["Draws:"] = "Matchs nuls :"
	L["Totals Across All Teams"] = "Totaux toutes équipes confondues"
	L["%s%s\124r Battles"] = "Combats %s%s\124r"
	L["+1 Win"] = "+1 Victoire"
	L["+1 Loss"] = "+1 Défaite"
	L["+1 Draw"] = "+1 Match nul"
	L["Reset Win Record"] = "Réinitialiser les enregistrements de victoire"
	L["Are you sure you want to remove all wins, losses and draws from the team \"%s\"?"] = "Êtes-vous sûr de vouloir supprimer toutes les victoires, défaites et matchs nuls de l'équipe \"%s\" ?"
	L["Reset All Win Records"] = "Réinitialiser tous les enregistrements de victoire"
	L["Are you sure?"] = "Êtes-vous sûr ?"
	L["This will remove win record data for all teams and cannot be undone!"] = "Cela supprimera toutes les données d'enregistrement de victoire pour toutes les équipes et c'est irréversible !"
	L["Convert Team Names To Win Records"] = "Convertir les noms d'équipes en enregistrements de victoires"
	L["Convert"] = "Convertir"
	L["This will look for teams with names that may include win-loss-draw stats and pull those into an actual win record before removing the numbers from the team name.\n\nDo you want to convert these teams?\n\nThe currently loaded team will be unloaded to prevent major complications.\n\n\124cffff1111Please backup your teams before attempting this!"] = "Cela va chercher les équipes avec des noms qui peuvent inclure des statistiques de victoire-défaite-match nul et récupérer celles-ci dans un enregistrement de victoire actuel avant de supprimer les nombres de leur nom d'équipe.\n\nVoulez-vous convertir cette équipe ?\n\nL'équipe actuellement chargée sera déchargée pour éviter des complications.\n\n\124cffff1111Merci de sauvegarder vos équipes avant de tenter cette manip !"
	L["Done!"] = "Fait !"
	L["%s%d teams and %d battles were converted."] = "%s%d équipes et %d combats ont été convertis."

-- Panels\PetPanel.lua
	L["Strong vs"] = "Forte vs"
	L["Tough vs"] = "Difficulté vs"
	L["Pets: %s%d"] = "Mascottes : %s%d"
	L["Filters: %s%s"] = "Filtres : %s%s"

-- Panels\LoadoutPanel.lua
	L["Target has a saved team"] = "Possède une équipe"
	L["Load"] = "Charger"
	L["Load the team saved for this target."] = "Charge l'équipe enregistrée pour cette cible."
	L["This target has no saved team"] = "Pas d'équipe enregistrée"
	L["Save the currently loaded pets to this target."] = "Enregistre les mascottes actuellement chargées pour cette cible."

-- Panels\TeamPanel.lua

-- Panels\QueuePanel.lua
	L["Ascending Level"] = "Niveau croissant"
	L["Descending Level"] = "Niveau décroissant"
	L["Median Level"] = "Niveau médian"
	L["Type"] = "Type"
	L["Queue"] = "File"
	L["This is the leveling queue. Drag pets you want to level here.\n\nRight click any of the three battle pet slots and choose 'Put Leveling Pet Here' to mark it as a leveling slot you want controlled by the queue.\n\nWhile a leveling slot is active, the queue will fill the slot with the top-most pet in the queue. When this pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will take its place.\n\nTeams saved with a leveling slot will reserve that slot for future leveling pets."] = "Il s'agit de la file d'attente de leveling. Déplacez les mascottes que vous souhaitez monter ici.\n\nFaites un clic-droit sur n'importe lequel des trois emplacements de combat de mascotte et sélectionnez 'Mettre une mascotte de leveling ici' pour le marquer comme emplacement de leveling que vous souhaitez contrôler avec la file d'attente.\n\nTant qu'un emplacement de leveling est actif, la file d'attente le remplira avec la meilleure mascotte de la file. Quand cette mascotte sera niveau 25 (félicitation !) elle quittera la file et la mascotte suivante prendra sa place.\n\nLes équipes enregistrées avec un emplacement de leveling conserveront cet emplacement pour les futures mascottes de leveling."
	L["Sort by:"] = "Trier par :"
	L["Sort all pets in the queue from level 1 to level 24."] = "Trie toutes les mascottes de la file du niveau 1 au niveau 24."
	L["Sort all pets in the queue for levels closest to 10.5."] = "Trie toutes les mascottes de la file pour les niveaux les plus proche de 10,5."
	L["Sort all pets in the queue from level 24 to level 1."] = "Trie toutes les mascottes de la file du niveau 24 au niveau 1."
	L["Sort all pets in the queue by their types."] = "Trie toutes les mascottes de la file par leur type."
	L["Active Sort"] = "Tri actif"
	L["The queue will stay sorted in the order chosen. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets while the queue is actively sorted."] = "La file restera triée dans l'ordre choisi. L'ordre des mascottes peut automatiquement changer en fonction de leur gain d'xp ou de leur ajout/suppression de la file.\n\nVous ne pouvez pas changer manuellement l'ordre des mascottes tant que la file est triée."
	L["Pause Preferences"] = "Suspendre les préférences"
	L["Suspend all preferred loading of pets from the queue, except for pets that can't load."] = "Suspend tous les chargements de mascottes préférés depuis la file, excepté pour les mascottes qui ne peuvent être chargée."
	L["Fill Queue"] = "Remplir la file"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, and for which you don't have a level 25 or one in the queue already."] = "Remplir la file de leveling avec une version de chaque mascotte qui peut monter de niveau depuis la liste de mascottes filtrée, et pour lesquelles vous n'avez de niveau 25 ou une version déjà présente dans la file."
	L["Fill Queue More"] = "Remplir plus la file"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, regardless whether you have any at level 25 or one in the queue already."] = "Remplir la file de leveling avec une version de chaque mascotte qui peut monter de niveau depuis la liste de mascottes filtrée, peu importe si vous en possédez déjà une version au niveau 25 ou une version déjà présente dans la file."
	L["Empty Queue"] = "Vider la file"
	L["Remove all leveling pets from the queue."] = "Supprime toutes les mascottes de leveling de la file d'attente."
	L["Are you sure you want to remove all pets from the leveling queue?"] = "Êtes-vous sûr de vouloir supprimer toutes les mascottes de la file de leveling ?"
	L["Leveling Queue"] = "File de leveling"
	L["No Active Sort"] = "Pas de tri actif"
	L["Turn off Active Sort. Queued pets can then be rearranged and will not automatically reorder themselves.\n\nTo turn Active Sort back on, check %sActive Sort\124r in the Queue menu."] = "Désactive le tri actif. Les mascottes dans la file peuvent alors être réarrangées et ne seront pas automatiquement retriées par elles-même.\n\nPour réactiver le tri actif, cochez %sTri actif\124r dans le menu de la file."
	L["Turn Off Active Sort?"] = "Désactiver le tri actif ?"
	L["Leveling Pets: %s%s"] = "Mascottes : %s%s"
	L["Active Sort:"] = "Tri actif :"
	L["Add these pets to the queue?"] = "Ajouter ces mascottes à la file ?"
	L["This will add %s%d\124r pets to the leveling queue.\n\nYou can be more selective by filtering pets.\n\nFor instance, if you filter pets to High Level (15-24) and Rare, Fill Queue will only add rare pets between level 15 and 24."] = "Cela ajoutera %s%d\124r mascottes à la file de leveling.\n\nVous pouvez être plus sélectif en filtrant les mascottes.\n\nPar exemple, si vous filtrez les mascottes sur Haut niveau (15-24) et Rare, Remplir la file ajoutera uniquement les mascottes rares entre le niveau 15 et le niveau 24."
	L["This will add %s%d\124r pets to the leveling queue."] = "Cela ajoutera %s%d\124r mascottes à la file de leveling."

-- Panels\MiniQueue.lua

-- Panels\MiniPanel.lua
	L["This target has a saved team"] = "Possède une équipe"

-- Panels\OptionPanel.lua
	L["All Options"] = "Toutes les options"
	L["Targeting Options"] = "Options de ciblage"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right click!"] = "Charger automatiquement lors du ciblage uniquement, et non sur le passage de la souris.\n\n\124cffff4040ATTENTION !\124r Ceci n'est pas recommandé ! Il sera peut-être trop tard pour charger les mascottes si vous ciblez avec un clic-droit !"
	L["Always Show When Targeting"] = "Toujours afficher lors du ciblage"
	L["Regardless whether a target's team is already loaded, show the Rematch window when you target something with a saved team."] = "Peu importe si une équipe liée à une cible est chargée, monter la fenêtre Rematch quand vous ciblez quelque chose avec une équipe enregistrée."
	L["Preferred Window Mode"] = "Mode fenêtré préféré"
	L["Minimized Standalone"] = "Autonome minimisée"
	L["When automatically showing the Rematch window, show the minimized standalone window."] = "Lors de l'affichage automatique de la fenêtre Rematch, afficher la fenêtre autonome minimisée."
	L["Maximized Standalone"] = "Autonome maximisée"
	L["When automatically showing the Rematch window, show the maximized standalone window."] = "Lors de l'affichage automatique de la fenêtre Rematch, afficher la fenêtre autonome maximisée."
	L["Pet Journal"] = "Journal de mascottes"
	L["When automatically showing the Rematch window, show the pet journal."] = "Lors de l'affichage automatique de la fenêtre Rematch, afficher le journal de mascottes."
	L["Standalone Window Options"] = "Options de fenêtre autonome"
	L["Use Custom Scale"] = "Utiliser une échelle personnalisée"
	L["Change the relative size of the standalone window to anywhere between 50% and 200% of its standard size."] = "Change la taille relative de la fenêtre autonome pour quelque part entre 50% et 200% de sa taille standard."
	L["Single Panel Mode"] = "Mode panneau simple"
	L["Collapse the maximized standalone window to one panel instead of two side by side.\n\nUsers of earlier versions of Rematch may find this mode more familiar."] = "Réduit la taille maximale de la fenêtre autonome en un seul panneau plutôt que deux côte à côte.\n\nLes utilisateurs des versions précédentes de Rematch peuvent trouver ce mode plus familier."
	L["Combine Pets And Queue"] = "Combiner mascottes et file"
	L["In single panel mode, combine the Pets and Queue tabs together. A narrow queue will display to the right of the pet list instead of in a separate tab."] = "En mode simple panneau, combine les onglets de mascottes et de file d'attente ensemble. Une file d'attente étroite s'affiche à droite de la liste de mascottes plutôt que dans un onglet séparé."
	L["Keep Window On Screen"] = "Garder la fenêtre à l'écran"
	L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = "Ne pas masquer la fenêtre autonome quand la touche Echap est pressée ou les autres fois où elle devrait être masquée, comme en allant dans le menu du jeu."
	L["Even For Pet Battles"] = "Même pour les combats de mascotte"
	L["Keep the standalone window on the screen even when you enter pet battles."] = "Garder la fenêtre autonome à l'écran même quand vous entrez dans un combat de mascotte."
	L["Even Across Sessions"] = "Même entre sessions de jeu"
	L["If the standalone window was on screen when logging out, automatically summon it on next login."] = "Si la fenêtre autonome était à l'écran lors de la déconnexion, la réinvoquer automatiquement à la prochaine connexion."
	L["Don't Minimize With ESC Key"] = "Ne pas minimiser avec la touche Echap"
	L["Don't minimize the standalone window when the ESCape key is pressed."] = "Ne pas minimiser la fenêtre autonome quand la touche Echap est pressée."
	L["Lower Window Behind UI"] = "Fenêtre plus petite derrière l'interface"
	L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = "Pousser la fenêtre autonome derrière les autres parties de l'interface, les autres parties de l'interface s'afficheront donc au premier plan."
	L["Move Panel Tabs To Right"] = "Déplacer le panneau d'onglets à droite"
	L["Align the Pets, Teams, Queue and Options tabs to the right side of the standalone window."] = "Aligner les onglets de mascottes, d'équipes, de file d'attente et d'options du côté droit de la fenêtre autonome."
	L["Minimal Minimized Window"] = "Fenêtre minimisée minimale"
	L["Remove the titlebar and tabs when the standalone window is minimized."] = "Supprimer la barre de titre et les onglets lorsque la fenêtre autonome est minimisée."
	L["Appearance Options"] = "Options d'apparence"
	L["Compact List Format"] = "Format de liste compacte"
	L["Use an alternate style of lists for Pets, Teams and Queue to display more on the screen at once.\n\n\124cffff4040This option requires a Reload."] = "Utiliser un style de liste alternatif pour les mascottes, les équipes et la file d'attente pour en afficher plus à l'écran à la fois.\n\n\124cffff4040Cette option exige un rechargement de l'interface."
	L["Use Smaller Text Too"] = "Utiliser des textes plus petits également"
	L["Also use smaller text in the Compact List Format so more text displays on each button."] = "Utiliser aussi des textes plus petits dans la liste au format compact, plus de texte sera donc affiché sur chaque bouton."
	L["Color Pet Names By Rarity"] = "Colorer les noms par rareté"
	L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = "Colorer les noms de mascottes de la même couleur que leur rareté. Bleu pour rare, vert pour inhabituel, etc."
	L["Hide Rarity Borders"] = "Masquer les bords de rareté"
	L["Don't color the icon border for pets you own in the same color as its rarity."] = "Ne pas colorer les bords des icônes de mascottes en fonction de leur rareté."
	L["Hide Level At Max Level"] = "Masquer le niveau au niveau max"
	L["If a pet is level 25, don't show its level on the pet icon."] = "Si une mascotte est niveau 25, ne pas afficher son niveau sur son icône."
	L["Show Ability Numbers"] = "Afficher le numéro de compétence"
	L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = "Dans le menu contextuel de compétence, afficher les nombres 1 et 2 pour aider avec les notations communes comme \"Nom de mascotte 122\" pour connaître les compétences à utiliser."
	L["Toolbar Options"] = "Options de barre d'outil"
	L["Move Toolbar To Bottom"] = "Placer la barre d'outil en bas"
	L["Move the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc) to the bottom of the standalone window.\n\nAlso convert the red panel buttons (Save, Save As, Find Battle) to toolbar buttons."] = "Déplacer les boutons de la barre d'outil (Ranimer les mascottes, Bandages de mascottes, etc) en bas de la fenêtre autonome.\nConvertir également les boutons rouges du panneau (Enregistrer, Enregistrer sous, Trouver un combat) en boutons de la barre d'outil."
	L["Reverse Toolbar Buttons"] = "Inverser les boutons de la barre d'outil"
	L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = "Inverse l'ordre des boutons de la barre d'outil (Ranimer les mascottes, Bandages pour mascottes, etc)."
	L["Hide On Toolbar Right Click"] = "Masquer sur clic-droit de la barre d'outil"
	L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = "Lorsqu'un un bouton de la barre d'outil est utilisé avec un clic-droit, dissimuler la fenêtre Rematch après avoir réalisé l'action associée."
	L["Safari Hat Reminder"] = "Rappel pour Chapeau de Safari"
	L["Draw attention to the safari hat button while a pet below max level is loaded.\n\nAlso show the Rematch window when a low level pet loads and the safari hat is not equipped."] = "Attirer l'attention sur le bouton Chapeau de Safari lorsqu'une mascotte de niveau maximum est chargée.\n\nMontrer également la fenêtre Rematch lorsqu'une mascotte de bas niveau charge et que le Chapeau de Safari n'est pas équipé."
	L["Pet Card & Notes Options"] = "Options de fiche de mascotte & de notes"
	L["Allow Pet Cards To Be Pinned"] = "Permettre à la fiche de mascotte d'être épinglée"
	L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = "Lors du glissement d'une fiche de mascotte vers une autre partie de l'écran, épingler la fiche de manière à ce que toutes les futures fiches de mascotte s'affichent au même endroit, jusqu'à ce que la fiche soit déplacée à nouveau ou que le bouton Détacher soit cliqué."
	L["Click For Pet Cards & Notes"] = "Cliquer pour fiche de mascotte & notes"
	L["Instead of automatically showing pet cards and notes when you mouseover them, require clicking the pet or notes button to display them."] = "Plutôt que d'afficher automatiquement les fiches de mascotte et les notes lorsque vous passez la souris dessus, exiger un clic sur la mascotte ou sur le bouton de notes pour les afficher."
	L["Faster Pet Cards & Notes"] = "Fiche de mascottes & notes plus rapides"
	L["Instead of a small delay before showing pet cards and notes, immediately show them as you mouseover pets and notes buttons."] = "Au lieu d'avoir un petit délai avant d'afficher les fiches de mascottes et les notes, les afficher immédiatement lors du passage de la souris sur les mascottes et les boutons de notes."
	L["Use Pet Cards In Battle"] = "Utiliser les fiches de mascotte en combat"
	L["Use the pet card on the unit frames during a pet battle instead of the default tooltip."] = "Utiliser la fiche de mascotte sur le cadre d'unité pendant un combat de mascotte au lieu de l'infobulle par défaut."
	L["Use Pet Cards For Links"] = "Utiliser les fiches de mascottes pour les liens"
	L["Use the pet card when viewing a link of a pet someone else sent you instead of the default link."] = "Utiliser la fiche de mascotte lorsque vous visualisez un lien d'une mascotte que quelqu'un d'autre vous a envoyé, plutôt que d'utiliser le lien par défaut."
	L["Show Team Cards"] = "Afficher les fiches d'équipe"
	L["Show a card with team details when you mouseover a team.\n\n%sIMPORTANT:\124r While this option is enabled, clicking a team will lock the team card instead of loading it. %sDouble-Click\124r to load a team with this option enabled, just as you would Double-Click a pet to summon it."] = "Afficher une fiche avec les détails de l'équipe lorsque vous passez la souris sur une équipe.\n\n%sIMPORTANT :\124r Tant que cette option est activée, le fait de cliquer sur une équipe verrouillera la fiche de l'équipe plutôt que de charger l'équipe. %sDouble-Cliquez\124r pour charger une équipe avec cette option activée, simplement comme vous le feriez pour invoquer une mascotte."
	L["Keep Notes On Screen"] = "Garder les notes à l'écran"
	L["Don't hide notes when the ESCape key is pressed or other times it would hide, such as changing tabs or closing Rematch."] = "Ne pas masquer les notes lorsque la touche Echap est pressée ou les autres fois où elle seraient masquée, comme lors du changement d'onglet ou de la fermeture de Rematch."
	L["Show Notes Upon Targeting"] = "Afficher les notes lors du ciblage"
	L["When your target has a saved team with notes, automatically display and lock the notes."] = "Lorsque votre cible dispose d'une équipe enregistrée possédant des notes, afficher et verrouiller automatiquement les notes."
	L["Show Notes In Battle"] = "Afficher les notes pendant un combat"
	L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "Si l'équipe chargée possède des notes, afficher et verrouiller ces notes lorsque vous entrez dans un combat de mascotte."
	L["Only Once Per Team"] = "Seulement une fois par équipe"
	L["Only display notes automatically the first time entering battle, until another team is loaded."] = "Afficher les notes automatiquement uniquement la première fois que l'équipe commence un combat, jusqu'à ce qu'une autre équipe soit chargée."
	L["Alternate Lore Font"] = "Police de connaissance alternée"
	L["Use a more normal-looking font for lore text on the back of the pet card."] = "Utiliser une police avec un look plus classique pour le texte des connaissances en bas de le fiche de mascotte."
	L["Show Species ID On Pet Cards"] = "Afficher l'ID d'espèce sur la fiche"
	L["Display the numerical species ID of a pet as a stat on their pet card."] = "Afficher l'ID numérique de l'espèce d'une mascotte comme une caractéristique sur leur fiche de mascotte."
	L["Team Options"] = "Options d'équipe"
	L["Hide Targets Below Teams"] = "Masquer les cibles sous les équipes"
	L["Hide the target name that appears beneath a team that is not named the same as its target."] = "Masquer le nom de la cible qui apparaît sous une équipe qui ne s'appelle pas pareil que sa cible."
	L["Always Show Team Tabs"] = "Toujours afficher les onglets d'équipe"
	L["Show team tabs along the right side of the window even if you're not on the team panel."] = "Afficher les onglets d'équipe sur le côté droit de la fenêtre même si vous n'êtes pas sur le panneau d'équipe."
	L["Move Team Tabs To Left"] = "Déplacer les onglets d'équipe à gauche"
	L["Move the team tabs along the right side of the standalone window to the left side."] = "Déplace les onglets d'équipe du côté droit de la fenêtre vers le côté gauche."
	L["Auto Track Win Record"] = "Suivre automatiquement les victoires"
	L["At the end of each battle, automatically record whether the loaded team won or lost.\n\nForfeits always count as a loss.\n\nYou can still manually update a team's win record at any time."] = "À la fin de chaque combat, enregistrer automatiquement le fait que l'équipe chargée ait gagné ou perdu.\n\nLes forfaits compte toujours comme une défaite.\n\nVous pouvez toujours, à tout moment, mettre à jour manuellement un enregistrement de victoire d'une équipe."
	L["For PVP Battles Only"] = "Pour les combat JcJ uniquement"
	L["Automatically track whether the loaded team won or lost only in a PVP battle and never for a PVE battle."] = "Suivre automatiquement si l'équipe chargée a gagné ou perdu uniquement dans les combats JcJ et jamais pour les combats classiques."
	L["Display Total Wins Instead"] = "Afficher plutôt le total de victoires"
	L["Instead of displaying the win percentage of a team on the win record button, display the total number of wins.\n\nTeam tabs that are sorted by win record will sort by total wins also."] = "Au lieu d'afficher le pourcentage de victoires d'une équipe sur le bouton d'enregistrement de victoire, afficher le nombre total de victoire.\n\nLes onglets d'équipe qui sont triés par enregistrement de victoire seront triés par nombre de victoires total aussi."
	L["Hide Win Record Buttons"] = "Masquer les boutons de victoires"
	L["Hide the win record button displayed to the right of each team.\n\nYou can still manually edit a team's win record from its right-click menu and automatic tracking will continue if enabled."] = "Masquer le bouton d'enregistrement de victoire affiché à droite de chaque équipe.\n\nVous pouvez toujours modifier manuellement les enregistrement de victoire d'une équipe depuis son menu clic-droit et le suivi automatique continuera s'il est activé."
	L["Leveling Queue Options"] = "Options de la file de leveling"
	L["Prefer Living Pets"] = "Préférer les mascottes vivantes"
	L["When loading pets from the queue, skip dead pets and load living ones first."] = "Lors du chargement des mascottes depuis la file, passe les mascottes mortes et charge celles vivantes en premier."
	L["And At Full Health"] = "Et avec points de vie max"
	L["Also prefer uninjured pets when loading pets from the queue."] = "Préférer également les mascottes qui possèdent leur maximum de points de vie lors du chargement des mascottes depuis la file."
	L["Double Click To Send To Top"] = "Double-clic pour envoyer en tête"
	L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = "Lorsqu'une mascotte de la file est double-cliquée, l'envoyer en tête de la file plutôt que de l'invoquer."
	L["Hide Leveling Pet Toast"] = "Masquer les popup des mascottes de leveling"
	L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "Ne pas afficher les popup 'toast' lorsqu'une nouvelle mascotte est automatiquement chargée depuis la file de leveling."
	L["Automatically Level New Pets"] = "Monter automatiquement les nouvelles mascottes"
	L["When you capture or learn a pet, automatically add it to the leveling queue."] = "Lorsque vous capturez ou apprenez une nouvelle mascotte, l'ajouter automatiquement à la file de leveling."
	L["Only Pets Without A 25"] = "Mascottes sans 25 uniquement"
	L["Only automatically level pets which don't have a version already at 25 or in the queue."] = "Monter automatiquement uniquement les mascottes qui ne possèdent pas déjà une version au niveau 25 ou déjà dans la file de leveling."
	L["Only Rare Pets"] = "Mascottes rares uniquement"
	L["Only automatically level rare quality pets."] = "Monter automatiquement uniquement les mascottes de qualité rare."
	L["Pet Filter Options"] = "Options de filtre de mascotte"
	L["Reset Filters On Login"] = "Réinitialiser les filtres à la connexion"
	L["When logging in, start with all pets listed and no filters active."] = "Lors de la connexion, commencer avec toutes les mascottes affichées et aucun filtre actif."
	L["Reset Sort With Filters"] = "Réinitialiser le tri avec les filtres"
	L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = "Lors du nettoyage des filtres, réinitialiser également le tri par défaut : Triées par Nom, Favorites en premier."
	L["Don't Reset Search With Filters"] = "Ne pas réinitialiser la recherche avec les filtres"
	L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = "Lors du nettoyage manuel des filtres, ne pas nettoyer la barre de recherche en même temps.\n\nPlusieurs actions, comme la connexion ou la recherche des similaires, nettoyeront toujours la recherche peu importe ce paramètre."
	L["Sort By Chosen Name"] = "Trier par surnom"
	L["When pets are sorted by name, sort them by the name given with the Rename option instead of their original name."] = "Lorsque les mascottes sont triées par nom, les trier sur le nom donné via l'option Renommer plutôt que leur nom original."
	L["Don't Sort By Relevance"] = "Ne pas trier par pertinence"
	L["When searching for something by name in the search box, do not sort the results by relevance.\n\nWhen sorted by relevance, pets with the search term in their name are listed first, followed by terms in notes, then abilities and then source text last."] = "Lors de la recherche de quelque chose par nom dans la barre de recherche, ne pas trier les résultats par pertinence.\n\nLorsque triés par pertinence, les mascottes avec les mots-clés de recherche dans leur nom sont listées en premier, puis celles qui ont les mots-clés dans leurs notes, puis les compétences et la source en dernier."
	L["Confirmation Options"] = "Options de confirmation"
	L["Don't display a popup when a team loads and a pet within the team can't be found."] = "Ne pas afficher d'alerte lors du chargement d'une équipe si une mascotte de celle-ci ne peut être trouvée."
	L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = "Ne pas demander de confirmation lors du masquage d'une mascotte.\n\nVous pouvez voir les mascottes masquées dans le filtre 'Autres'."
	L["Don't Remind About Backups"] = "Pas de rappel pour les sauvegardes"
	L["Don't show a popup offering to backup teams every once in a while. Generally, the popup appears sometime after the number of teams increases by 50."] = "Ne pas afficher de popup proposant de sauvegarder les équipes régulièrement. En règle générale, la popup apparaît quelques temps après que le nombre d'équipes ait dépassé les 50."
	L["Miscellaneous Options"] = "Options diverses"
	L["Show After Pet Battle"] = "Afficher après un combat de mascotte"
	L["Show the Rematch window after leaving a pet battle."] = "Afficher la fenêtre Rematch après avoir quitté un combat de mascotte."
	L["Disable Sharing"] = "Désactiver le partage"
	L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "Désactive le bouton Envoyer et bloque également la récéption de mascottes par d'autres joueurs. Importer et Exporter continuent de fonctionner."
	L["Use Minimap Button"] = "Utiliser le bouton de la minicarte"
	L["Place a button on the minimap to toggle Rematch and load favorite teams."] = "Place un bouton sur la minicarte pour activer/descativer Rematch et charger les équipes favorites."
	L["Keep Companion"] = "Garder le compagnon"
	L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = "Après qu'une équipe soit chargée, réinvoquer la mascotte qui était à vos côtés avant le chargement; ou renvoyer la mascotte si vous n'en avez pas à vos côtés."
	L["Hide Tooltips"] = "Masquer les infobulles"
	L["Hide the more common tooltips in Rematch."] = "Masque la plupart des infobulles de Rematch."
	L["Hide Extra Help"] = "Masquer l'aide complémentaire"
	L["Hide the informational \"Help\" items found in many menus and on the pet card."] = "Masque les items \"Aide\" que l'on trouve dans plusieurs menus et sur la fiche de mascotte."
	L["Use Default Pet Journal"] = "Utiliser le codex de mascottes par défaut"
	L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "Désactive l'intégration de Rematch avec le codex de mascottes original.\n\nVous pouvez toujours utiliser Rematch dans sa fenêtre autonome, accessible via une touche de raccourci, la commande /rematch ou depuis le bouton de la minicarte si activé dans les options."
	L["Rematch version %s"] = "Rematch version %s"
	L["The%s icon indicates new options."] = "L'icône %s indique de nouvelles options."
	L["Anchor"] = "Ancrage"
	L["Bottom Right"] = "En bas à droite"
	L["Top Right"] = "En haut à droite"
	L["Bottom Left"] = "En bas à gauche"
	L["Top Left"] = "En haut à gauche"
	L["Anchor: %s"] = "Ancrage : %s"
	L["When the standlone window is minimized, send it to the %s corner."] = "Lorsque la fenêtre autonome est minimisée, l'envoyer dans le coin %s."
	L["Current Scale: %d%%"] = "Échelle actuelle : %d%%"
	L["Click here to choose a different scale for the standalone window."] = "Cliquez ici pour choisir une échelle différente pour la fenêtre autonome."
	L["\n\n%sThis will close the journal and open the standalone window."] = "\n\n%s Cela fermera le codex et ouvrira la fenêtre autonome."
	L["Reload the UI now?"] = "Recharger l'interface maintenant ?"
	L["You've chosen to change the setting for Compact List Format.\n\nThis change doesn't take effect until a reload or logout."] = "Vous avez choisi de changer le paramètre pour le format de liste compacte.\n\nCe changement ne prendra effet qu'après un rechargement de l'interface ou une déconnexion."
	L["Custom Scale"] = "Échelle personnalisée"
	L["Keep this scale?"] = "Garder cette échelle ?"
	L["This scale determines the relative size of the standalone window, where 100% is the standard size."] = "Cette échelle détermine la taille relative de la fenêtre autonome, où 100% est la taille normale."

-- Widgets\BottomPanel.lua
	L["You can also double-click a pet to summon or dismiss it."] = "Vous pouvez aussi double-cliquer sur une mascotte pour l'invoquer ou la renvoyer."
	L["Disable Rematch"] = "Désactiver Rematch"
	L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "Décocher cette case pour revenir au codex de mascottes standard.\n\nVous pouvez toujours utiliser Rematch dans sa fenêtre autonome, accessible via une touche de raccourci, la commande /rematch ou depuis le bouton de la minicarte si activé dans les options."

-- Widgets\TeamTabs.lua
	L["Edit Tab"] = "Modifier l'onglet"
	L["Change the name or icon of this tab."] = "Changer le nom ou l'icône de cet onglet."
	L["Custom Sort"] = "Tri personnalisé"
	L["Remove Custom Sort"] = "Supprimer le tri personnalisé"
	L["Are you sure you want to remove the custom sort order?\n\nThe saved order of teams will be lost and turning this option back on will not restore the old order."] = "Êtes-vous sûr de vouloir supprimer l'ordre de tri personnalisé ?\n\nL'ordre des équipes enregistré sera perdu et réactiver cette option ne permettra pas de récupérer l'ancien ordre de tri."
	L["While checked, you can rearrange the order of teams within this tab from the teams' right-click menu."] = "Tant que cette case est cochée, vous pouvez réarranger l'ordre des équipes à l'intérieur de cet onglet depuis le menu clic-droit des équipes."
	L["Sort By Wins"] = "Trier par victoires"
	L["This option is disabled while Custom Sort is active."] = "Cette option est désactivée tant que le tri personnalisé est actif."
	L["Sort teams in this tab by their wins.\n\nFavorited teams will still list at the top."] = "Tri les équipes de cet onglet en fonction de leurs victoires.\n\nLes équipes favorites resteront listées en premier."
	L["Set leveling preferences for all teams within this tab.\n\nIf a team within this tab also has preferences, the tab's preferences will take priority over the team's preferences."] = "Définir les préférences de leveling pour toutes les équipes de cet onglet.\n\nSi une équipe de cet onglet possède déjà des préférences, les préférences d'onglet prennent la priorité sur les préférences d'équipe."
	L["Export Tab"] = "Exporter l'onglet"
	L["Export all teams in this tab to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "Exporte toutes les équipes de cet onglet vers une chaîne que vous pouvez copier ailleurs, comme sur des forums ou dans des emails.\n\nLes autres utilisateurs de Rematch peuvent alors coller ces équipes dans leur Rematch via Importer des équipes.\n\nVous pouvez exporter une simple équipe en faisant un clic-droit dessus et en délectionnant le menu Partager."
	L["Delete Tab"] = "Supprimer l'onglet"
	L["Delete this tab and move all of its teams to the default tab."] = "Supprime cet onglet et déplace toutes ses équipes dans l'onglet par défaut."
	L["Create New Tab"] = "Créer un nouvel onglet"
	L["Teams: %d"] = "Équipes : %d"
	L["New Tab"] = "Nouvel onglet"
	L["Choose a name and icon"] = "Choisissez un nom et une icône"
	L["Delete this tab?"] = "Supprimer cet onglet ?"
	L["Deleting this tab will move its teams to the %s tab."] = "Supprimer cet onglet déplacera ses équipes vers l'onglet %s."

-- Widgets\LoadedTeamPanel.lua
	L["Reload Team"] = "Recharger l'équipe"
	L["When a team is loaded its name goes here. You can reload the team by clicking here or right-click for team options such as setting notes."] = "Lorsqu'une équipe est chargée son nom apparaît ici. Vous pouvez recharger l'équipe en cliquant ici ou en cliquant droit pour les options d'équipe, comme écrire une note."
	L["Last Loaded Team"] = "Dernière équipe chargée"

-- Dialogs\Save.lua
	L["Target For This Team"] = "Cible pour cette équipe"
	L["A target stored in a team is used to decide which team to load when you return to that target.\n\nYou can save an unlimited number of teams to fight a target, but a target can only be saved in one team."] = "Une cible définie dans une équipe permet de décider quelle équipe charger quand vous retourner voir cette cible.\n\nVous pouvez enregistrer un nombre illimité d'équipes pour battre une cible, mais une cible peut uniquement être enregistrée dans une équipe."
	L["Name:"] = "Nom :"
	L["Target:"] = "Cible :"
	L["Save As.."] = "Sauver sous..."
	L["Save this team?"] = "Enregistrer cette équipe ?"
	L["Save Notes & Preferences Too"] = "Enregistrer aussi les notes et les préférences"
	L["All teams must have a name."] = "Toutes les équipes doivent avoir un nom."
	L["This target already has a team."] = "Cette cible a déjà une équipe."
	L["A team already has this name."] = "Une équipe possède déjà ce nom."
	L["Overwrite Team"] = "Écraser l'équipe"
	L["Overwrite this team?"] = "Écraser cette équipe ?"
	L["The target %s%s\124r already has a team.\n\nA target can only have one team."] = "La cible %s%s\124r possède déjà une équipe.\n\nUne cible ne peut avoir qu'une seule équipe."
	L["A team named %s%s\124r already exists.\n\nTeams without a target must have a unique name."] = "Une équipe nommée %s%s\124r existe déjà.\n\nLes équipes sans cible doivent avoir un nom unique."

-- Dialogs\Preferences.lua
	L["Minimum Health"] = "Vie minimale"
	L["This is the minimum health preferred for a leveling pet.\n\nThe queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = "Il s'agit du nombre de points de vie minimum préféré pour une mascotte de leveling.\n\nLa file préfèrera les mascottes de leveling avec au moins ce nombre de point de vie (ajusté en fonction des dégâts subis attendus le cas échéant)."
	L["Minimum Level"] = "Niveau minimum"
	L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = "Il s'agit du niveau minimum préféré pour une mascotte de leveling.\n\nLes niveaux peuvent être des nombres partiels. Le niveau 4.33 correspond au niveau 4 avec 33% d'xp pour atteindre le niveau 5."
	L["Maximum Health"] = "Vie maximale"
	L["This is the maximum health preferred for a leveling pet."] = "Il s'agit du nombre maximum de points de vie préféré pour une mascotte de leveling."
	L["Maximum Level"] = "Niveau maximum"
	L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = "Il s'agit du niveau maximum préféré pour une mascotte de leveling.\n\nLes niveaux peuvent être des nombres partiels. Le niveau 23.45 correspond au niveau 23 avec 45% d'xp pour atteindre le niveau 24."
	L["Or any"] = "Ou tout"
	L["Allow low-health Magic and Mechanical pets to ignore the Minimum Health, since their racials allow them to often survive a hit that would ordinarily kill them."] = "Autorise les mascottes de types Magique ou Mécanique avec un faible niveau de vie à ignorer la Vie minimale, puisque leurs races leur permet souvent de survivre à un coup qui les aurait tué normalement."
	L["Expected Damage Taken"] = "Dégâts subis attendus"
	L["Tab"] = "Onglet"
	L["Team Preferences"] = "Préférences d'équipe"
	L["Tab Preferences"] = "Préférences d'onglet"
	L["  For %s pets: %s%d%s"] = "  Pour les mascottes %s : %s%d%s"
	L["%s %sTab Preferences"] = "%s Préférences de l'onglet %s"
	L["%s%s Preferences Paused"] = "%s%s Préférences suspendues"
	L["%s Resume Preferences"] = "%s Reprendre les préférences"
	L["%s Pause Preferences"] = "%s Suspendre les préférences"
	L["Leveling Preferences For %s:"] = "Préférences de leveling pour %s :"
	L["Expected damage taken"] = "Dégâts subis attendus"
	L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = "Les points de vie minimum des mascottes peuvent être ajustés en fonction du type de dégâts qu'ils s'attendent à recevoir."
	L["Damage expected"] = "Dégâts subis"
	L["  For %s pets: \124cffffd200%d"] = "  Pour les mascottes %s : \124cffffd200%d"

-- Dialogs\Sideline.lua
	L["New Team"] = "Nouvelle équipe"

-- Dialogs\Share.lua
	L["^(.-)%(.-NPC#(%d+)%)"] = nil
	L[":([^\n]-)[%(%[]*([12]).([12]).([12])[%)%]]*.-[\n]*"] = nil
	L[":([^\n]+)"] = nil
	L["\n%s*Preferred leveling pets: ([^\n]+)%."] = "\n%s*Mascottes de leveling préférées : ([^\n]+)%."
	L["at least (%d+) health"] = "au moins (%d+) de vie"
	L["or any Magic/Mechanical"] = "ou toute Magique/Mécanique"
	L[".+[,%(](.-)damage expected%)"] = ".+[,%(](.-)dégâts attendus%)"
	L["at most (%d+) health"] = "au mieux (%d+) de vie"
	L["at least level ([%d%.]+)"] = "au moins niveau ([%d%.]+)"
	L["at most level ([%d%.]+)"] = "au mieux niveau ([%d%.]+)"
	L["^[Ll][Ee][Vv][Ee][Ll][Ii][Nn][Gg] [Pp][Ee][Tt]$"] = nil
	L["^[Cc][Aa][Rr][Rr][Yy] [Pp][Ee][Tt]$"] = nil
	L["%s (NPC#%d)"] = nil
	L["%s (%s NPC#%d)"] = nil
	L["%d: %s"] = nil
	L["%d: %s (%d,%d,%d)"] = nil
	L["Preferred leveling pets: %s."] = "Mascottes de leveling préférées : %s."
	L["at least %d health"] = "au moins %d de vie"
	L["at least %d health (or any Magic/Mechanical)"] = "au moins %d de vie (ou toute Magique/Mécanique)"
	L["at least %d health (%s damage expected)"] = "au moins %d de vie (%s dégâts attendus)"
	L["at least %d health (or any Magic/Mechanical, %s damage expected)"] = "au moins %d de vie (ou toute Magique/Mécanique, %s dégâts attendus)"
	L["at most %d health"] = "au mieux %d de vie"
	L["at least level %s"] = "au moins niveau %s"
	L["at most level %s"] = "au mieux niveau %s"
	L["Export Team"] = "Exporter l'équipe"
	L["Press Ctrl+C to copy these teams to the clipboard."] = "Faites Ctrl+C pour copier ces équipes dans le presse-papier."
	L["Press Ctrl+C to copy this team to the clipboard."] = "Faites Ctrl+C pour copier cette équipe dans le presse-papier."
	L["Include Preferences"] = "Inclure les préférences"
	L["Include Notes"] = "Inclure les notes"
	L["Press Ctrl+V to paste a team from the clipboard."] = "Faites Ctrl+V pour coller une équipe depuis le presse-papier."
	L["This is not a recognizable team."] = "Il ne s'agit pas d'une équipe reconnue."
	L["An existing team already has this %s."] = "Une équipe existante possède déjà %s."
	L["target"] = "cible"
	L["name"] = "nom"
	L["Create a new copy"] = "Créer une nouvelle copie"
	L["Overwrite existing team"] = "Écraser l'équipe existante"
	L["%s%d\124r teams are in this import."] = "%s%d\124r équipes sont dans cet import."
	L["%s%d\124r have a name or target already used."] = "%s%d\124r possède un nom ou une cible déjà utilisé."
	L["Create new copies"] = "Créer de nouvelles copies"
	L["Overwrite existing teams"] = "Écraser les équipes existantes"
	L["Send"] = "Partager"
	L["Who do you want to send this team to?"] = "À qui souhaitez-vous envoyer cette équipe ?"
	L["Sending..."] = "Envoi..."
	L["No response. Lag or they don't have Rematch?"] = "Pas de réponse. Délai trop long ou le joueur ne possède pas Rematch ?"
	L["Team successfully received!"] = "Équipe correctement reçue !"
	L["Sending...%d%%"] = "Envoi...%d%%"
	L["They're busy. Try again later."] = "Le joueur est occupé. Réessayez plus tard."
	L["They're in combat. Try again later."] = "Le joueur en combat. Réessayez plus tard."
	L["They have team sharing disabled."] = "Le joueur a désactivé le partage d'équipe."
	L["Incoming Rematch Team!"] = "Équipe Rematch en arrivée !"
	L["%s%s\124r has sent you a team named \"%s\" (for %s)."] = "%s%s\124r vous a envoyé une équipe nommée \"%s\" (pour %s)."
	L["%s%s\124r has sent you a team for %s."] = "%s%s\124r vous a envoyé une équipe pour %s."
	L["%s%s\124r has sent you a team named \"%s\"."] = "%s%s\124r vous a envoyé une équipe nommée \"%s\"."
	L["Import these teams?"] = "Importer ces équipes ?"
	L["Import"] = "Importer"
	L["%s%d\124r Rematch teams have the same name."] = "%s%d\124r équipes Rematch ont le même nom."
	L["Please Wait..."] = "Patienter..."
	L["Note: These are just your teams and their notes and preferences. Tab information, sort orders, win records, specific breeds and other settings are not included.\n\nFor the most complete backup of all your addon data, please backup your Word of Warcraft\\WTF folder."] = "À noter : Il n'y a que vos équipes et leurs notes et préférences. L'onglet d'information, les ordres de tri, les victoires, les races spécifiques et les autres paramètres ne sont pas inclus.\n\nPour une sauvegarde plus complète de toutes les données de votre addon, merci de sauvegarder votre dossier World of Warcraft\\WTF."
	L["Press Ctrl+C to copy these teams to the clipboard. Then paste them into an email to yourself or a text file someplace safe.\n\nIf you ever need to restore your teams, paste them back in with Import Teams."] = "Faites Ctrl+C pour copier ces équipes dans le presse-papier. Puis coller-les dans un email que vous vous envoyez ou dans un fichier texte dans un endroit sûr.\n\nSi vous avez besoin de restaurer vos équipes, collez-les de nouveau dans Importer des équipes."
	L["Backup All Rematch Teams?"] = "Sauvegarder toutes les équipes Rematch ?"
	L["You have %s%d\124r Rematch teams.\n\nWould you like to back them up?"] = "Vous avez %s%d\124r équipes Rematch.\n\nSouhaitez-vous les sauvegarder ?"
	L["Choosing Yes will export all teams to copy and paste in an email to yourself or someplace safe.\n\nYou can also do this at any time from the Teams button at the top of the Teams panel of Rematch."] = "En choisissant Oui cela exportera toutes les équipes pour les copier-coller dans un email à vous-même ou dans un endroit sûr.\n\nVous pouvez aussi faire cela à tout moment depuis le bouton Équipes en haut du panneau d'équipes de Rematch."

-- Dialogs\Tooltip.lua

-- Dialogs\ScriptFilter.lua
	L["Pet Variables"] = "Variables de mascotte"
	L["Exposed API"] = "API disponible"
	L["Test"] = "Test"
	L["line "] = "Ligne"
	L["Pet Filter Script Error"] = "Erreur de script de filtre de mascotte"
	L["Error in %s"] = "Erreur dans %s"
	L["\124TInterface\\RaidFrame\\ReadyCheck-NotReady:16\124t Error %s"] = nil
	L["\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t Script ran without errors!"] = "\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t Le script s'est exécuté sans erreur !"
	L["\124cffffd200-\124r Scripts are a way to create custom pet filters.\n\n\124cffffd200-\124r Scripts are Lua code and require some knowledge of the language and API to create your own filters.\n\n\124cffffd200-\124r Scripts run for each pet and should return true if the pet is to be listed.\n\n\124cffffd200-\124r Some variables are filled in as the script runs for each pet. See \124cffffd200Pet Variables\124r.\n\n\124cffffd200-\124r Scripts run in a restricted environment with no access outside its environment. See \124cffffd200Exposed API\124r.\n\n\124cffffd200-\124r All variables/tables created exist only in this environment and disappear when the filter finishes.\n\n\124cffffd200-\124r If the first line of the script is a --comment, it will be used as a tooltip in the Script menu."] = "\124cffffd200-\124r Les scripts sont un moyen de créer des filtres de mascotte.\n\n\124cffffd200-\124r Les scripts sont écrits avec du code Lua et exigent quelques connaissances du langage et de l'API pour créer vos propres filtres.\n\n\124cffffd200-\124r Les scripts s'exécutent pour chaque mascotte et retournent true si la mascotte doit être listée.\n\n\124cffffd200-\124r Plusieurs variables sont remplies au fur et à mesure que le script s'exécute pour chaque mascotte. Voir \124cffffd200Variables de mascotte\124r.\n\n\124cffffd200-\124r Les scripts s'exécutent dans un environnement restreint sans aucun accès en dehors de cet environnement. Voir \124cffffd200API disponible\124r.\n\n\124cffffd200-\124r Toutes les variables/tables créées n'existent que dans cet environnement et disparaissent lorsque le filtre a fini.\n\n\124cffffd200-\124r Si la première ligne du script est --comment, elle sera utilisée comme infobulle dans le menu du script."
	L["These variables are defined as the script runs for each pet:\n\n\124cffffd200owned\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is owned by the player.\n\n\124cffffd200petID\124r \124cffaaaaaa(string)\124r\nUnique ID of the owned pet, such as \"BattlePet-0-000004A98F18\".\n\n\124cffffd200speciesID\124r \124cffaaaaaa(number)\124r\nShared ID of the pet's family. Black Tabby Cats are species 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(string)\124r\nName given to the pet by the player.\n\n\124cffffd200level\124r \124cffaaaaaa(number)\124r\nLevel of the pet, or nil for uncollected pets.\n\n\124cffffd200xp\124r \124cffaaaaaa(number)\124r\nAmount of xp the pet has in its current level.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(number)\124r\nTotal amount of xp required to reach the pet's next level.\n\n\124cffffd200displayID\124r \124cffaaaaaa(number)\124r\nA numeric representation of a pet's model skin.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is favorited by the player.\n\n\124cffffd200name\124r \124cffaaaaaa(string)\124r\nTrue name of the pet species.\n\n\124cffffd200icon\124r \124cffaaaaaa(string)\124r\nTexture path of the pet's icon.\n\n\124cffffd200petType\124r \124cffaaaaaa(number)\124r\nValue between 1 and 10 for its type. 1=Humanoid, 2=Dragonkin, etc.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(number)\124r\nThe npcID of the pet when it's summoned.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(string)\124r\nFormatted text describing where the pet is from.\n\n\124cffffd200description\124r \124cffaaaaaa(string)\124r\nLore text of the species.\n\n\124cffffd200isWild\124r \124cffaaaaaa(boolean)\124r\nWhether the pet was a captured wild pet.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can battle.\n\n\124cffffd200tradable\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can be caged.\n\n\124cffffd200unique\124r \124cffaaaaaa(boolean)\124r\nWhether no more than one of the pet can be known at a time.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(table)\124r\nArray of abilityIDs used by the species.\n\n\124cffffd200levelList\124r \124cffaaaaaa(table)\124r\nArray of levels the abilityIDs are learned."] = "Ces variables sont définies lors de l'exécution du script pour chaque mascotte :\n\n\124cffffd200owned\124r \124cffaaaaaa(boolean)\124r\nLa mascotte est détenue par le joueur.\n\n\124cffffd200petID\124r \124cffaaaaaa(string)\124r\nID unique de la mascotte possédée, par exemple \"BattlePet-0-000004A98F18\".\n\n\124cffffd200speciesID\124r \124cffaaaaaa(number)\124r\nID partagé de la famille de mascotte. Les Chats tigrés noirs ont un ID d'espèce à 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(string)\124r\nNom donné à la mascotte par le joueur.\n\n\124cffffd200level\124r \124cffaaaaaa(number)\124r\nNiveau de la mascotte, ou nil pour les mascottes non collectées.\n\n\124cffffd200xp\124r \124cffaaaaaa(number)\124r\nLe nombre d'xp que possède la mascotte au niveau actuel.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(number)\124r\nNombre total d'xp nécessaire pour atteindre le niveau suivant.\n\n\124cffffd200displayID\124r \124cffaaaaaa(number)\124r\nUne représentation numérique du modèle de présentation.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(boolean)\124r\nIndique si la mascotte est taggée comme favortie par le joueur.\n\n\124cffffd200name\124r \124cffaaaaaa(string)\124r\nVrai nom de l'espèce de mascotte.\n\n\124cffffd200icon\124r \124cffaaaaaa(string)\124r\nChemin d'accès à la texture de l'icône de mascotte.\n\n\124cffffd200petType\124r \124cffaaaaaa(number)\124r\nValeur entre 1 et 10 pour ce type. 1=Humanoïde, 2=Draconien, etc.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(number)\124r\nL'ID de PNJ de la mascotte lorsqu'elle est invoquée.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(string)\124r\nTexte mis en forme décrivant d'où vient la mascotte.\n\n\124cffffd200description\124r \124cffaaaaaa(string)\124r\nTexte original de l'espèce.\n\n\124cffffd200isWild\124r \124cffaaaaaa(boolean)\124r\nIndique si la mascotte était une mascotte sauvage capturée.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(boolean)\124r\nIndique si la mascotte peut se battre.\n\n\124cffffd200tradable\124r \124cffaaaaaa(boolean)\124r\nIndique si la mascotte peut être mise en cage.\n\n\124cffffd200unique\124r \124cffaaaaaa(boolean)\124r\nIndique qu'il s'agit d'une mascotte unique.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(table)\124r\nTableau d'ID de compétences utilisées par la mascotte.\n\n\124cffffd200levelList\124r \124cffaaaaaa(table)\124r\nTableau indiquant le niveau auquel la compétence est acquise."
	L["The script environment is restricted with access to only common Lua and the following:\n\n\124cffffd200C_PetJournal \124cffaaaaaa(table)\124r\nThe default API for journal functions.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(table)\124r\nThe default API for the battle UI.\n\n\124cffffd200GetBreed \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r The numeric breed (3-12) of a petID if one of the supported breed addons is enabled.\n\n\124cffffd200GetSource \124cffaaaaaa(function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The numeric source (1-10) of a speciesID. 1=Drop, 2=Quest, etc.\n\nA few iterator functions are also provided if you need to compare a pet against others. These are used in a for loop such as:\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- do something with speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next speciesID of all existing unique pets.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next petID of all owned pets.\n\n\124cffffd200AllPets \124cffaaaaaa(iterator function)\nReturns:\124r The next petID or speciesID of all pets in the master list. Owned pets return a petID string, uncollected pets return a speciesID number.\n\n\124cffffd200AllAbilities \124cffaaaaaa(iterator function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The next abilityID and level of the ability for a speciesID.\n\124cffffd200Note:\124r abilityList and levelList are already defined for each pet as your script runs. Use this iterator if you need to gather abilities of other pets for comparison. See the Unique Abilities script for an example.\n\n\124cffffd200If you would like anything else exposed please post a comment on wowinterface, curse or warcraftpet's Rematch 4.0 thread."] = "L'environnement de script est restreint à un accès au Lua commun et à ce qui suit :\n\n\124cffffd200C_PetJournal \124cffaaaaaa(table)\124r\nl'API par défaut pour les fonctions du codex.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(table)\124r\nL'API par défaut pour l'interface des combats.\n\n\124cffffd200GetBreed \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r La race numérique (3-12) d'un petID si un des addons de race supportés est activé.\n\n\124cffffd200GetSource \124cffaaaaaa(function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r La source numérique (1-10) d'un speciesID. 1=Abandon, 2=Quête, etc.\n\nQuelques fonctions d'itération sont aussi disponibles si vous avez besoin de comparer une mascotte face à une autre. Elles sont utilisée dans une boocle for comme :\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- faire quelque chose avec le speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(iterator function)\nReturns:\124r Le speciesID suivant parmi toutes les mascottes uniques existantes.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(iterator function)\nReturns:\124r Le petID suivant parmi toutes les mascottes détenues.\n\n\124cffffd200AllPets \124cffaaaaaa(iterator function)\nReturns:\124r Le petID ou le speciesID suivant parmi toutes les mascottes de la liste principale. Les mascottes obtenues retournent une chaîne de petID, les mascottes non détenues retournent un nombre speciesID.\n\n\124cffffd200AllAbilities \124cffaaaaaa(iterator function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r Le abilityID et le niveau de la compétence pour un speciesID.\n\124cffffd200À noter :\124r abilityList et levelList sont déjà définis pour chaque mascotte au fur et à mesure que votre script s'exécute. Utilisez cet itérateur si vous avez besoin de recueillir les compétences des autres mascottes pour comparer. Voir le script de compétences uniques pour un exemple.\n\n\124cffffd200Si vous souhaitez voir autre chose exposé, merci de poster un commentaire sur wowinterface, curse ou le sujet Rematch 4.0 de warcraftpet."

-- Dialogs\Collection.lua
	L["Total Collected Pets"] = "Mascottes totales collectées"
	L["Unique Collected Pets"] = "Mascottes uniques collectées"
	L["Pets Not Collected"] = "Mascottes non collectées"
	L["Percent Collected"] = "Pourcentage collecté"
	L["Max Level Pets"] = "Mascottes niveau max"
	L["Rare Quality Pets"] = "Mascottes rares"
	L["Unique Pets In The Game"] = "Mascottes uniques dans le jeu"
	L["Collection Statistics"] = "Statistiques de la collection"
	L["There are %s%d\124r unique pets in the game."] = "Il y a %s%d\124r mascottes uniques dans le jeu."
	L["Pets Collected"] = "Mascottes collectées"
	L["Pets At Max Level"] = "Mascottes niveau max"
	L["Total"] = "Total"
	L["Unique"] = "Unique"
	L["Duplicate Collected Pets"] = "Mascottes en double"
	L["Average Battle Pet Level"] = "Niveau moyen de mascotte"
	L["You have %s%.1f%%\124r of all unique pets."] = "Vous avez %s%.1f%%\124r de mascottes uniques."
	L["All unique pets in the game."] = "Toutes les mascottes unique dans le jeu."
	L["All pets you've collected, including duplicates."] = "Toutes les mascottes collectées, incluant les doublons."
	L["The unique pets you've collected, not including duplicates."] = "Les mascottes uniques que vous avez collecté, incluant les doublons."
	L["The unique pets you're missing."] = "Les mascottes uniques manquantes."
	L["How much of each category's unique pets you've collected as a percent."] = "Combien de mascotte de chaque catégorie unique vous avez collecté en pourcentage."
	L["All of your level 25 pets, including duplicates."] = "Toutes vos mascottes niveau 25, incluant les doublons."
	L["All of your rare quality pets, including duplicates."] = "Toutes vos mascottes rares, incluant les doublons."
	L["Pet Types"] = "Types"
	L["Sources"] = "Sources"

-- Frames\Frame.lua
	L["Pets"] = "Mascottes"
	L["Options"] = "Options"
	L["Toggle Single Panel Mode"] = "Basculer en mode 1 panneau"
	L["Toggle between one panel or two panels side by side."] = "Basculer entre un panneau et deux panneaux côte à côte."
	L["You are in combat. Try again when out of combat."] = "Vous êtes en combat. Réessayez lorsque vous n'y serez plus."

-- Frames\Configure.lua

-- Frames\Journal.lua
	L["Enable Rematch"] = "Activer Rematch"
	L["Check this to use Rematch in the pet journal."] = "Cochez cette case pour uiliser Rematch dans le journal de mascottes."

-- Frames\Battle.lua

-- Process\Battle.lua
	L["Show Pet Card"] = "Voir la fiche de mascotte"

-- Process\Breeds.lua
end
