local _,L = ...

if GetLocale()=="koKR" then

-- 추가    로컬 없는 거
--	L["Loaded Team"] = "불러온 팀" -- Panels\TeamPanel.xml
--	L["Current Leveling Pet"] = "현재 평준화 애완동물" -- Panels\QueuePanel.xml
--  L["Name:"] = "이름:" -- Save.xml
--  L["Target:"] = "대상:" -- Save.xml
  L["Cage this pet?"] = "이 애완동물을 우리에 넣습니까?" -- Menus\PetMenus.lua
  L["This pet is already in the queue and Active Sort is enabled.\n\nWhile enabled, the queue has complete control over the order of pets in the queue.\n\nDo you want to turn off Active Sort to move this pet in the queue?"] = "이 애완동물은 이미 대기열 있고 정렬 활성화를 사용하고 있습니다.\n\n사용하는 동안, 대기열은 대기열에 있는 애완동물의 순서를 완벽하게 제어 할 수 있습니다.\n\n대기열에서 이 애완동물을 이동하기 위해 정렬 활성화를 끄시겠습니까?" -- QueuePanel.lua
-- 추가

-- Main.lua
	L["Rematch"] = nil
	L["Toggle Window"] = "창 전환"
	L["Auto Load"] = "자동 부르기"
	L["Team Notes"] = "팀 노트"
	L["Pets Tab"] = "애완동물 탭"
	L["Teams Tab"] = "팀 탭"
	L["Queue Tab"] = "대기 탭"
	L["Toggle Rematch"] = "Rematch 전환"
	L["Load this team?"] = "이 팀을 불러옵니까?"
	L["They do not appear to be online."] = "그들은 온라인으로 나타나지 않습니다."
	L["has also been added to your leveling queue!"] = "또한 평준화 대기열에 추가되었습니다!"
	L["The team named '%s' can't be found."] = "'%s' 팀 이름을 찾을 수 없습니다."

-- Utils.lua
	L["Leveling Pet"] = "평준화 애완동물"

-- Widgets\PetListButtons.lua
	L["The Leveling Queue Is Empty"] = "평준화 대기열이 비어 있음"
	L["Empty Battle Pet Slot"] = "애완동물 대전 칸 비었음"
	L["This pet can't level."] = "이 애완동물은 레벨을 올릴 수 없습니다."
	L["Only pets that can battle and are under 25 can go in the leveling queue."] = "평준화 대기열에는 대전이 가능하고 25레벨 미만의 애완동물만 들어갈 수 있습니다."

-- Widgets\Toolbar.lua
	L["Dismiss Pet"] = "애완동물 해제"
	L["Summon Pet"] = "애완동물 소환"
	L["Random Favorite"] = "즐겨찾기 무작위"
	L["Random From All"] = "전체에서 무작위"
	L["All pets are at full health."] = "모든 애완동물 체력 꽉 참."

-- Widgets\MinimapButton.lua
	L["Load Favorite Team"] = "즐겨찾기 팀 부르기"
	L["Favorite Teams"] = "즐겨찾기 팀"

-- Widgets\PanelTabs.lua

-- Process\PetLoading.lua
	L["You can't load a team during combat."] = "전투 중에 팀을 불러올 수 없습니다."
	L["You can't load a team during a pet battle."] = "애완동물 대전 중에 팀을 불러올 수 없습니다."
	L["You can't load a team in a matched pet battle."] = "애완동물 대전 찾기 중에 팀을 불러올 수 없습니다."
	L["Loading..."] = "불러오는 중..."
	L["Pets are missing from this team!"] = "애완동물이 이 팀에서 누락되었습니다!"
	L["Substitutes were found. Please review the loaded team and click Save if you'd like to keep the chosen pets."] = "대체품을 찾앗습니다. 불러온 팀을 검토하고 선택한 애완동물을 유지하려면 저장을 누르십시오."
	L["Don't Warn About Missing Pets"] = "애완동물 누락에 대한 경고 안 함"

-- Process\Roster.lua
	L["Favorites"] = "즐겨찾기"
	L["Types"] = "유형"
	L["Strong Vs"] = "강한 대상"
	L["Tough Vs"] = "약한 대상"
	L["Breed"] = "품종"
	L["Similar"] = "비슷"
	L["Script"] = "스크립트"
	L["Level"] = "레벨"
	L["Leveling"] = "평준화"
	L["Tradable"] = "거래 가능"
	L["Battle"] = "대전"
	L["Quantity"] = "수량"
	L["Team"] = "팀"
	L["Hidden"] = "숨겨짐"
	L["Zone"] = "지역"
	L["Notes"] = "노트"
	L["Search"] = "검색"
	L["Sort"] = "정렬"

-- Process\QueueProcess.lua
	L["All done leveling pets!"] = "애완동물 평준화 모두 완료!"
	L["Rematch's leveling queue is empty"] = "Rematch의 평준화 대기열이 비어 있음"
	L["Now leveling:"] = "지금 평준화:"

-- Process\Sanctuary.lua

-- Menus\Menu.lua
	L["Help"] = "도움말"

-- Menus\TeamMenus.lua
	L["Unload Team"] = "팀 내리기"
	L["Edit Team"] = "팀 편집"
	L["Set Notes"] = "노트 설정"
	L["Set Preferences"] = "우선권 설정"
	L["Move To"] = "이동"
	L["Move To Top"] = "제일 위로 이동"
	L["Move Up"] = "위로 이동"
	L["Move Down"] = "아래로 이동"
	L["Move To End"] = "제일 끝으로 이동"
	L["Share"] = "공유"
	L["Delete this team?"] = "이 팀을 삭제합니까?"
	L["Put Leveling Pet Here"] = "여기에 평준화 애완동물 넣기"
	L["Add a leveling pet to this team?"] = "이 팀에 평준화 애완동물을 추가하시겠습니까?"
	L["Export As Plain Text"] = "일반 글자로 내보내기"
	L["Export this team in plain text that you can copy elsewhere, such as forums or emails.\n\nThe plain text format is best for sharing a team with others that may not use Rematch.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "포럼이나 이메일과 같이 다른 곳에 일반 글자로 복사해 내보낼 수 있습니다.\n\n일반 글자 형식은 하나의 팀을 공유하기에 가장 좋고 다른 형식은 Rematch에 사용할 수 없습니다.\n\nRematch의 팀 가져오기를 통해 다른 Rematch 사용자는 이 팀을 붙여넣을 수 있습니다."
	L["Export As String"] = "문자열로 내보내기"
	L["Export this team as a string you can copy elsewhere, such as forums or emails.\n\nThe string format is best for copying multiple teams to be imported together, or for sharing teams with someone in another language.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "포럼이나 이메일과 같이 다른 곳에 문자열로 복사해 내보낼 수 있습니다.\n\n문자열 형식은 여러 팀을 복사해 함께 가져올 때 가장 좋으며, 다른 언어권에 있는 사람들과 팀을 공유할 수 있습니다.\n\nRematch의 팀 가져오기를 통해 다른 Rematch 사용자는 이 팀을 붙여넣을 수 있습니다."
	L["Import Team"] = "팀 가져오기"
	L["Import a single team or many teams that was exported from Rematch."] = "Rematch에서 내보낸 단일 팀 또는 여러 팀을 가져옵니다."
	L["Send Team"] = "팀 보내기"
	L["Send this team to another online user of Rematch."] = "Rematch의 또 다른 온라인 사용자에게 이 팀을 보냅니다."
	L["Prompt To Load"] = "확인 창 부르기"
	L["When your new target has a saved team not already loaded, and the target panel isn't on screen, display a popup asking if you want to load the team.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "새 대상의 저장된 팀이 불려있지 않거나 대상 패널이 화면에 없을 때, 팀을 불러올지를 묻는 팝업 창을 표시합니다.\n\n이것은 대상과의 첫 상호 작용만을 위한 것입니다. 여러분은 항상 대상 패널에서 대상의 팀을 불러올 수 있습니다."
	L["With Rematch Window"] = "대신 Rematch 창"
	L["Prompt to load with the Rematch window instead of a separate popup dialog."] = "별도의 팝업 창 대신 Rematch 창으로 확인 창을 부릅니다."
	L["Always Prompt"] = "항상 확인 창"
	L["Prompt every time you interact with a target with a saved team not already loaded, instead of only the first time."] = "첫 대상일 때 만 말고, 저장된 팀이 불려있지 않은 대상과 상호 작용할 때마다 확인 창을 나타냅니다."
	L["When you mouseover a new target that has a saved team not already loaded, immediately load it.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "저장된 팀이 불려있지 않은 대상에 마우스를 갖다 댈 때, 즉시 불러옵니다.\n\n이것은 대상과의 첫 상호 작용만을 위한 것입니다. 여러분은 항상 대상 패널에서 대상의 팀을 불러올 수 있습니다."
	L["Show After Loading"] = "불러온 후 표시"
	L["After a team auto loads, show the Rematch window."] = "팀을 자동으로 불러온 후, Rematch 창을 표시합니다."
	L["Show On Injured"] = "부상 표시"
	L["When a team auto loads, show the Rematch window if any pets are injured."] = "팀을 자동으로 불러올 때, 어떤 애완동물이 다쳤는지 Rematch 창에 표시합니다."
	L["On Target Only"] = "대상일 때 만"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right click!"] = "마우스오버가 아닌, 대상으로 지정됐을 때만 자동으로 불러옵니다.\n\n\124cffff4040경고!\124r 이것은 권장하지 않습니다! 당신이 대상을 우-클릭할 경우 애완동물을 불러오기에 너무 늦을 수 있습니다!"
	L["Export Listed Teams"] = "팀 목록 내보내기"
	L["Export all teams listed below to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "포럼이나 전자우편과 같이 다른 곳에 문자열로 아래의 모든 팀 목록을 내보낼 수 있습니다.\n\nRematch의 팀 가져오기를 통해 다른 Rematch 사용자는 그 팀을 붙여넣을 수 있습니다.\n\n하나를 우-클릭하고 공유 메뉴를 선택해 하나의 팀을 내보낼 수도 있습니다."
	L["Import Teams"] = "팀 가져오기"
	L["Import From Pet Battle Teams"] = "애완동물 대전 팀에서 가져오기"
	L["Copy your existing teams from Pet Battle Teams to Rematch."] = "Rematch에 애완동물 대전 팀으로 기존의 팀을 복사합니다."

-- Menus\PetMenus.lua
	L["Unnamed Pets"] = "무명 애완동물"
	L["Partially Leveled"] = "부분 평준됨"
	L["Unique Abilities"] = "고유 능력"
	L["Pets Without Rares"] = "희귀가 없는 애완동물"
	L["Hybrid Counters"] = "하이브리드 카운터"
	L["Find Similar"] = "비슷한 것 찾기"
	L["Enter a new name"] = "새 이름 입력"
	L["List %d Teams"] = "%d 팀 목록"
	L["Hide Pet"] = "애완동물 숨김"
	L["Unhide Pet"] = "애완동물 숨김 해제"
	L["Release this pet?"] = "이 애완동물을 놓아줍니까?"
	L["Once released, this pet is gone forever!"] = "한번 놓아주면, 이 애완동물은 영원히 사라집니다!"
	L["Start Leveling"] = "평준화 시작"
	L["Add To Leveling Queue"] = "평준화 대기열에 추가"
	L["Stop Leveling"] = "평준화 정지"
	L["Only Favorites"] = "즐겨찾기 만"
	L["Favorite Filters"] = "즐겨찾기 필터"
	L["Pet Filter"] = "애완동물 필터"
	L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r"] = "이 메뉴의 필터 외에도, 추가로 검색 상자와 애완동물 목록을 구체화 할 수 있습니다. 몇 가지 검색 예:\n\n애완동물: %s검은얼룩\124r\n지역: %s실리더스\124r\n능력: %s모래폭풍\124r\n능력 안에 글자: %s출혈\124r\n레벨: %slevel=21-23\124r\n능력치: %sspeed>300\124r"
	L["Reset All"] = "전부 초기화"
	L["Checkbox Groups"] = "체크박스 그룹"
	L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = "필터 메뉴에서 체크박스 그룹을 아무것도 선택하지 않으면 모두 선택한 것으로 간주됩니다.\n\n하나 더:%s\n\n[Shift]+클릭\124r으로 선택한 박스를 제외하고 모두 선택.%s\n\n[Alt]+클릭\124r으로 선택한 박스를 제외하고 모두 선택 취소."
	L["Low Level (1-7)"] = "저 레벨 (1-7)"
	L["Mid Level (8-14)"] = "중 레벨 (8-14)"
	L["High Level (15-24)"] = "고 레벨 (15-24)"
	L["Max Level (25)"] = "최대 레벨 (25)"
	L["Without Any 25s"] = "25가 없는 모두"
	L["Moveset Not At 25"] = "25가 아닌 무브셋"
	L["You can filter to a specific level or range of levels in the search box. For example, search for:\n\n\%slevel=1\124r\nor\n\%slevel=21-23\124r"] = "검색 창에 레벨의 범위나 특정 레벨로 걸러낼 수 있습니다. 검색 예:\n\n\%slevel=1\124r\n또는\n\%slevel=21-23\124r"
	L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" categorizes pets with no breed data. Keep your breed addon up to date to see if they have new data."] = "%s%s\124r|1이;가; 설치된 애드온에서 모든 품종 자료를 얻습니다.\n\n품종 \"New\" 범주는 품종 자료가 없는 애완동물입니다.\n\n새로운 자료인 경우 품종 애드온을 갱신해 유지하십시오."
	L["Not Leveling"] = "평준화 안됨"
	L["Not Tradable"] = "거래 불가능"
	L["Can Battle"] = "대전 가능"
	L["Can't Battle"] = "대전 불가능"
	L["One Copy"] = "한 마리"
	L["Two+ Copies"] = "두 마리+"
	L["Three+ Copies"] = "세 마리+"
	L["In A Team"] = "팀에 있음"
	L["Not In A Team"] = "팀에 없음"
	L["Current Zone"] = "현재 지역"
	L["Hidden Pets"] = "숨긴 애완동물"
	L["Has Notes"] = "노트 있음"
	L["Reverse Sort"] = "역 정렬"
	L["Favorites First"] = "즐겨찾기 먼저"
	L["Sort By"] = "정렬 방식"
	L["You can filter to a specific range of stats too. For example, search for:\n\n\%shealth>500\124r\nor\n\%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = "능력치의 특정 범위를 걸러낼 수 있습니다. 검색 예:\n\n\%shealth>500\124r\n또는\n\%sspeed=200-300\124r\n\n필터가 초기화 될 때 정렬 순서는 일반적으로 초기화되지 않습니다. 필터를 초기화 할 때, 정렬을 초기화하길 원하시면 설정 탭 안에 %s필터로 정렬 초기화\124r를 설정합니다."
	L["Hide this pet?"] = "이 애완동물을 숨깁니까?"
	L["Don't Ask When Hiding Pets"] = "애완동물을 숨길 때 묻지 않기"
	L["Are you sure you want to hide all versions of %s%s\124r?\n\nHidden pets will not show up in the pet list or searches. You can view or unhide these pets in the 'Other' filter."] = "정말로 %s%s\124r의 버젼을 모두 숨기시겠습니까?\n\n숨겨진 애완동물은 애완동물 목록이나 검색에 표시되지 않습니다. '기타' 필터에서 이 애완동물을 보거나 숨길 수 있습니다."
	L["Save Filter"] = "필터 저장"
	L["Save this as a favorite filter?"] = "이 즐겨찾기 필터를 저장 하시겠습니까?"
	L["Filters: %s%s\124r\n\nChoose a name to use in the Favorite Filters menu:"] = "필터: %s%s\124r\n\n즐겨찾기 필터 메뉴에서 사용하는 이름을 선택:"
	L["Note: Search text and Sort order are not included in the filter."] = "참고: 글자를 검색하고 필터에 포함되지 않은 순서를 정렬합니다."
	L["Delete Filter"] = "필터 삭제"
	L["Are you sure you want to delete the filter named %s%s\124r?"] = "정말로 %s%s\124r 이라는 필터를 삭제하시겠습니까?"
	L["New Script"] = "새 스크립트"
	L["Create a new pet filter."] = "새 애완동물 필터를 만듭니다."
	L["Delete Script"] = "스크립트 삭제"
	L["Are you sure you want to delete the script named %s%s\124r?"] = "정말로 스크립트 이름 %s%s\124r|1을;를; 삭제하시겠습니까?"

-- Menus\Npcs.lua
	L["Eastern Kingdom"] = "동부 왕국"
	L["Kalimdor"] = "칼림도어"
	L["Outland"] = "아웃랜드"
	L["Northrend"] = "노스렌드"
	L["Cataclysm"] = "대격변"
	L["Pandaria"] = "판다리아"
	L["Beasts of Fable"] = "전설의 야수"
	L["Celestial Tournament"] = "천신의 시합"
	L["Draenor"] = "드레노어"
	L["Garrison"] = "주둔지"
	L["Menagerie"] = "동물원"
	L["Tanaan Jungle"] = "타나안 정글"
	L["No Target"] = "대상 없음"
	L["Noteworthy Targets"] = "주목할 만한 대상"
	L["These are noteworthy targets such as tamers and legendary pets.\n\nChoose one to view the pets you would battle.\n\nTargets with a \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t already have a team saved."] = "조련사와 전설 애완동물과 같은 주목할 만한 대상입니다.\n\n당신과 대전할 애완동물을 보려면 하나를 선택하십시오.\n\n\124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t 표식이 있는 대상은 이미 팀이 저장되어 있습니다."

-- Dialogs\Dialog.lua
	L["Tab:"] = "탭:"

-- Cards\PetCard.lua
	L["Vs"] = "대"
	L["Damage\nTaken"] = "받는\n피해"
	L["from"] = "에는"
	L["abilities"] = "능력"
	L["Unpin Pet Card"] = "애완동물 카드 고정 해제"
	L["While pinned, pet cards will display where you last moved it.\n\nClick this to unpin the pet card and snap it back to the pets."] = "고정되어 있는 동안엔 마지막으로 이동한 곳에 애완동물 카드가 표시됩니다.\n\n애완동물 카드의 고정을 해제하고 애완동물을 다시 원위치 시키려면 이것을 클릭합니다."
	L["Pet Card"] = "애완동물 카드"
	L["Hold [Alt] to view more about this pet."] = "이 애완동물에 대한 자세한 내용을 보시려면 [Alt] 고정."
	L["XP: %d/%d (%d%%)"] = "경험치: %d/%d (%d%%)"
	L["Possible Breeds"] = "가능한 품종"
	L["Slotted"] = "대전 칸"
	L["This pet is loaded in one of the three battle pet slots."] = "이 애완동물은 세 군데의 애완동물 대전 칸 중 한 곳에 사용되고 있습니다."
	L["Favorite"] = "즐겨찾기"
	L["This pet is marked as a Favorite from its right-click menu."] = "이 애완동물은 우-클릭 메뉴에서 즐겨찾기로 설정되어 있습니다."
	L["This pet is in Rematch's leveling queue."] = "이 애완동물은 Rematch의 평준화 대기열에 있습니다."
	L["Determines how stats are distributed.  All breed data is pulled from your installed %s%s\124r addon."] = "능력치를 분류할 방법을 결정합니다. 모든 품종의 자료는 설치된 %s%s\124r 애드온에서 가져옵니다."
	L["%d Teams"] = "%d 팀"
	L["Teams"] = "팀"
	L["The number of Rematch teams that includes this pet."] = "이 애완동물이 포함된 Rematch 팀의 수입니다."
	L["When this team loads, your current leveling pet will go in this spot."] = "이 팀을 부를 때, 현재 평준화 애완동물이 이 자리에 들어갑니다."
	L["This is an opponent pet."] = "이것은 상대의 애완동물입니다."
	L["All breed data pulled from %s%s\124r."] = "모든 품종의 자료는 %s%s\124r에서 가져옵니다."
	L["Stats At Level 25 \124cff0070ddRare"] = "\124cff0070dd희귀\124r 25 레벨에 능력치"
	L["No known breeds :("] = "품종 모름 :("

-- Cards\Notes.lua
	L["Pet Notes"] = "애완동물 노트"
	L["Delete Notes"] = "노트 삭제"
	L["Are you sure you want to delete the notes for %s\124r?"] = "정말로 %s\124r에 대한 노트를 삭제하시겠습니까?"

-- Panels\PetPanel.lua
	L["Strong vs"] = "강한 대상"
	L["Tough vs"] = "약한 대상"
	L["Pets: %s%d"] = "애완동물: %s%d"
	L["Filters: %s%s"] = "필터: %s%s"

-- Panels\LoadoutPanel.lua
	L["Target has a saved team"] = "대상에 저장된 팀 있음"
	L["Load"] = "불러오기"
	L["Load the team saved for this target."] = "이 대상을 위해 저장된 팀을 불러옵니다."
	L["This target has no saved team"] = "대상은 저장된 팀이 없습니다"
	L["Save the currently loaded pets to this target."] = "이 대상에 현재 불러온 애완동물을 저장합니다."

-- Panels\TeamPanel.lua

-- Panels\QueuePanel.lua
	L["Ascending Level"] = "레벨 오름차순"
	L["Descending Level"] = "레벨 내림차순"
	L["Median Level"] = "레벨 중간값"
	L["Type"] = "유형"
	L["Queue paused."] = "대기열 일시 정지"
	L["Queue paused while in combat."] = "전투에 있는 동안 대기열이 정지됐습니다."
	L["Queue paused while in a pet battle."] = "애완동물 대전에 있어 대기열이 정지됐습니다."
	L["Queue paused while queued for pet pvp."] = "애완동물pvp를 위해 대기하는 동안 대기열 정지"
	L["Queue"] = "대기열"
	L["Drag pets you want to level here.\n\nWhen a team is saved with one of these pets, the current leveling pet will take its place when the team is loaded.\n\nWhen a pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will become the current leveling pet.\n\nSlots with a \124cffffd200gold\124r border are controlled by the leveling queue."] = "레벨을 상향시킬 애완동물을 여기에 끌어놓으세요.\n\n이 애완동물 중 하나가 팀을 불러올 때, 현재 평준화 애완동물이 그 자리에 들어갈 것입니다.\n\n애완동물이 레벨25(아싸!)에 도달했을 때 대기열을 떠나고 대기열의 다음 애완동물이 현재 평준화 애완동물이 됩니다.\n\n\124cffffd200금\124r 테두리의 홈은 평준화 대기열에 의해 제어됩니다."
	L["Sort by:"] = "정렬 방식:"
	L["Sort all pets in the queue from level 1 to level 24."] = "레벨1부터 레벨24까지 대기열에 있는 모든 애완동물을 정렬합니다."
	L["Sort all pets in the queue for levels closest to 10.5."] = "레벨10.5에 가까운 대기열에 있는 모든 애완동물을 정렬합니다."
	L["Sort all pets in the queue from level 24 to level 1."] = "레벨24부터 레벨1까지 대기열에 있는 모든 애완동물을 정렬합니다."
	L["Sort all pets in the queue by their types."] = "유형에 의해 대기열에 있는 모든 애완동물을 정렬합니다."
	L["Active Sort"] = "정렬 활성화"
	L["The queue will stay sorted in the order chosen. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets while the queue is actively sorted."] = "대기열은 선택한 순서대로 정렬이 유지됩니다. 애완동물의 순서는 경험치를 얻거나 대기열에서 추가/제거 되면 자동으로 변경될 수 있습니다.\n\n대기열의 정렬이 활성화되어 있으면 애완동물의 순서를 수동으로 변경할 수 없게 됩니다."
	L["Pause Preferences"] = "우선권 정지" -- 수정
	L["Suspend all preferred loading of pets from the queue, except for pets that can't load."] = "불러올 수 없는 애완동물을 제외하고, 대기열에서 애완동물의 선출 작업을 중지합니다."
	L["Fill Queue"] = "대기열 채우기"
	L["Fill the leveling queue with one of each species that can level from the filtered pet browser, and for which you don't have a level 25 already."] = "애완동물 브라우저에서 걸러진 레벨을 올릴 수 있는 애완동물 각각 한 종류씩 평준화 대기열을 채웁니다, 이미 25레벨이 있는 것은 제외."
	L["Fill Queue More"] = "대기열 더 채우기"
	L["Fill the leveling queue with one of each species that can level from the filtered pet browser, regardless whether you have any at level 25 already."] = "애완동물 브라우저에서 걸러진 레벨을 올릴 수 있는 애완동물 각각 한 종류씩 평준화 대기열을 채웁니다, 이미 25레벨이 있는 것과 관계없이 포함."
	L["Empty Queue"] = "대기열 비우기"
	L["Remove all leveling pets from the queue."] = "대기열에서 모든 평준화 애완동물을 제거합니다."
	L["Are you sure you want to remove all pets from the leveling queue?"] = "정말로 평준화 대기열에서 모든 애완동물을 제거하시겠습니까?"
	L["No Active Sort"] = "정렬 활성화 안 함"
	L["Turn off Active Sort. Queued pets can then be rearranged and will not automatically reorder themselves.\n\nTo turn Active Sort back on, check %sActive Sort\124r in the Queue menu."] = "정렬 활성화를 끕니다. 대기중인 애완동물을 재배열할 수 있으며 자동으로 자신의 순서를 변경하지 않습니다.\n\n정렬 활성화를 켜시려면, 대기열 메뉴에서 %s정렬 활성화\124r를 선택하세요."
	L["Turn Off Active Sort?"] = "정렬 활성화를 끌까요?"
	L["Leveling Pets: %s%s"] = "평준화 애완동물: %s%s"
	L["Active Sort:"] = "정렬 활성화:"
	L["Add these pets to the queue?"] = "대기열에 애완동물을 추가 하시겠습니까?"
	L["This will add %s%d\124r pets to the leveling queue.\n\nYou can be more selective by filtering pets.\n\nFor instance, if you filter pets to High Level (15-24) and Rare, Fill Queue will only add rare pets between level 15 and 24."] = "이 평준화 대기열에 %s%d\124r마리의 애완동물을 추가합니다.\n\n당신은 애완동물을 필터링하여 보다 많은 선택을 할 수 있습니다.\n\n예를 들어, 고 레벨 (15-24) 및 희귀 애완동물을 필터링 할 경우, 대기열은 레벨 15에서 24 사이에 희귀 애완동물을 추가하여 채웁니다."
	L["This will add %s%d\124r pets to the leveling queue."] = "이 평준화 대기열에 %s%d\124r 애완동물을 추가합니다."

-- Panels\MiniQueue.lua

-- Panels\MiniPanel.lua
	L["This target has a saved team"] = "이 대상은 저장된 팀 있음"

-- Panels\OptionPanel.lua
	L["All Options"] = "모든 설정"
	L["Team & Targeting Options"] = "팀 & 대상 설정"
	L["Always Show When Targeting"] = "대상으로 선택됐을 때 항상 표시"
	L["Regardless whether a target's team is already loaded, show the Rematch window when you target something with a saved team."] = "대상의 팀이 이미 불려온 것과 관계없이, 대상에 저장된 팀이 무엇인지 Rematch 창을 표시합니다."
  L["Show After Pet Battle"] = "애완동물 대전 후 표시"
  L["Show the Rematch window after leaving a pet battle."] = "애완동물 대전을 떠난 후에 Rematch 창을 표시합니다."
	L["Preferred Window Mode"] = "선호하는 창 방식"
	L["Minimized Standalone"] = "작은 독립형" 
	L["When automatically showing the Rematch window, show the minimized standalone window."] = "Rematch 창을 자동으로 표시할 때, 작은 독립형 창으로 표시합니다."
	L["Maximized Standalone"] = "큰 독립형"
	L["When automatically showing the Rematch window, show the maximized standalone window."] = "Rematch 창을 자동으로 표시할 때, 큰 독립형 창으로 표시합니다."
	L["Pet Journal"] = "애완동물 도감"
	L["When automatically showing the Rematch window, show the pet journal."] = "Rematch 창을 자동으로 표시할 때, 애완동물 도감으로 표시합니다."
	L["Standalone Window Options"] = "독립형 창 설정"
	L["Use Custom Scale"] = "사용자 크기 사용"
	L["Change the relative size of the standalone window to anywhere between 50% and 200% of its standard size."] = "표준 크기의 50%와 200% 사이에 어디든 독립형 창의 상대적 크기를 변경합니다."
	L["Single Panel Mode"] = "단일 패널 방식"
	L["Collapse the maximized standalone window to one panel instead of two side by side.\n\nUsers of earlier versions of Rematch may find this mode more familiar."] = "나란히 두 개 대신 하나의 패널로 큰 독립형 창을 접습니다.\n\nRematch의 이전 버전의 사용자는 이 방식을 더 잘 알고 찾을 수 있습니다."
	L["Combine Pets And Queue"] = "애완동물과 대기열 합치기"
	L["In single panel mode, combine the Pets and Queue tabs together. A narrow queue will display to the right of the pet list instead of in a separate tab."] = "단일 패널 방식에서 애완동물과 대기열 탭을 함께 합칩니다. 나뉘었던 탭을 대신해 애완동물 목록의 오른쪽에 좁은 대기열로 표시됩니다."
	L["Keep Window On Screen"] = "화면에 창 유지"
	L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = "ESC 키를 누르거나 게임 메뉴로 이동하는 등의 숨겨할 상황에서도 독립형 창을 숨기지 않습니다."
	L["Even For Pet Battles"] = "애완동물 대전 동안에도"
	L["Keep the standalone window on the screen even when you enter pet battles."] = "애완동물 대전에 들어가도 화면에 독립형 창을 유지합니다."
	L["Even Across Sessions"] = "다음 접속에도"
	L["If the standalone window was on screen when logging out, automatically summon it on next login."] = "접속 종료 할 때 화면에 독립형 창이 있었다면, 다음에 접속할 때 자동으로 호출합니다."
	L["Don't Minimize With ESC Key"] = "ESC키로 최소화 금지"
	L["Don't minimize the standalone window when the ESCape key is pressed."] = "ESC 키를 누를 때 독립창을 최소화하지 않습니다."
	L["Lower Window Behind UI"] = "UI 뒤로 창 낮추기"
	L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = "UI의 다른 부분을 위쪽에 나타낼 수 있게 UI의 다른 부분 뒤로 숨게 독립형 창을 밀어냅니다."
	L["Move Panel Tabs To Right"] = "오른쪽으로 패널 탭 이동"
	L["Align the Pets, Teams, Queue and Options tabs to the right side of the standalone window."] = "애완동물, 팀, 대기열과 설정 탭을 독립형 창 오른쪽 옆으로 정렬합니다."
	L["Minimal Minimized Window"] = "작은 소형 창"
	L["Remove the titlebar and tabs when the standalone window is minimized."] = "독립창을 최소화 할 때 제목 표시줄과 탭을 제거합니다."
	L["Appearance Options"] = "외관 설정"
	L["Compact List Format"] = "작은 목록 형식"
	L["Use an alternate style of lists for Pets, Teams and Queue to display more on the screen at once.\n\n\124cffff4040This option requires a Reload."] = "애완동물, 팀, 대기열을 한 화면에 더 많이 표시하기 위해 바뀐 양식의 목록을 사용합니다.\n\n\124cffff4040이 설정은 재시작이 필요합니다."
	L["Use Smaller Text Too"] = "작은 글자 사용"
	L["Also use smaller text in the Compact List Format so more text displays on each button."] = "마찬가지로 각 단추에 더 많은 글자를 표시하도록 작은 목록 형식에 작은 글자를 사용합니다."
	L["Color Pet Names By Rarity"] = "품질로 애완동물 이름 색상화"
	L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = "품질과 동일한 색상으로 애완동물 이름을 만듭니다. 희귀엔 파랑, 고급엔 녹색 등으로."
	L["Hide Rarity Borders"] = "품질 테두리 숨김"
	L["Don't color the icon border for pets you own in the same color as its rarity."] = "품질과 동일한 색상으로 애완동물의 아이콘 테두리에 색을 칠하지 않습니다"
	L["Hide Level At Max Level"] = "최대 레벨은 레벨 숨김"
	L["If a pet is level 25, don't show its level on the pet icon."] = "애완동물이 레벨 25인 경우, 애완동물 아이콘에 레벨을 표시하지 않습니다."
	L["Hide Targets Below Teams"] = "팀 아래쪽에 대상 숨김"
	L["Hide the target name that appears beneath a team that is not named the same as its target."] = "그 대상과 같이 지정되지 않은 팀 밑에 나타난 대상 이름을 숨깁니다."
	L["Show Ability Numbers"] = "능력에 숫자 표시"
	L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = "능력을 펼칠 때, 사용하는 능력이 뭔지 알게 \"애완동물 이름 122\"와 같이 일반적인 표기법으로 숫자 1과 2로 표시합니다."
	L["Reverse Toolbar Buttons"] = "도구모음 단추 뒤집기"
	L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = "도구모음 단추(전투 애완동물 되살리기, 전투 애완동물 붕대, 탐험대 모자 등)의 순서를 뒤집습니다."
	L["Always Show Team Tabs"] = "팀 탭 항상 표시"
	L["Show team tabs along the right side of the window even if you're not on the team panel."] = "팀 패널에 있지 않을 때도 창의 오른쪽에 팀 탭을 표시합니다."
	L["Move Team Tabs To Left"] = "팀 탭 왼쪽으로 이동"
	L["Move the team tabs along the right side of the standalone window to the left side."] = "독립형 창의 오른쪽에 붙어있는 팀 탭을 왼쪽으로 이동합니다."
	L["Pet Card & Notes Options"] = "애완동물 카드 & 노트 설정"
	L["Allow Pet Cards To Be Pinned"] = "애완동물 카드에 고정핀 허용"
	L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = "화면의 다른 부분으로 애완동물 카드를 끌 때, 앞으로 모든 애완동물 카드를 같은 자리에 표시하고, 애완동물 카드를 이동하거나 고정 해제 단추를 클릭할 때 까지 카드를 고정합니다."
	L["Faster Pet Cards & Notes"] = "빠른 애완동물 카드 & 노트"
	L["Instead of a small delay before showing pet cards and notes, immediately show them as you mouseover pets and notes buttons."] = "애완동물과 노트 단추에 마우스를 갖다댔을 때, 애완동물 카드와 노트를 보여주기 전에 잠깐 지연시키는 대신 바로 표시합니다."
	L["Click For Pet Cards & Notes"] = "클릭으로 애완동물 카드 & 노트"
	L["Instead of automatically showing pet cards and notes when you mouseover them, require clicking the pet or notes button to display them."] = "마우스를 갖다댔을 때 애완동물 카드와 노트를 자동으로 보여주는 대신, 표시하려면 애완동물이나 노트 단추의 클릭이 필요합니다."
	L["Keep Notes On Screen"] = "화면에 노트 유지"
	L["Don't hide notes when the ESCape key is pressed or other times it would hide, such as changing tabs or closing Rematch."] = "ESC 키를 누르거나, Rematch를 닫거나 탭을 변경할 때에도 노트를 숨기지 않습니다."
	L["Show Notes Upon Targeting"] = "대상 선택시 노트 표시"
	L["When your target has a saved team with notes, automatically display and lock the notes."] = "대상에 노트와 함께 저장된 팀이 있다면, 자동으로 표시하고 노트를 고정합니다."
	L["Show Notes In Battle"] = "전투가 시작되면 노트 표시"
	L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "노트가 있는 팀을 불러오면, 애완동물 대전에 들어갈 때 노트를 표시하고 고정합니다."
	L["Only Once Per Team"] = "팀 당 하나만"
	L["Only display notes automatically the first time entering battle, until another team is loaded."] = "다른 팀을 불러오기 전까지, 첫 번째로 들어가는 대전에만 자동으로 노트를 표시합니다."
  L["Alternate Lore Font"] = "지식 글자 바꾸기"
  L["Use a more normal-looking font for lore text on the back of the pet card."] = "애완동물 카드 뒷면에 지식 글자를 더 평범해 보이는 글꼴로 사용합니다."
	L["Leveling Queue Options"] = "평준화 대기열 설정"
	L["Prefer Living Pets"] = "살아 있는 애완동물에게 우선권"
	L["When loading pets from the queue, skip dead pets and load living ones first."] = "대기열에서 애완동물을 불러올 때, 죽은 애완동물은 넘기고 살아있는 것을 먼저 부릅니다."
	L["Double Click To Send To Top"] = "두 번 클릭으로 꼭대기로 보내기"
	L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = "대기열 패널의 애완동물을 두 번 클릭하면, 소환하는 대신 대기열의 꼭대기로 보냅니다."
	L["Hide Leveling Pet Toast"] = "평준화 애완동물 토스트 숨김"
	L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "새로운 애완동물이 평준화 대기열에서 자동으로 불러올 때 '토스트' 팝업을 표시하지 않습니다."
	L["Automatically Level New Pets"] = "새 애완동물 자동 평준화"
	L["When you capture or learn a pet, automatically add it to the leveling queue."] = "애완동물을 사로잡거나 배울 때, 평준화 대기열에 자동으로 추가합니다."
	L["Only Pets Without A 25"] = "25레벨이 없는 애완동물 만"
	L["Only automatically level pets which don't have a version already at 25 or in the queue."] = "이미 25레벨이 되었거나 대기열에 없는 애완동물 만 자동 평준화합니다."
	L["Only Rare Pets"] = "희귀 애완동물 만"
	L["Only automatically level rare quality pets."] = "희귀 등급의 애완동물 만 자동으로 평준화"
	L["Pet Filters"] = "애완동물 필터"
	L["Reset Filters On Login"] = "접속하면 필터 초기화"
	L["When logging in, start with all pets listed and no filters active."] = "접속하면 모든 애완동물 목록과 적용된 필터 없이 시작합니다."
	L["Reset Sort With Filters"] = "필터로 정렬 초기화"
	L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = "필터를 제거할 경우에도 기본값으로 다시 정렬을 초기화합니다: 이름, 즐겨찾기 먼저로 정렬"
	L["Don't Reset Search With Filters"] = "필터로 검색 초기화 안 함"
	L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = "수동으로 필터를 지울 때에도, 검색 상자를 지우지 않습니다.\n\n접속하거나 비슷한 것 찾기와 같은 일부 작업은, 이 설정과 상관없이 언제나 검색을 초기화합니다"
	L["Miscellaneous Options"] = "기타 설정"
  L["Hide On Toolbar Right Click"] = "도구모음 우-클릭으로 숨김"
  L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = "도구모음 단추를 우-클릭으로 사용하면, 그 작업을 수행한 후 Rematch 창을 닫습니다."
	L["Disable Sharing"] = "공유 비활성화"
	L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "보내기 단추를 비활성화 하고 다른 사람에 의해 전송되어 들어오는 애완동물을 차단합니다. 가져오기와 내보내기는 계속 작동합니다."
	L["Don't display a popup when a team loads and a pet within the team can't be found."] = "팀을 부르고 팀 내에서 애완동물을 찾을 수 없을 경우, 팝업을 표시하지 않습니다."
	L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = "애완동물을 숨길 때에도 확인을 요구하지 않습니다.\n\n'기타' 애완동물 필터에서 숨겨진 애완동물을 볼 수 있습니다."
	L["Use Minimap Button"] = "미니맵 단추 사용"
	L["Place a button on the minimap to toggle Rematch and load favorite teams."] = "Rematch를 전환하고 즐겨찾는 팀을 불러올 단추를 미니맵에 설치합니다."
	L["Keep Companion"] = "동료 유지"
	L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = "팀을 불어온 후, 불러오기 전에 옆에 있던 동료를 다시 소환합니다; 또는 소환되어 있지 않았다면 애완동물을 해제합니다."
	L["Hide Tooltips"] = "툴팁 숨김"
	L["Hide the more common tooltips in Rematch."] = "Rematch 내의 일반적인 툴팁을 숨깁니다."
	L["Hide Extra Help"] = "특별 도움말 숨김"
	L["Hide the informational \"Help\" items found in many menus and on the pet card."] = "다수의 메뉴와 애완동물 카드에 있는 \"도움말\" 항목의 내용을 숨깁니다."
	L["Use Default Pet Journal"] = "기본 애완동물 도감 사용"
	L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "기본 애완동물 도감과 Rematch의 통합을 끕니다.\n\n여전히 단축키, /rematch 명령어 또는 설정에서 사용하는 경우 미니맵 단추를 통해 독립형 창으로 Rematch를 사용할 수 있습니다."
	L["Rematch version %s"] = "Rematch 버전 %s"
	L["The%s icon indicates new options."] = "%s아이콘은 새로운 설정을 나타냅니다."
	L["Anchor"] = "기준"
	L["Bottom Right"] = "오른쪽 아래"
	L["Top Right"] = "오른쪽 위"
	L["Bottom Left"] = "왼쪽 아래"
	L["Top Left"] = "왼쪽 위"
	L["Anchor: %s"] = "기준: %s"
	L["When the standlone window is minimized, send it to the %s corner."] = "독립형 창을 최소화 할 때,\n%s 구석으로 보냅니다."
	L["Current Scale: %d%%"] = "현재 크기: %d%%"
	L["Click here to choose a different scale for the standalone window."] = "다른 크기의 독립형 창을 선택하려면 여기를 클릭하십시오."
	L["\n\n%sThis will close the journal and open the standalone window."] = "\n\n\s이 도감을 닫고 독립형 창을 엽니다."
	L["Reload the UI now?"] = "지금 UI를 재시작하시겠습니까?"
	L["You've chosen to change the setting for Compact List Format.\n\nThis change doesn't take effect until a reload or logout."] = "작은 목록 형식에 대한 설정이 바뀌도록 선택되었습니다.\n\n이 변경 사항은 재시작하거나 종료할 때까지 적용되지 않습니다."
	L["Custom Scale"] = "사용자 크기"
	L["Keep this scale?"] = "이 크기를 유지합니까?"
	L["This scale determines the relative size of the standalone window, where 100% is the standard size."] = "표준 크기가 100%인 독립형 창의 상대적 크기를 결정합니다."

-- Widgets\TopPanel.lua
	L["Total Collected Pets"] = "수집한 전체 애완동물"
	L["Unique Collected Pets"] = "수집한 고유 애완동물"
	L["Pets Not Collected"] = "미수집 애완동물"
	L["Percent Collected"] = "수집한 비율"
	L["Max Level Pets"] = "최고 레벨 애완동물"
	L["Rare Quality Pets"] = "희귀 품질 애완동물"
	L["Unique Pets In The Game"] = "게임 내의 고유 애완동물"
	L["Unique Pets"] = "고유 애완동물"
	L["%s\n\nPets At Max Level: %s%d\124r\nPets Not Collected: %s%d\124r\n\n%s Click to display more about your collection."] = "%s\n\n최고 레벨의 애완동물: %s%d\124r\n미수집 애완동물: %s%d\124r\n\n%s 클릭으로 수집품에 대한 자세한 내용을 표시합니다."
	L["Collection Statistics"] = "수집 통계"
	L["There are %s%d\124r unique pets in the game."] = "게임 내에 %s%d\124r개의 고유 애완동물이 있습니다."
	L["You have %s%.1f%%\124r of all unique pets."] = "전체의 %s%.1f%%\124r의 고유 애완동물을 갖고 있습니다."
	L["Pets Collected"] = "수집된 애완동물"
	L["Pets At Max Level"] = "최대 레벨인 애완동물"
	L["Total"] = "전체"
	L["Unique"] = "고유"
	L["Duplicate Collected Pets"] = "중복 수집한 애완동물"
	L["Average Battle Pet Level"] = "평균 애완동물 대전 레벨"
	L["All unique pets in the game."] = "게임 내의 모든 고유 애완동물"
	L["All pets you've collected, including duplicates."] = "중복 포함, 수집한 모든 애완동물."
	L["The unique pets you've collected, not including duplicates."] = "중복 미포함, 수집한 고유 애완동물."
	L["The unique pets you're missing."] = "누락된 고유 애완동물"
	L["How much of each category's unique pets you've collected as a percent."] = "각 범주 별, 고유 애완동물의 수집 비율."
	L["All of your level 25 pets, including duplicates."] = "중복 포함, 레벨25 애완동물 전부."
	L["All of your rare quality pets, including duplicates."] = "중복 포함, 희귀 품질 애완동물 전부."
	L["Pet Types"] = "애완동물 유형"
	L["Sources"] = "출처"

-- Widgets\BottomPanel.lua
	L["Save As..."] = "..으로 저장"
	L["Save the currently loaded pets to a new team."] = "새 팀으로 현재 불러온 애완동물을 저장합니다."
	L["Save the currently loaded pets to the loaded team."] = "불러온 팀에 현재 불러온 애완동물을 저장합니다."
	L["Disable Rematch"] = "Rematch 미사용"
	L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "기본 애완동물 도감으로 복원하려면 이곳을 선택하지 않습니다.\n\n여전히 단축키, /rematch 명령어 또는 설정에서 사용하는 경우 미니맵 단추를 통해 독립형 창으로 Rematch를 사용할 수 있습니다."

-- Widgets\TeamTabs.lua
	L["Edit Tab"] = "탭 편집"
	L["Change the name or icon of this tab."] = "이 탭의 이름 또는 아이콘을 변경합니다."
	L["Custom Sort"] = "사용자 정렬"
	L["Remove Custom Sort"] = "사용자 정렬 제거"
	L["Are you sure you want to sort teams alphabetically in this tab?\n\nThe custom sort order will be lost and cannot be undone."] = "정말로 이 탭에서 가나다 순으로 팀을 정렬하시겠습니까?\n\n사용자 지정 정렬 순서를 잃게 되며 취소할 수 없습니다."
	L["While checked, you can rearrange the order of teams within this tab."] = "선택되어 있는 동안, 이 탭에서 팀의 순서를 재배열 할 수 있습니다."
	L["Set leveling preferences for all teams within this tab.\n\nIf a team within this tab also has preferences, the tab's preferences will take priority over the team's preferences."] = "이 탭 내의 모든 팀의 평준화 우선권을 설정합니다.\n\n이 탭 내의 개별 팀에 환경설정이 있는 경우, 탭의 우선권이 팀의 우선권보다 우선합니다."
	L["Export Tab"] = "탭 내보내기"
	L["Export all teams in this tab to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "포럼이나 전자우편과 같이 다른 곳에 문자열로 이 탭 내의 모든 팀을 내보낼 수 있습니다.\n\nRematch의 팀 가져오기를 통해 다른 Rematch 사용자는 그 팀을 붙여넣을 수 있습니다.\n\n하나를 우-클릭하고 공유 메뉴를 선택해 하나의 팀을 내보낼 수도 있습니다."
	L["Delete Tab"] = "탭 삭제"
	L["Delete this tab and move all of its teams to the default tab."] = "이 탭을 삭제하고 기본 탭으로 모든 팀을 이동합니다."
	L["Create New Tab"] = "새 탭 만들기"
	L["Teams: %d"] = "팀: %d"
	L["New Tab"] = "새 탭"
	L["Choose a name and icon"] = "이름과 아이콘 선택"
	L["Delete this tab?"] = "이 탭을 삭제하시겠습니까?"
	L["Deleting this tab will move its teams to the %s tab."] = "이 탭을 삭제하면 %s 탭으로 팀이 이동합니다."

-- Widgets\LoadedTeamPanel.lua
	L["Reload Team"] = "팀 다시 불러오기"
	L["Team Options"] = "팀 설정"
	L["When a team is loaded its name goes here. You can reload the team by clicking here or right-click for team options such as setting notes."] = "팀을 불러올 때, 이름이 이곳에 표시됩니다. 이곳을 클릭하여 팀을 다시 불러오거나 팀 설정에서 우-클릭으로 노트 설정할 수 있습니다."
	L["Last Loaded Team"] = "마지막에 불러온 팀"

-- Widgets\NarrowPanel.lua

-- Dialogs\Save.lua
	L["Target For This Team"] = "이 팀의 대상"
	L["A target stored in a team is used to decide which team to load when you return to that target.\n\nYou can save an unlimited number of teams to fight a target, but a target can only be saved in one team."] = "팀에 저장된 대상은 그 대상으로 돌아왔을 때 불러올 팀을 결정하는데 사용됩니다.\n\n대상과 싸울 팀의 숫자는 무제한으로 저장할 수 있습니다. 하지만, 대상은 하나의 팀에만 저장할 수 있습니다."
	L["Save As.."] = "..으로 저장"
	L["Save this team?"] = "이 팀을 저장하시겠습니까?"
	L["Save Notes & Preferences Too"] = "노트 & 우선권도 저장"
	L["Save Without Leveling Slots"] = "평준화 홈 없이 저장"
	L["All teams must have a name."] = "모든 팀은 이름이 있어야 합니다."
	L["This target already has a team."] = "이 대상은 이미 팀이 있습니다."
	L["A team already has this name."] = "팀은 이미 이 이름이 있습니다."
	L["Overwrite Team"] = "팀 덮어쓰기"
	L["Overwrite this team?"] = "이 팀을 덮어쓰시겠습니까?"
	L["The target %s%s\124r already has a team.\n\nA target can only have one team."] = "%s%s\124r 대상은 이미 팀이 있습니다\n\n대상은 하나의 팀만 보유할 수 있습니다."
	L["A team named %s%s\124r already exists.\n\nTeams without a target must have a unique name."] = "%s%s\124r|1이라는;라는; 이름의 팀이 이미 존재합니다.\n\n목표가 없는 팀의 이름은 없는 이름이어야 합니다."

-- Dialogs\Preferences.lua
	L["Minimum Health"] = "최저 체력"
	L["This is the minimum health preferred for a leveling pet.\n\nThe queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = "이 최저 체력은 평준화 애완동물에게 우선시됩니다.\n\n대기열에 적어도 이 정도의 체력과 평준화 애완동물을 우선시 합니다(어떤 선택을 했을 때 받을 예상 피해에 의해 조정됨)."
	L["Minimum Level"] = "최저 레벨"
	L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = "이 최저 레벨은 평준화 애완동물에게 우선시됩니다.\n\n레벨은 일정 량이 될 수 있습니다. 레벨 4.33은 레벨 5로 가는 경험치의 33%로 레벨 4입니다."
	L["Maximum Health"] = "최대 체력"
	L["This is the maximum health preferred for a leveling pet."] = "이 최대 체력은 평준화 애완동물에게 우선시됩니다."
	L["Maximum Level"] = "최대 레벨"
	L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = "이 최대 레벨은 평준화 애완동물에게 우선시됩니다.\n\n레벨은 일정 량이 될 수 있습니다. 레벨 23.45는 레벨 24로 가는 경험치의 45%로 레벨 23입니다."
	L["Or any"] = "또는"
	L["Allow low-health Magic and Mechanical pets to ignore the Minimum Health, since their racials allow them to often survive a hit that would ordinarily kill them."] = "그들의 유형은 그들이 보통 죽음에 이르는 타격에도 자주 생존할 수 있기 때문에, 체력이 낮은 마법과 기계 애완동물은 최저 체력을 무시하도록 허용합니다."
	L["Expected Damage Taken"] = "받을 것으로 예상되는 피해"
	L["Tab"] = "탭"
	L["Leveling Preferences"] = "평준화 우선권"
	L["Team Preferences"] = "팀 우선권"
	L["Tab Preferences"] = "탭 우선권"
	L["  For %s pets: %s%d%s"] = " %s 애완동물에겐: %s%d%s"
	L["%s %sTab Preferences"] = "%s %s 탭 우선권"
	L["%s%s Preferences Paused"] = "%s%s 우선권 중지"
	L["%s Resume Preferences"] = "%s 우선권 재시작"
	L["%s Pause Preferences"] = "%s 우선권 중지"
	L["Leveling Preferences For %s:"] = "%s|1을;를; 위한 평준화 우선권:"
	L["Expected damage taken"] = "받을 예상 피해"
	L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = "애완동물의 최소 체력이 받기로 예상되는 피해의 유형에 의해 조정될 수 있습니다."
	L["Damage expected"] = "예상 피해"
	L["  For %s pets: \124cffffd200%d"] = " %s 애완동물에겐: \124cffffd200%d"

-- Dialogs\Sideline.lua
	L["New Team"] = "새 팀"

-- Dialogs\Share.lua
	L["^(.-)%(.-NPC#(%d+)%)"] = nil
	L[":([^\n]-)[%(%[]*([12]).([12]).([12])[%)%]]*.-[\n]*"] = nil
	L[":([^\n]+)"] = nil
	L["\n%s*Preferred leveling pets: ([^\n]+)%."] = "\n%s*우선시되는 평준화 애완동물: ([^\n]+)%."
	L["at least (%d+) health"] = "최소한 (%d+) 체력"
	L["or any Magic/Mechanical"] = "또는 마법/기계"
	L[".+[,%(](.-)damage expected%)"] = ".+[,%(](.-)예상 피해%)"
	L["at most (%d+) health"] = "최대한 (%d+) 체력"
	L["at least level ([%d%.]+)"] = "최소한 레벨 ([%d%.]+)"
	L["at most level ([%d%.]+)"] = "최대한 레벨 ([%d%.]+)"
	L["^[Ll][Ee][Vv][Ee][Ll][Ii][Nn][Gg] [Pp][Ee][Tt]$"] = nil
	L["^[Cc][Aa][Rr][Rr][Yy] [Pp][Ee][Tt]$"] = nil
	L["%s (NPC#%d)"] = nil
	L["%s (%s NPC#%d)"] = nil
	L["%d: %s"] = nil
	L["%d: %s (%d,%d,%d)"] = nil
	L["Preferred leveling pets: %s."] = "우선시되는 애완동물 평준화: %s."
	L["at least %d health"] = "최소한 %d 체력"
	L["at least %d health (or any Magic/Mechanical)"] = "최소한 %d 체력 (또는 마법/기계)"
	L["at least %d health (%s damage expected)"] = "최소한 %d 체력 (%s 예상 피해)"
	L["at least %d health (or any Magic/Mechanical, %s damage expected)"] = "최소한 %d 체력 (또는 마법/기계, %s 예상 피해)"
	L["at most %d health"] = "최대한 %d 체력"
	L["at least level %s"] = "최소한 레벨 %s"
	L["at most level %s"] = "최대한 레벨 %s"
	L["Export Team"] = "팀 내보내기"
	L["Press Ctrl+C to copy these teams to the clipboard."] = "클립보드에 이 팀을 복사하려면 Ctrl+C를 누르십시오."
	L["Press Ctrl+C to copy this team to the clipboard."] = "클립보드에 이 팀을 복사하려면 Ctrl+C를 누르십시오."
	L["Include Preferences"] = "우선권 추가"
	L["Include Notes"] = "노트 추가"
	L["Press Ctrl+V to paste a team from the clipboard."] = "클립보드에서 팀을 붙여 넣으려면 Ctrl+V를 누르십시오."
	L["This is not a recognizable team."] = "확인할 수 있는 팀이 아닙니다."
	L["An existing team already has this %s."] = "이 %s|1은;는; 이미 존재하는 팀이 있습니다."
	L["target"] = "대상"
	L["name"] = "이름"
	L["Create a new copy"] = "새 복사본 만들기"
	L["Overwrite existing team"] = "현존하는 팀 덮어쓰기"
	L["%s%d\124r teams are in this import."] = "%s%d\124r개의 팀을 가져왔습니다."
	L["%s%d\124r have a name or target already used."] = "%s%d\124r개의 이름 또는 대상이 이미 사용되고 있습니다."
	L["Create new copies"] = "새 복사본 만들기"
	L["Overwrite existing teams"] = "현재 팀 덮어쓰기"
	L["Send"] = "보내기"
	L["Who do you want to send this team to?"] = "누구에게 이 팀을 보내시겠습니까?"
	L["Sending..."] = "보내는 중..."
	L["No response. Lag or they don't have Rematch?"] = "응답이 없습니다. 지연 또는 그들은 Rematch가 없나요?"
	L["Team successfully received!"] = "팀 수신 성공!"
	L["Sending...%d%%"] = "%d%% 보내는 중..."
	L["They're busy. Try again later."] = "그들은 바쁩니다. 나중에 다시 시도하십시오."
	L["They're in combat. Try again later."] = "그들은 전투중입니다. 나중에 다시 시도하십시오."
	L["They have team sharing disabled."] = "그들은 팀의 공유가 불가능합니다."
	L["Incoming Rematch Team!"] = "Rematch 팀이 들어왔습니다!"
	L["%s%s\124r has sent you a team named \"%s\" (for %s)."] = "%s%s\124r|1이;가; 당신에게 \"%s\"(%s|을;를; 위한)|1이라는;라는; 이름의 팀을 보냈습니다."
	L["%s%s\124r has sent you a team for %s."] = "%s%s\124r|1이;가; 당신에게 %s|을;를; 위한 팀을 보냈습니다."
	L["%s%s\124r has sent you a team named \"%s\"."] = "%s%s\124r|1이;가; 당신에게 \"%s\"|1이라는;라는; 이름의 팀을 보냈습니다."
	L["Import these teams?"] = "이 팀을 가져오시겠습니까?"
	L["Import"] = "가져오기"
	L["%s%d\124r Rematch teams have the same name."] = "%s%d\124r Rematch 팀은 같은 이름을 가지고 있습니다."

-- Dialogs\Tooltip.lua

-- Dialogs\ScriptFilter.lua
	L["Pet Variables"] = "애완동물 변수"
	L["Exposed API"] = "노출형 API"
	L["Test"] = "시험"
	L["line "] = "줄 "
	L["Pet Filter Script Error"] = "애완동물 필터 스크립트 오류"
	L["Error in %s"] = "%s 오류"
	L["\124TInterface\\RaidFrame\\ReadyCheck-NotReady:16\124t Error %s"] = "\124TInterface\\RaidFrame\\ReadyCheck-NotReady:16\124t %s 오류"
	L["\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t Script ran without errors!"] = "\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t 오류 없이 스크립트 실행!"
	L["\124cffffd200-\124r Scripts are a way to create custom pet filters.\n\n\124cffffd200-\124r Scripts are Lua code and require some knowledge of the language and API to create your own filters.\n\n\124cffffd200-\124r Scripts run for each pet and should return true if the pet is to be listed.\n\n\124cffffd200-\124r Some variables are filled in as the script runs for each pet. See \124cffffd200Pet Variables\124r.\n\n\124cffffd200-\124r Scripts run in a restricted environment with no access outside its environment. See \124cffffd200Exposed API\124r.\n\n\124cffffd200-\124r All variables/tables created exist only in this environment and disappear when the filter finishes.\n\n\124cffffd200-\124r If the first line of the script is a --comment, it will be used as a tooltip in the Script menu."] = "\124cffffd200-\124r 스크립트는 사용자 정의 애완동물 필터를 생성하는 방법입니다.\n\n\124cffffd200-\124r 스크립트는 Lua 코드이며, 자신만의 필터를 만들려면 언어와 API에 대한 약간의 지식이 필요합니다.\n\n\124cffffd200-\124r 각 애완동물에 스크립트가 실행되고 애완동물이 나열되면 참(true)을 반환해야 합니다.\n\n\124cffffd200-\124r 일부 변수는 각 애완동물에 스크립트가 실행되면서 채워집니다. \124cffffd200애완동물 변수\124r 참조.\n\n\124cffffd200-\124r 외부 환경의 접근 없이 제한된 환경에서 스크립트가 실행됩니다. \124cffffd200노출형 API\124r 참조.\n\n\124cffffd200-\124r 이 환경에서만 모든 변수/테이블이 생성되 존재하고 필터가 완료되면 사라집니다.\n\n\124cffffd200-\124r 스크립트의 첫 줄이 -- 주석이면, 스크립트 메뉴에 툴팁으로 사용됩니다."
	L["These variables are defined as the script runs for each pet:\n\n\124cffffd200owned\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is owned by the player.\n\n\124cffffd200petID\124r \124cffaaaaaa(string)\124r\nUnique ID of the owned pet, such as \"BattlePet-0-000004A98F18\".\n\n\124cffffd200speciesID\124r \124cffaaaaaa(number)\124r\nShared ID of the pet's family. Black Tabby Cats are species 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(string)\124r\nName given to the pet by the player.\n\n\124cffffd200level\124r \124cffaaaaaa(number)\124r\nLevel of the pet, or nil for uncollected pets.\n\n\124cffffd200xp\124r \124cffaaaaaa(number)\124r\nAmount of xp the pet has in its current level.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(number)\124r\nTotal amount of xp required to reach the pet's next level.\n\n\124cffffd200displayID\124r \124cffaaaaaa(number)\124r\nA numeric representation of a pet's model skin.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is favorited by the player.\n\n\124cffffd200name\124r \124cffaaaaaa(string)\124r\nTrue name of the pet species.\n\n\124cffffd200icon\124r \124cffaaaaaa(string)\124r\nTexture path of the pet's icon.\n\n\124cffffd200petType\124r \124cffaaaaaa(number)\124r\nValue between 1 and 10 for its type. 1=Humanoid, 2=Dragonkin, etc.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(number)\124r\nThe npcID of the pet when it's summoned.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(string)\124r\nFormatted text describing where the pet is from.\n\n\124cffffd200description\124r \124cffaaaaaa(string)\124r\nLore text of the species.\n\n\124cffffd200isWild\124r \124cffaaaaaa(boolean)\124r\nWhether the pet was a captured wild pet.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can battle.\n\n\124cffffd200tradable\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can be caged.\n\n\124cffffd200unique\124r \124cffaaaaaa(boolean)\124r\nWhether no more than one of the pet can be known at a time.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(table)\124r\nArray of abilityIDs used by the species.\n\n\124cffffd200levelList\124r \124cffaaaaaa(table)\124r\nArray of levels the abilityIDs are learned."] = "이러한 변수는 각 애완동물에 대해 스크립트의 실행으로 정의됩니다:\n\n\124cffffd200owned\124r \124cffaaaaaa(불 대수)\124r\n애완동물이 플레이어가 소유하고 있는지에 대한 여부.\n\n\124cffffd200petID\124r \124cffaaaaaa(문자열)\124r\n\"BattlePet-0-000004A98F18\" 처럼 소유한 애완동물의 고유 ID.\n\n\124cffffd200speciesID\124r \124cffaaaaaa(숫자)\124r\n애완동물의 가족의 공유 ID. 검은얼룩고양이는 species 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(문자열)\124r\n플레이어가 애완동물에게 준 이름.\n\n\124cffffd200level\124r \124cffaaaaaa(숫자)\124r\n애완동물의 레벨, 또는 미수집된 애완동물은 nil.\n\n\124cffffd200xp\124r \124cffaaaaaa(숫자)\124r\n현재 레벨에 있는 애완동물의 경험치의 양.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(숫자)\124r\n애완동물이 다음 레벨로 가기 위해 필요한 경험치의 총량.\n\n\124cffffd200displayID\124r \124cffaaaaaa(숫자)\124r\n애완동물의 모델 스킨의 숫자 표시.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(불 대수)\124r\n애완동물이 플레이어에게 즐겨찾기 되어 있는지 여부.\n\n\124cffffd200name\124r \124cffaaaaaa(문자열)\124r\n애완동물 종의 진짜 이름.\n\n\124cffffd200icon\124r \124cffaaaaaa(문자열)\124r\n애완동물 아이콘의 질감 경로.\n\n\124cffffd200petType\124r \124cffaaaaaa(숫자)\124r\n종류에 따른 1과 10 사이의 값. 1=인간형, 2=용족 등.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(숫자)\124r\n소환된 애완동물의 npcID.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(문자열)\124r\n애완동물이 어디에서 왔는지 설명하는 형식의 글자.\n\n\124cffffd200description\124r \124cffaaaaaa(문자열)\124r\n종의 지식 글자.\n\n\124cffffd200isWild\124r \124cffaaaaaa(불 대수)\124r\n애완동물이 사로잡은 야생 애완동물인지 여부.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(불 대수)\124r\n대전 가능한 애완동물인지 여부.\n\n\124cffffd200tradable\124r \124cffaaaaaa(불 대수)\124r\n우리에 넣을 수 있는 애완동물인지 여부.\n\n\124cffffd200unique\124r \124cffaaaaaa(불 대수)\124r\n한 번에 알 수 있는 애완동물이 하나뿐인지 여부.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(테이블)\124r\n종에 사용되는 abilityID에 대한 정렬.\n\n\124cffffd200levelList\124r \124cffaaaaaa(테이블)\124r\n배운 abilityID의 레벨에 대한 정렬."
	L["The script environment is restricted with access to only common Lua and the following:\n\n\124cffffd200C_PetJournal \124cffaaaaaa(table)\124r\nThe default API for journal functions.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(table)\124r\nThe default API for the battle UI.\n\n\124cffffd200GetBreed \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r The numeric breed (3-12) of a petID if one of the supported breed addons is enabled.\n\n\124cffffd200GetSource \124cffaaaaaa(function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The numeric source (1-10) of a speciesID. 1=Drop, 2=Quest, etc.\n\nA few iterator functions are also provided if you need to compare a pet against others. These are used in a for loop such as:\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- do something with speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next speciesID of all existing unique pets.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next petID of all owned pets.\n\n\124cffffd200AllPets \124cffaaaaaa(iterator function)\nReturns:\124r The next petID or speciesID of all pets in the master list. Owned pets return a petID string, uncollected pets return a speciesID number.\n\n\124cffffd200AllAbilities \124cffaaaaaa(iterator function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The next abilityID and level of the ability for a speciesID.\n\124cffffd200Note:\124r abilityList and levelList are already defined for each pet as your script runs. Use this iterator if you need to gather abilities of other pets for comparison. See the Unique Abilities script for an example.\n\n\124cffffd200If you would like anything else exposed please post a comment on wowinterface, curse or warcraftpet's Rematch 4.0 thread."] = "스크립트 환경은 Lua 규격 만이 접근이 허용되고 다음과 같이 제한됩니다:\n\n\124cffffd200C_PetJournal \124cffaaaaaa(테이블)\124r\n도감 함수에 대한 기본 API.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(테이블)\124r\n대전 UI에 대한 기본 API.\n\n\124cffffd200GetBreed \124cffaaaaaa(함수)\nArgument(인수):\124r petID\n\124cffaaaaaaReturns(반환):\124r 품종을 지원하는 애드온 중 하나를 사용하는 경우, petID의 숫자 품종은 (3-12)입니다.\n\n\124cffffd200GetSource \124cffaaaaaa(함수)\nArgument(인수):\124r speciesID\n\124cffaaaaaaReturns(반환):\124r speciesID의 숫자 소스는 (1-10)입니다. 1=획득, 2=퀘스트 등.\n\n다른 것과 애완동물을 비교해야 하는 경우, 몇 가지의 반복자 함수도 제공됩니다. 이것은 다음과 같은 루프에 사용됩니다:\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- do something with speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(반복자 함수)\nReturns(반환):\124r 현재 모든 고유 애완동물의 다음 speciesID.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(반복자 함수)\nReturns(반환):\124r 소유한 모든 애완동물의 다음 petID.\n\n\124cffffd200AllPets \124cffaaaaaa(반복자 함수)\nReturns(반환):\124r 주 목록 안에 모든 애완동물의 다음 petID 또는 specieesID. 수집된 애완동물은 petID 문자열을 반환하고, 미수집 애완동물은 speciesID 숫자를 반환합니다.\n\n\124cffffd200AllAbilities \124cffaaaaaa(반복자 함수)\nArgument(인수):\124r speciesID\n\124cffaaaaaaReturns(반환):\124r speciesID를 위한 능력의 다음 abilityID와 레벨.\n\124cffffd200Note:\124r 능력 목록과 레벨 목록은 이미 각 애완동물을 위해 정의된 스크립트를 실행합니다. 비교를 위해 다른 애완동물의 능력을 수집해야하는 경우, 이 반복자를 사용합니다. 예제로 고유 능력 스크립트를 참조하십시오.\n\n\124cffffd200무언가 다른 노출을 원하시면 wowinterface, curse 또는 warcraftpet's Rematch 4.0 스레드에 댓글을 달아주시기 바랍니다."

-- Frames\Frame.lua
	L["Pets"] = "애완동물"
	L["Options"] = "설정"
	L["Toggle Single Panel Mode"] = "단일 패널 방식 전환"
	L["Toggle between one panel or two panels side by side."] = "하나의 패널 또는 나란히 붙은 두개의 패널 사이를 전환합니다."

-- Frames\Journal.lua
	L["Enable Rematch"] = "Rematch 사용"
	L["Check this to use Rematch in the pet journal."] = "애완동물 도감에 Rematch를 사용하시려면 이것을 선택하세요."

end
